---
- name: Create Minecraft folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/minecraft

- name: Generate Minecraft container
  containers.podman.podman_container:
    name: minecraft-server
    image: docker.io/itzg/minecraft-server
    state: quadlet
    ports:
      - 25565:25565
    env:
      EULA: true
      ONLINE_MOD: false
      DIFFICULTY: "hard"
      MOTD: "§l§cAxcha§r §nserver"
    volume:
      - "/opt/minecraft:/data"
    quadlet_options:
      - AutoUpdate=registry
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target

- name: Start Minecraft
  ansible.builtin.systemd_service:
    name: minecraft-server.service
    state: started
    daemon_reload: yes
