gw:
    hosts:
        gw.tremoureux.fr:
            ansible_user: ENC[AES256_GCM,data:ONbAiQ==,iv:R3ciKAmdRW/SjucNMZE7uLP9NWOgnVXldigOWggrNfk=,tag:x6tWm29v3DKfr7qw7MJWEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-09T15:00:37Z"
    mac: ENC[AES256_GCM,data:rkxkIYYKkX+yuK+yuXLM4iGvitmWSjEvJgaMJRoVYRJ6FnLs1tsI9RbFQf31q3ms94SMslsCJb9VUfpF/1PzlfLE6q0/Fo5BFXtbgmsxoNgC83Lm7zJh6DDf7CD80HAvelXC2MdlW30RUXXTe65w6MW0uRReTeKt/jp825zCIzI=,iv:BOljGYS+ghOwiR12p2c+wH0okPUzyKPCkV8j5K4xheg=,tag:SIwlDb0bwmjfZ3ckE5/pEQ==,type:str]
    pgp:
        - created_at: "2024-03-09T15:00:37Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUbDO5aXdI8YSAQdAn0tf1icOHBSDtrxgh7rqaYQusQWa6DKbnyQlQDPYtHEw
            OB8g5LxDx43cpRcxvdI0qFv60569EuHl+elmGFguE2eAgCiSaAQVjO8ZdJ5qUhn7
            1GgBCQIQI9UFShkOszcs1ZVRYVdFur/A07Vxc5uHwf5HmKlj6iH7Hx1xam9o2HBu
            bmSCL162v/e3p6O/9Erv8GqKOz65UOERFCsDfHS+RBpm66ekFi7va7G0pSNL0mrZ
            ov9ZIlexIUOZBg==
            =R7O8
            -----END PGP MESSAGE-----
          fp: 7E97AEE02B26E52987441BBC653487B3CDE2DCE9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
