gw:
    hosts:
        gw.tremoureux.fr:
            ansible_user: ENC[AES256_GCM,data:f58l3w==,iv:FFurvNw1uDNBbJ+sgP/8BDf7wUMAjrLD0GIdHSOXwgs=,tag:zO70XbIrpU4ZkKWhluo6CQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-04-09T19:05:20Z"
    mac: ENC[AES256_GCM,data:k953kaijx3uOxIeLeThkCFqUxV3qGziupAi5VW/JaHiA9nyDhjVh2C8wi235A0NFSntHX1DoPEVWL2FskQFM677+87XeGt1EasJR8gFaBoaT9Da3wgVZN9bAgYpwsKFwmjgSYt0yFemFOVB2wijvVRzcQ3dv7d9ivYJFhdZ6Omk=,iv:46fRtHAhMsP1wdLoN8PbAjkBZUNfU6c9tEom/hGlWRM=,tag:4TlxREfnlL8zi6/K+FtBZw==,type:str]
    pgp:
        - created_at: "2024-04-09T19:05:20Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DUbDO5aXdI8YSAQdAxY3TU63MmsLFJZXsoWm/kpBsSQY2b0diR5TQXGlrqDIw
            s1NUzxvYDbTZjtdMeXtHAdvCKDa/6V0rmRn3lrQ/DBmPlkm5Ndc3UEThQh+UL/c4
            1GgBCQIQ0wuAd9yRJsDBLa42hRrJEk5zLTpyM1rIeE4mTdhre0xvrWCctMtuKbPH
            TpS9Ad+p/6J/zS/PEInncEB7ueTN+mMND5rx03yDIF0nfOb3YVu7MmW/XbEfJ+y9
            +zCVzzbLcj2/Zw==
            =wihc
            -----END PGP MESSAGE-----
          fp: 7E97AEE02B26E52987441BBC653487B3CDE2DCE9
    unencrypted_suffix: _unencrypted
    version: 3.8.1
