apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m0s
  ref:
    branch: zen
  secretRef:
    name: forgejo-auth
  url: https://codeberg.org/tsacha/homelab.git
