---
- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present

- name: Install boot packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
      - docker-ce
      - docker-ce-cli
      - git
    update_cache: yes

- name: Install yq
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: 0755

- meta: flush_handlers

# Common resources
- name: Common directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/rasp

- name: Rasp docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /opt/rasp/docker-compose.yaml

- name: Reverse proxy configuration
  ansible.builtin.template:
    src: Caddyfile.j2
    dest: /opt/rasp/Caddyfile

- name: Systemd unit
  ansible.builtin.template:
    src: unit.j2
    dest: /etc/systemd/system/rasp.service

- name: Boot directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/boot
    - /opt/boot/kea
    - /opt/boot/assets
    - /opt/boot/assets/nodes

- name: Download boot assets
  ansible.builtin.get_url:
    force: yes
    url: "{{ item.url }}"
    dest: "/opt/boot/assets/{{ item.dest }}"
  loop:
    -
      url: http://boot.ipxe.org/snponly.efi
      dest: snponly.efi
    -
      url: http://boot.ipxe.org/arm64-efi/snponly.efi
      dest: snponly-arm64.efi
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.7.0/vmlinuz-amd64
      dest: vmlinuz
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.7.0/initramfs-amd64.xz
      dest: initramfs.xz
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.7.0/vmlinuz-arm64
      dest: vmlinuz-arm64
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.7.0/initramfs-arm64.xz
      dest: initramfs-arm64.xz

- name: Boot iPXE menu
  ansible.builtin.template:
    src: menu.ipxe.j2
    dest: /opt/boot/assets/menu.ipxe

- name: Talos iPXE
  ansible.builtin.template:
    src: talos.ipxe.j2
    dest: "/opt/boot/assets/nodes/{{ item.value.mac|replace(':', '-') }}.ipxe"
  loop: "{{ nodes|dict2items }}"

- name: Kea DHCPv6 configuration file
  ansible.builtin.template:
    src: dhcp6.json.j2
    dest: /opt/boot/kea/dhcp6.json

- name: Start rasp services
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: rasp
