---
- name: Install boot packages
  ansible.builtin.apt:
    pkg:
      - kea-dhcp6-server
      - tftpd-hpa
      - caddy
    update_cache: yes

- name: Download boot assets
  ansible.builtin.get_url:
    force: yes
    url: "{{ item.url }}"
    dest: "/srv/tftp/{{ item.dest }}"
  loop:
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.10.2/vmlinuz-amd64
      dest: vmlinuz-x86_64
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.10.2/initramfs-amd64.xz
      dest: initramfs-x86_64.xz
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.10.2/vmlinuz-arm64
      dest: vmlinuz-arm64
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.10.2/initramfs-arm64.xz
      dest: initramfs-arm64.xz

- block:
  - name: DHCPv6 Boot configuration
    ansible.builtin.template:
      src: dhcp6.json
      dest: /etc/kea/kea-dhcp6.conf
    notify: Restart Kea

  - name: Caddy boot configuration
    ansible.builtin.template:
      src: caddyfile
      dest: /etc/caddy/Caddyfile
    notify: Restart Caddy

  - name: Copy snponly (x86_64)
    ansible.builtin.copy:
      src: snponly.x86_64.efi
      dest: /srv/tftp

  - name: Copy menu.ipxe
    ansible.builtin.template:
      src: menu.ipxe
      dest: /srv/tftp

  - name: Nodes PXE directory
    ansible.builtin.file:
      path: /srv/tftp/nodes
      state: directory

  tags: boot_update
