[tools]
"python" = "latest"
"pipx:makejinja" = "latest"
aqua = "latest"
talosctl = "latest"
yq = "latest"
task = "latest"
age = "latest"
flux2 = "latest"
helm = "latest"
velero = "latest"
"aqua:kopia/kopia" = "latest"
