---
version: '3'

tasks:
  prereqs:
    cmds:
      - helm repo add cilium https://helm.cilium.io/
  # Secrets
  git/encrypt:
    cmds:
      - sops --encrypt secrets.yaml > secrets.yaml.enc
      - sops --input-type yaml --output-type yaml --encrypt talos/data/talosconfig > talos/data/talosconfig.enc
      - sops --encrypt ansible/inventory/gw.yaml > ansible/inventory/gw.yaml.enc
      - sops --encrypt ansible/inventory/proxmox.yaml > ansible/inventory/proxmox.yaml.enc
      - |
        for f in $(ls talos/data/*.yaml); do
          sops --encrypt $f > $f.enc
        done;
      - |
        for n in $(ls talos/data/iso/); do
          sops --input-type yaml --output-type yaml --encrypt talos/data/iso/$n/meta-data > talos/data/iso/$n/meta-data.enc
          sops --input-type yaml --output-type yaml --encrypt talos/data/iso/$n/user-data > talos/data/iso/$n/user-data.enc
          sops --input-type yaml --output-type yaml --encrypt talos/data/iso/$n/network-config > talos/data/iso/$n/network-config.enc
        done;

  git/decrypt:
    cmds:
      - sops --input-type yaml --output-type yaml --decrypt secrets.yaml.enc > secrets.yaml
      - sops --input-type yaml --output-type yaml --decrypt talos/data/talosconfig.enc > talos/data/talosconfig
      - sops --input-type yaml --output-type yaml --decrypt ansible/inventory/gw.yaml.enc > ansible/inventory/gw.yaml
      - sops --input-type yaml --output-type yaml --decrypt ansible/inventory/proxmox.yaml.enc > ansible/inventory/proxmox.yaml
      - |
        for f in $(ls talos/data/*.yaml.enc); do
          echo $f
          sops --input-type yaml --output-type yaml --decrypt $f > ${f%.*}
        done;
      - |
        for n in $(ls talos/data/iso/); do
          sops --input-type yaml --output-type yaml --decrypt talos/data/iso/$n/meta-data.enc > talos/data/iso/$n/meta-data
          sops --input-type yaml --output-type yaml --decrypt talos/data/iso/$n/user-data.enc > talos/data/iso/$n/user-data
          sops --input-type yaml --output-type yaml --decrypt talos/data/iso/$n/network-config.enc > talos/data/iso/$n/network-config
        done;
  # Gateway things
  gw/dns:
    dir: ansible/
    cmds:
      - ansible-playbook -i inventory/gw.yaml gw.yaml -t dns-restart

  # Talos
  talos/nocloud-iso:
    cmds:
      - mkdir -p talos/iso
      - |
        docker run --rm -i -w /work -v "$PWD":/work --entrypoint sh ghcr.io/siderolabs/imager:v1.4.6 -c '
          installer iso --arch amd64 --output talos/iso/
          xorriso -osirrox on -indev ./talos/iso/talos-amd64.iso -extract / /tmp &&
          rm -f ./talos/iso/talos-amd64.iso &&
          sed -i 's/talos.platform=metal/talos.platform=nocloud/g' /tmp/boot/grub/grub.cfg &&
          grub-mkrescue --compress=xz --output=./talos/iso/talos-amd64-nocloud.iso /tmp'
      - |
        for hypervisor in $( yq -r ".hypervisors|to_entries[].key" secrets.yaml ); do
          scp talos/iso/talos-amd64-nocloud.iso root@$(yq -r ".hypervisors.$hypervisor.hostname" secrets.yaml):/var/lib/vz/template/iso/
        done
  talos/gensecrets:
    cmds:
      - mkdir -p talos/data
      - talosctl gen secrets --force -o talos/data/secrets.yaml
  talos/genconfig:
    vars:
      endpoint:
        sh: yq -r ".kube.endpoint" secrets.yaml
      cluster:
        sh: yq -r ".kube.cluster" secrets.yaml
    cmds:
      - gomplate -d secrets.yaml -f talos/templates/all.patch.template -o talos/data/all.patch.yaml
      - gomplate -d secrets.yaml -f talos/templates/cp.patch.template -o talos/data/cp.patch.yaml
      - gomplate -d secrets.yaml -f talos/templates/bgp.yaml.template -o talos/data/bgp.yaml
      - gomplate -d secrets.yaml -f talos/templates/cilium-options.yaml.template -o talos/data/cilium-options.yaml
      - gomplate --plugin helm=helm -f talos/templates/cilium-inline.patch.template -o talos/data/cilium-inline.yaml
      - talosctl gen config --force --with-secrets talos/data/secrets.yaml {{ .cluster }} https://{{ .endpoint }}:6443 --config-patch @talos/data/all.patch.yaml --config-patch-control-plane=@talos/data/cp.patch.yaml --output-dir talos/data/
      - talosctl --talosconfig talos/data/talosconfig config endpoint {{ .endpoint }}
      - talosctl --talosconfig talos/data/talosconfig config node {{ .endpoint }}
      - mkdir -p talos/data/iso
  talos/gennodes:
    cmds:
      - |
        for node in $( yq -r ".nodes|to_entries[].key" secrets.yaml ); do
          mkdir -p talos/data/iso/$node
          NODE=$node gomplate -d secrets.yaml -f talos/templates/node.patch.template -o talos/data/$node.patch.yaml
          talosctl machineconfig patch talos/data/controlplane.yaml --patch @talos/data/$node.patch.yaml --patch @talos/data/cilium-inline.yaml --output talos/data/iso/$node/user-data
          NODE=$node gomplate -d secrets.yaml -f talos/templates/cloud-init-network.template -o talos/data/iso/$node/network-config
          NODE=$node gomplate -d secrets.yaml -f talos/templates/cloud-init-meta-data.template -o talos/data/iso/$node/meta-data
          mkisofs -output talos/data/iso/$node/cidata.iso -V cidata -r -J talos/data/iso/$node/user-data talos/data/iso/$node/meta-data talos/data/iso/$node/network-config
          scp talos/data/iso/$node/cidata.iso root@$(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).hostname" secrets.yaml):/var/lib/vz/template/iso/
        done;
  talos/vms:
    cmds:
      - |
        for node in $( yq -r ".nodes|to_entries[].key" secrets.yaml ); do
          ssh root@$(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).hostname" secrets.yaml) -C \
            qm create $(yq -r ".nodes.$node.id" secrets.yaml) \
              --name $node \
              --memory 6144 \
              --net0 virtio,bridge=vmbr0 \
              --cores 4 \
              --sockets 1 \
              --scsi0 local-lvm:50,iothread=1 \
              --scsi1 $(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).fstype" secrets.yaml):250,iothread=1 \
              --scsi2 local:iso/talos-amd64-nocloud.iso,media=cdrom \
              --scsi3 local:iso/cidata.iso,media=cdrom \
              --efidisk0 local-lvm:0,efitype=4m \
              --bios ovmf \
              --vga qxl \
              --ostype l26 \
              --scsihw virtio-scsi-single \
              --cpu x86-64-v2-AES \
              --onboot 1
          ssh root@$(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).hostname" secrets.yaml) -C qm start $(yq -r ".nodes.$node.id" secrets.yaml)
        done;
  talos/install:
    cmds:
      - talosctl --talosconfig talos/data/talosconfig bootstrap
      - talosctl --talosconfig talos/data/talosconfig kubeconfig -f
  talos/postinstall:
    cmds:
      - kubectl apply -f bgp.yaml
  talos/destroy:
    cmds:
      - |
        for node in $( yq -r ".nodes|to_entries[].key" secrets.yaml ); do
          ssh root@$(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).hostname" secrets.yaml) -C qm stop $(yq -r ".nodes.$node.id" secrets.yaml) || /bin/true
          ssh root@$(yq -r ".hypervisors.$(yq -r ".nodes.$node.hypervisor" secrets.yaml).hostname" secrets.yaml) -C qm destroy $(yq -r ".nodes.$node.id" secrets.yaml) || /bin/true --destroy-unreferenced-disks=true --purge
        done;
