---
version: '3'

includes:
  gw: ./tasks/gw.yaml
  git: ./tasks/git.yaml
  boot: ./tasks/boot.yaml
  talos: ./tasks/talos.yaml
  flux: ./tasks/flux.yaml
  ceph: ./tasks/ceph.yaml
  secrets: ./tasks/secrets.yaml
