# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  default: go-task --list
includes:
  bootstrap: ./tasks/bootstrap.yaml
  mikrotik: ./tasks/mikrotik.yaml
  talos: ./tasks/talos.yaml
  renovate: ./tasks/renovate.yaml
  secrets: ./tasks/secrets.yaml
  restic: ./tasks/restic.yaml
