# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  default: go-task --list
includes:
  templates: ./tasks/templates.yaml
  gw: ./tasks/gw.yaml
  mikrotik: ./tasks/mikrotik.yaml
  home: ./tasks/home.yaml
  renovate: ./tasks/renovate.yaml
  restic: ./tasks/restic.yaml
