apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pocketid
  namespace: apps
spec:
  parentRefs:
    - name: gw-apps
  hostnames:
    - "{{ .Values.auth.pocketid_vhost }}"
  rules:
    - backendRefs:
        - name: pocketid
          namespace: apps
          port: 80
