apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: home-tremoureux-fr
  namespace: flux-system
spec:
  interval: 10m
  url: ssh://git@github.com/tsacha/homelab
  ref:
    branch: main
  secretRef:
    name: github-deploy-key
