apiVersion: batch/v1
kind: CronJob
metadata:
  name: rclone-sync
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: rclone-sync
              image: rclone/rclone:latest
              command:
                - sh
                - -c
                - |
                  rclone sync "seedbox:/home/neandre/" "/media/torrents/" \
                    --config /config/rclone.conf \
                    --include "/movies/**" \
                    --include "/shows/**" \
                    --fast-list \
                    --tpslimit 3 \
                    --checkers 2 \
                    --size-only \
                    -P
              volumeMounts:
                - name: rclone-config-volume
                  mountPath: /config
                - name: ssh-key-volume
                  mountPath: /root/.ssh
                  readOnly: true
                - name: media-storage
                  mountPath: /media
          volumes:
            - name: rclone-config-volume
              configMap:
                name: rclone-config
            - name: ssh-key-volume
              secret:
                secretName: rclone-ssh-key
                items:
                  - key: id_ed25519
                    path: id_ed25519
                defaultMode: 0600
            - name: media-storage
              hostPath:
                path: /media
                type: Directory
