apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: papra-docs
  annotations:
    k8up.io/backup: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
