---
- name: Generate Jellyfin container
  containers.podman.podman_container:
    name: jellyfin
    image: ghcr.io/jellyfin/jellyfin
    state: quadlet
    network: host
    ports:
      - 8096:8096
    device:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volume:
      - "/opt/jellyfin/config:/config"
      - "/opt/jellyfin/cache:/cache"
      - "/opt/jellyfin/media:/media"
      - "/mnt/seedbox:/seedbox"
    quadlet_options:
      - AutoUpdate=registry
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target

- name: Start Jellyfin
  ansible.builtin.systemd_service:
    name: jellyfin.service
    state: started
    daemon_reload: yes
