---
- name: Install seedbox sync packages
  ansible.builtin.apt:
    pkg:
      - rclone
    update_cache: yes

- name: Create mount.rclone symlink
  ansible.builtin.file:
    src: /bin/rclone
    dest: /usr/sbin/mount.rclone
    state: link

- name: Create rclone configuration
  ansible.builtin.template:
    src: rclone
    dest: /opt/.rclone

- name: Create rclone mount unit file
  ansible.builtin.template:
    src: rclone-unit
    dest: /etc/systemd/system/mnt-seedbox.mount

- name: Mount Seedbox
  ansible.builtin.systemd_service:
    name: mnt-seedbox.mount
    state: started
    daemon_reload: yes

- name: Sync folders unit
  ansible.builtin.template:
    src: sync.unit
    dest: /etc/systemd/system/sync@.service

- name: Sync folders timer
  ansible.builtin.template:
    src: sync.timer
    dest: /etc/systemd/system/sync@.timer

- name: Sync Movies
  ansible.builtin.systemd_service:
    name: sync@movies.timer
    state: started
    enabled: true
    daemon_reload: yes

- name: Sync Shows
  ansible.builtin.systemd_service:
    name: sync@shows.timer
    state: started
    enabled: true
    daemon_reload: yes
