# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  kvm:
    desc: Start a VM with cloud-init
    dir: boot
    cmds:
      - |
        if [ ! -f upstream.img ]; then
          wget https://cloud-images.ubuntu.com/plucky/current/plucky-server-cloudimg-amd64.img -O upstream.img
        fi

        cp -f upstream.img current.img
        qemu-img resize current.img 20G

        cp ../private/boot/cloud-init/user-data.yaml user-data
        cp ../private/boot/cloud-init/meta-data.yaml meta-data
        cp ../private/boot/cloud-init/network-config-eth.yaml network-config
        genisoimage -output seed.iso -V cidata -r -J ./user-data  ./meta-data ./network-config
        rm -f user-data meta-data network-config

        qemu-system-x86_64  \
          -machine accel=kvm \
          -bios /usr/share/ovmf/x64/OVMF.4m.fd \
          -cpu host \
          -m 2G \
          -boot order=d \
          -nographic \
          -netdev bridge,id=net0,br=br \
          -device virtio-net-pci,netdev=net0,id=nic1 \
          -drive if=virtio,format=qcow2,file=current.img \
          -drive file=seed.iso,format=raw,if=virtio
  install:
    dir: boot
    cmds:
      - |
        if [ ! -f raspi.img.xz ]; then
            wget https://cdimage.ubuntu.com/releases/25.04/release/ubuntu-25.04-preinstalled-server-arm64+raspi.img.xz -O raspi.img.xz
        fi

        cat <<EOF
        xzcat ./boot/raspi.img.xz | sudo dd status=progress bs=4M of={{ .CLI_ARGS }}
        sudo mount {{ .CLI_ARGS }}2 /mnt/
        sudo mount {{ .CLI_ARGS }}1 /mnt/boot/
        sudo cp ./private/boot/cloud-init/user-data.yaml /mnt/boot/user-data
        sudo cp ./private/boot/cloud-init/meta-data.yaml /mnt/boot/meta-data
        sudo cp ./private/boot/cloud-init/network-config-wlan.yaml /mnt/boot/network-config
        sudo umount /mnt/boot
        sudo umount /mnt
        sync
        EOF
  postinstall:
    vars:
      ENDPOINT:
        sh: yq '.boot.fqdn' private/inventory.yaml
    cmds:
      - task: ipxe
      - |
        sftp root@{{ .ENDPOINT }} << EOF
          mkdir /etc/jool
          put ./private/boot/nat64/* /etc/jool/
          put ./private/boot/dns64/* /etc/unbound/unbound.conf.d/
          put ./private/boot/dhcp6/* /etc/kea/
          put ./private/boot/ipxe/* /srv/tftp/
          put ./private/boot/http/* /etc/caddy/
          put ./boot/ipxe/src/bin-x86_64-efi/snponly.efi /srv/tftp/snponly.x86_64.efi
          put ./boot/ipxe/src/bin-arm64-efi/snponly.efi /srv/tftp/snponly.arm64.efi
        EOF
        ssh root@{{ .ENDPOINT }} "
          systemctl restart unbound jool caddy kea-dhcp6-server;
          bash /etc/caddy/dl.sh
        "
  ipxe:
    desc: Generate iPXE EFI files
    dir: boot
    status:
      - test -f ipxe/src/bin-arm64-efi/snponly.efi
      - test -f ipxe/src/bin-x86_64-efi/snponly.efi
    cmds:
      - |
        rm -Rf ipxe/
        git clone https://github.com/ipxe/ipxe.git
        git apply ../templates/boot/ipxe/buffer.patch
        pushd ipxe/src
        make -j8 bin-x86_64-efi/snponly.efi
        make -j8 CROSS=aarch64-linux-gnu- bin-arm64-efi/snponly.efi
