---
version: '3'

tasks:
  apply:
    cmds:
      - flux reconcile -n flux-system source git flux-system
      - flux reconcile -n flux-system kustomization flux-system
      - flux reconcile -n flux-system kustomization apps
