# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  HOME_CLUSTER:
    sh: yq -r '.network.fqdn|sub("\\.";"-")' .private/inventory.yaml 2>/dev/null || /bin/true
  FORGEJO_USER:
    sh: yq -r '.flux.forgejo_user' .private/inventory.yaml 2>/dev/null || /bin/true
  FORGEJO_PAT:
    sh: yq -r '.flux.forgejo_pat' .private/inventory.yaml 2>/dev/null || /bin/true
tasks:
  flux:
    cmds:
      - |
        export KUBECONFIG=~/.kube/clusters/{{.HOME_CLUSTER}}.yaml
        kubectl get ns flux-system || kubectl create ns flux-system
        kubectl -n flux-system get secrets forgejo-auth || kubectl -n flux-system create secret generic forgejo-auth \
          --from-literal=username={{.FORGEJO_USER}} \
          --from-literal=password={{.FORGEJO_PAT}}

        kubectl -n flux-system get secrets sops-age || cat ~/.config/sops/age/keys.txt | kubectl create secret generic sops-age \
          --namespace=flux-system \
          --from-file=age.agekey=/dev/stdin

        kubectl apply --server-side -f clusters/home/flux-system/gotk-components.yaml
        pushd clusters/home/flux-system
        kubectl apply --server-side -k .
        popd
  cni:
    desc: Install Cilium with Gateway API CRDs
    cmds:
      - |
        export KUBECONFIG=~/.kube/clusters/{{.HOME_CLUSTER}}.yaml
        export CILIUM_VERSION=1.20.1 # renovate: datasource=github-releases depName=cilium packageName=cilium/cilium
        export GATEWAY_API_VERSION=v1.6.1 # renovate: datasource=github-releases depName=gateway-api packageName=kubernetes-sigs/gateway-api
        kubectl apply --server-side -f https://github.com/kubernetes-sigs/gateway-api/releases/download/$GATEWAY_API_VERSION/experimental-install.yaml
        helm repo add cilium https://helm.cilium.io/
        bash tasks/cilium-values.sh home \
          | helm upgrade --install cilium cilium/cilium -n kube-system --version=$CILIUM_VERSION -f -
  bgp:
    desc: Apply BGP configuration for Cilium
    cmds:
      - sops -d clusters/home/infra/bgp.sops.yaml | KUBECONFIG=~/.kube/clusters/{{.HOME_CLUSTER}}.yaml kubectl delete --ignore-not-found -f -
      - sops -d clusters/home/infra/bgp.sops.yaml | KUBECONFIG=~/.kube/clusters/{{.HOME_CLUSTER}}.yaml kubectl apply -f -
