# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  lookup:
    desc: Dry-run Renovate locally to see detected deps and available updates
    vars:
      GH_PAT:
        sh: yq '.renovate.gh_pat' .private/inventory.yaml
    cmds:
      - |
        LOG_LEVEL=debug \
        RENOVATE_GITHUB_COM_TOKEN={{.GH_PAT}} \
        RENOVATE_REQUIRE_CONFIG=optional \
        npx -y renovate --dry-run --platform=local --dry-run=lookup
