# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  SECRETS: clusters/home/vars/app/cluster-secrets.sops.yaml
  RESTIC_PASSWORD:
    sh: sops -d {{.SECRETS}} | yq '.stringData.RESTIC_PASSWORD'
  AWS_ACCESS_KEY_ID:
    sh: sops -d {{.SECRETS}} | yq '.stringData.S3_ACCESS_KEY'
  AWS_SECRET_ACCESS_KEY:
    sh: sops -d {{.SECRETS}} | yq '.stringData.S3_SECRET_KEY'
  RESTIC_ENDPOINT:
    sh: sops -d {{.SECRETS}} | yq '.stringData.S3_ENDPOINT'
  RESTIC_REGION:
    sh: sops -d {{.SECRETS}} | yq '.stringData.S3_ENDPOINT | sub("^https?://s3\.", "") | sub("\..*$", "")'
tasks:
  cmd:
    desc: Run restic commands on backups
    env:
      RESTIC_PASSWORD: "{{.RESTIC_PASSWORD}}"
      AWS_ACCESS_KEY_ID: "{{.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{.AWS_SECRET_ACCESS_KEY}}"
    cmds:
      - restic -r s3:{{.RESTIC_ENDPOINT}}/{{.CLI_ARGS}}
  s3:
    desc: Run s3 commands on backups
    env:
      AWS_ACCESS_KEY_ID: "{{.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{.AWS_SECRET_ACCESS_KEY}}"
      AWS_ENDPOINT_URL: "{{.RESTIC_ENDPOINT}}"
      AWS_DEFAULT_REGION: "{{.RESTIC_REGION}}"
    cmds:
      - aws s3 {{.CLI_ARGS}}
