# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  RESTIC_PASSWORD:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.restic' || echo ""
  AWS_ACCESS_KEY_ID:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.ak' || echo ""
  AWS_SECRET_ACCESS_KEY:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.sk' || echo ""
  RESTIC_ENDPOINT:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.endpoint' || echo ""
  RESTIC_BUCKET:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.bucket' || echo ""
  RESTIC_REGION:
    sh: test -n "home" && test -n "apps" && sops -d clusters/home/apps/values.sops.yaml | yq '.backup.region' || echo ""
tasks:
  cmd:
    desc: Run restic commands on backups
    env:
      RESTIC_PASSWORD: "{{.RESTIC_PASSWORD}}"
      AWS_ACCESS_KEY_ID: "{{.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{.AWS_SECRET_ACCESS_KEY}}"
    cmds:
      - restic -r s3:{{.RESTIC_ENDPOINT}}/{{.CLI_ARGS}}
  s3:
    desc: Run s3 commands on backups
    env:
      AWS_ACCESS_KEY_ID: "{{.AWS_ACCESS_KEY_ID}}"
      AWS_SECRET_ACCESS_KEY: "{{.AWS_SECRET_ACCESS_KEY}}"
      AWS_ENDPOINT_URL: "{{.RESTIC_ENDPOINT}}"
      AWS_DEFAULT_REGION: "{{.RESTIC_REGION}}"
    cmds:
      - aws s3 {{.CLI_ARGS}}
