
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'

tasks:
  encrypt:
    vars:
      dirs:
        sh: find .decrypted/ -type d
      files:
        sh: find .decrypted/ -type f -path "*.yaml"
    cmds:
      - for: {var: dirs}
        cmd: mkdir -p {{ replace ".decrypted/" "secrets/" .ITEM }}

      - for: {var: files}
        silent: true
        cmd: |
          dst="{{ .ITEM | replace `.decrypted/` `secrets/` | replace `.yaml` `.sops.yaml` | replace `.json` `.sops.json` }}"

          if [ ! -f "$dst" ]; then
            sops -e "{{ .ITEM }}" > $dst
          else
            if ! diff -q <(sops -d $dst | yq -N '...comments=""') <(yq -N '...comments=""' {{.ITEM}}) > /dev/null; then
                sops -e "{{.ITEM}}" > $dst
                echo "Re-encrypted $dst"
            fi
          fi
  .decrypt:
    vars:
      dirs:
        sh: find secrets/ -type d
      files:
        sh: find secrets/ -type f -path "*.sops*"
    cmds:
      - for: {var: dirs}
        cmd: mkdir -p {{ replace "secrets/" ".decrypted/" .ITEM }}
      - for: {var: files}
        cmd: sops -d {{ .ITEM }} > {{ replace "sops." "" (replace "secrets/" ".decrypted/" .ITEM) }}
