# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
tasks:
  gen:
    desc: Generate full configuration for Talos
    cmds:
      - task: restore
      - task: init
      - task: config
      - for:
          var: NODES
        task: genmachine
        vars:
          NODE: '{{ .ITEM }}'
      - for:
          var: NODES
        task: ipxe
        vars:
          NODE: '{{ .ITEM }}'
  restore:
    internal: true
    desc: Import Talos secrets from repository
    status:
      - test -f private/talos/talosconfig
      - test -f private/talos/secrets.yaml
    cmds:
      - |
        if [ -f talos/talosconfig.sops.yaml ] && [ -f talos/secrets.sops.yaml ]; then
          sops -d talos/talosconfig.sops.yaml > private/talos/talosconfig
          sops -d talos/secrets.sops.yaml > private/talos/secrets.yaml
        fi
  init:
    internal: true
    desc: Initialize Talos cluster secrets and tokens
    status:
      - test -f talos/talosconfig.sops.yaml
      - test -f talos/secrets.sops.yaml
    cmds:
      - mkdir talos
      - talosctl gen --force secrets -o private/talos/secrets.yaml
      - |
        talosctl gen config \
          {{ .CLUSTER }} https://{{ .ENDPOINT }}:6443 \
          -t talosconfig \
          --force \
          --with-secrets private/talos/secrets.yaml \
          --config-patch @private/talos/patch.all.yaml \
          --config-patch-control-plane=@private/talos/patch.cp.yaml \
          --output-dir private/talos
      - cp -f private/talos/talosconfig talos/talosconfig.sops.yaml
      - sops -e -i talos/talosconfig.sops.yaml
      - sops -e private/talos/secrets.yaml > talos/secrets.sops.yaml
  config:
    internal: true
    desc: Generate full Talos cluster configuration
    cmds:
      - mkdir -p private/talos/nodes
      - |
        talosctl gen config -t controlplane,worker --force \
          --with-secrets private/talos/secrets.yaml \
          {{ .CLUSTER }} \
          https://{{ .ENDPOINT }}:6443 \
          --config-patch @private/talos/patch.all.yaml \
          --config-patch-control-plane=@private/talos/patch.cp.yaml \
          --output-dir private/talos
  genmachine:
    internal: true
    desc: Generate per-node machine configs and PXE boot files
    cmds:
      - makejinja -D node={{.NODE}} -d private/inventory.yaml -i templates/talos/patch.node.partial.yaml.j2 -o private/talos/nodes/patch.node.{{.NODE}}.yaml
      - makejinja -D node={{.NODE}} -d private/inventory.yaml -i templates/talos/node.ipxe.partial.j2 -o private/talos/nodes/{{.MAC}}.ipxe
      - talosctl machineconfig patch private/talos/controlplane.yaml --patch @private/talos/nodes/patch.node.{{.NODE}}.yaml --output private/talos/nodes/{{.NODE}}.yaml
  ipxe:
    internal: true
    desc: Send per-node configuration to iPXE server
    vars:
      MAC:
        sh: yq -r ".nodes.{{ .NODE }}.mac" private/inventory.yaml | sed "s/:/-/g"
    cmds:
      - rsync private/talos/nodes/{{.NODE}}.yaml private/talos/nodes/{{.MAC}}.ipxe root@{{.BOOT}}:/srv/tftp/nodes/
  local:
    desc: Setup talosctl and kubectl on local machine
    cmds:
      - talosctl --talosconfig private/talos/talosconfig config endpoint kube.{{.FQDN}}
      - talosctl --talosconfig private/talos/talosconfig config nodes kube.{{.FQDN}}
      - TALOSCONFIG=private/talos/talosconfig talosctl kubeconfig - -m=false > ~/.kube/{{.CLUSTER}}.yaml
      - KUBECONFIG=~/.kube/{{.CLUSTER}}.yaml kubectl config rename-context admin@{{.CLUSTER}} {{.CLUSTER}}
  cni:
    desc: Install Cilium with Gateway API CRDs
    cmds:
      - kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.3.0/standard-install.yaml
      - cat private/talos/cilium.values.yaml | helm upgrade --install cilium cilium/cilium -n kube-system --version=1.18.0-pre.2 -f -
  bgp:
    desc: Apply BGP configuration for Cilium
    cmds:
      - cat ./private/bgp.yaml | kubectl apply -f -
