---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
 name: bgp-peering
spec:
 nodeSelector:
   matchLabels:
     kubernetes.io/os: linux
 virtualRouters:
 - localASN: 64512
   exportPodCIDR: true
   serviceSelector:
      matchExpressions:
         - {key: somekey, operator: NotIn, values: ['never-used-value']}
   neighbors:
    - peerAddress: 172.16.2.1/32
      peerASN: 64512
    - peerAddress: 2a01:e0a:1c0:da82:1afd:74ff:fea1:ad20/64
      peerASN: 64512
