apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: gw-media
spec:
  gatewayClassName: cilium
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "{{ .Values.gw.ip }}"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.{{ .Values.wildcard_domain }}"
      tls:
        certificateRefs:
          - kind: Secret
            name: wildcard-cert
