apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
    name: acme
    namespace: default
spec:
    acme:
        email: ENC[AES256_GCM,data:dhmdTMEoDBMKBBWa8zzKWKdsgg==,iv:ISReiwh2Bmx03FbHZaWCHP62VGhZFzC1s3wdsZAzYGE=,tag:gSnHddJaNj3uOdQjXAtB3Q==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: acme-key
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:1WUCrk11KflIIvM5dzrGqktxiWSWQ3AN/Q==,iv:8n3scBNpa8n3uE1c7JcnRPnuFWhoSaMaucJ0EXiPYJ4=,tag:M467KqHRdYzKDYyIbw7Hew==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: ENC[AES256_GCM,data:04aEHhjqa7E=,iv:wQMSqp9KzaF+NnALr7h6BmvcPkad9sfZ5wLV8QJhgPw=,tag:bQzeErrda9OKZb6tAczUjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pch6mmgqfw7ll7hhfk82kg7r8gc7njl6vv9sutvu7llrapjvpqnq84ne2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eGE3QnpCc0dHRFNpakJI
            cXV6cThwT2ZSOThINzdKOVBveTJSdlVkdENBClVGYkNtVXErVE45NTBNd29wOXpj
            Mk1VaTJxd0tOcXFvN1c4RXVWR3RDQ3cKLS0tIEFKYnpwcEhWeGlSUnQyTE43Z3ZR
            VGRHVEN0eWtxNWtYMmwxU0wxa2F1OVEKZKgYhlQn6NWYrU4g+jz1dUfjykO3gm2L
            fxJHX9ANOCjNAz85TCKEPhS5ndXTD1hqbWlDZZDprnrEP/5vba9nHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T19:18:47Z"
    mac: ENC[AES256_GCM,data:rG1HDOSm2hoT/PDDEc62kYPcS1nBGnX/sJ4WmYg+DTCW+r4Y05wtdyDLccbM+VpTrVnmAoS43wnNRwPvtRYAnOi3JYPv/rh+VnVo7SWSj/mSky5Z7JL8HoSEGkQFItJPfrgcSBz5VpSWHGAqlI2bJUjmpgUBtmlXebpu9obZxBk=,iv:WPupVLYXmM0or2vr+sk1HO3G5JHn8mQGPJyg5B0zDkQ=,tag:3SOpJVK8Ab4O+9iBic5v3Q==,type:str]
    pgp: []
    encrypted_regex: ^(email|key|nameserver)$
    version: 3.7.3
