apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme-staging
    namespace: default
spec:
    acme:
        email: ENC[AES256_GCM,data:+lkiLfBsgwkWeEUlpS46NBTFKA==,iv:axoNhcPjOZbrsKvzxBi16F1iqXNk332DTO3yZsWHrd0=,tag:gYKGLtK102m2TFoi22qT/Q==,type:str]
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: acme-staging-key
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:uwYEVvmtF6fOogF5ixE4vYY5CTRw2JKm9Q==,iv:iwGWaESwZFIX8tV4x8OR98uTIJ9nP3CaY2tkkXmiWzg=,tag:CGYvOWMC+uQdZjWMRS4gGQ==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: ENC[AES256_GCM,data:zxAPHyFwuPE=,iv:IBeUPZ91U2bBwD+dsgaLbCKvybF6j2PIOC2LgiQDCd4=,tag:b3DnFX1+NgFINfKI518Scg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pch6mmgqfw7ll7hhfk82kg7r8gc7njl6vv9sutvu7llrapjvpqnq84ne2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMlN3b2g0U2pzT01QeW80
            UWRxNGNrZ1BoV3pubmRYWUhRempvQldlUHlBClhtbWVFb09ReUcxeGQ2bTJEUWVU
            eHMyV1pEdFhMZkNTbnlzaEN4eGVkdzgKLS0tIEE5SmZjZWtia0pqR1NadVM5d3dG
            WUFWUG9NcEJXOGl4REE4enY0U1JGem8KgE2tLdrR4IYkGvTRpw8wWJgA/i6XzWVq
            ckEF11asrufk6D5XyhPuiOC3dzq+UR8ThhdIg+Zm5+knUerYxJkWNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T19:18:53Z"
    mac: ENC[AES256_GCM,data:U7LWQfOMXHOD5YYpTm3ifyiS7/ZaMRBJI6bRuF8ONza0c+Nse02NeCpK0F2b1VepRUbaKNNu/+4XuNw0+slIpshbcwR2FCSVbLrsIMArGbxCM4E9PHAOp83dolskcHRzl0U+2xFmFZR/HzoUaAh0a/4SpqxC2EVsLegD36tzzLQ=,iv:S8uRYiB3wfzsAVmLtm3ldT5GAAjYVW5oK7tYaXPREo4=,tag:lpUP2oswwetVMMDuNCP1DA==,type:str]
    pgp: []
    encrypted_regex: ^(email|key|nameserver)$
    version: 3.7.3
