---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/certs/cert-manager
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-tremoureux-fr
    namespace: flux-system
