apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-cert
  namespace: default
spec:
  secretName: wildcard-cert
  dnsNames:
    - "*.home.tremoureux.fr"
  issuerRef:
    name: acme
    kind: Issuer
    group: cert-manager.io
