wildcard_domain: ENC[AES256_GCM,data:l/bYcarpo9UfYJWz5M0wAZUe,iv:RFdbzFaqptwPll1WE2eRt1ABQNPUl4uOeFe7pcWzYLk=,tag:yUjJNgcu0DBHyi0b8Fkprw==,type:str]
gw:
    ip: ENC[AES256_GCM,data:pIr0MSqo0WWzjFP5hhoXU34ovQlL,iv:feWq9xgIvkr0QUAoJgOubsvqYU3ZJO4ctLrKSYRZxD4=,tag:CZBGop0DEDQOHBw0b1sxhQ==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRGJKOWM1RXNlb0hyZVZa
            WlRreFFpOGdsT25nbThQcHFGMDdwVGZ2WEg0CklOSWlVU01oKzYxMU5TR0JSbVBF
            cTRNOGtYNk9GWVZtNjZGY1pPVGpnMHcKLS0tIGNZNkJ0UElTdlpxK3BKc3ZsYjlG
            M0RzKysxNnZRL0ZzOFFROEFPWFRCL2sK20L86WF3fg73wCDcP1w/hp5iA8+bS4WJ
            mg6831f2VVo7JpWUQ8/fW/kL6sdI/E68hZVAIyakCwu80nyUlL60dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-14T18:24:42Z"
    mac: ENC[AES256_GCM,data:9TUsutx8DepOt3ahKglStzuczJXSaRcHk9xC+ZT38rfY264Ug/Ur7YE9baKLe9qWbSACpF22BtL7J8D7/4WyWWon09F1v6yAGTrD5hTvKTw54anKYMmbCirAOJBtXQqNT53jYxMD+6lUKP2ohln0kQ6WzXoO0eoF12Z9ccAgNYU=,iv://eurxT5gg5pCwe1ijJRnF9KRMZEuaGYki4A+hvviLY=,tag:njX1NlOrVNnQcGBw9UU+xA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
