apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  template:
    metadata:
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/tsacha/byparr:839368532c0a4eaa4021e0942fcd4fe3f8d65f0a-amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 8191
