apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-exporter-conf
data:
  config.yaml: |
    mqtt:
     server: tcp://mosquitto.mqtt:1883
     topic_path: "#"
     device_id_regex: ".*/(?P<deviceid>.*)/.*"
    metrics:

     - prom_name: current
       mqtt_name: ENERGY.Current
       help: Current
       type: gauge

     - prom_name: power
       mqtt_name: ENERGY.Power
       help: Power
       type: gauge

     - prom_name: apparent_power
       mqtt_name: ENERGY.ApparentPower
       help: "Apparent Power"
       type: gauge

     - prom_name: reactive_power
       mqtt_name: ENERGY.ReactivePower
       help: "Reactive Power"
       type: gauge

     - prom_name: factor
       mqtt_name: ENERGY.Factor
       help: "Power Factor"
       type: gauge

     - prom_name: voltage
       mqtt_name: ENERGY.Voltage
       help: Voltage
       type: gauge

     - prom_name: current
       mqtt_name: ENERGY.Current
       help: Current
       type: gauge
