---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-exporter
  namespace: mqtt
  labels:
    app: mqtt-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-exporter
  template:
    metadata:
      labels:
        app: mqtt-exporter
    spec:
      containers:
      - name: mqtt-exporter
        image: ghcr.io/hikhvar/mqtt2prometheus
        ports:
        - containerPort: 9641
          name: mqtt-exporter
        volumeMounts:
          - name: config
            mountPath: "/config.yaml"
            subPath: config.yaml
            readOnly: true
      volumes:
        # You set volumes at the Pod level, then mount them into containers inside that Pod
        - name: config
          configMap:
            name: mqtt-exporter-conf
            items:
              - key: "config.yaml"
                path: "config.yaml"
