---
apiVersion: v1
kind: Service
metadata:
  name: mqtt-exporter
  labels:
    app: mqtt-exporter
spec:
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mqtt-exporter
  ports:
  - name: mqtt-exporter
    protocol: TCP
    port: 9641
    targetPort: mqtt-exporter
