apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    POCKETID_VHOST: ENC[AES256_GCM,data:QHzu0TFDhjwpYdgN3bH8ZcR7,iv:D9GFXlIcBk+f4o0gPTtRtgU9CEDfh6kvspz9nt/9XaE=,tag:49yuBy3vKEPfgdzEzIuRKw==,type:str]
    POCKETID_ENCRYPTION_KEY: ENC[AES256_GCM,data:d4m2ZQD60HztIPGI9ZwFL07W5JmwQQ886lSK7yA0EbWVGnDClF1jDi2UXpE=,iv:/CC/8b536RSR2djaY5Oa7kCV3ZpVIgG70WfrQMNOAeE=,tag:B2+z/F2R+wzXXMwVQ3e2tg==,type:str]
    VAULTWARDEN_VHOST: ENC[AES256_GCM,data:UbA7McRNCABDJrJeKaEs01/eo2U=,iv:xuwFQx11wNhb77EXEN/Nqfpzr7wgGav8HGxkWeD0PUE=,tag:l5F8N9XRh/+1ONPoAhpkUw==,type:str]
    VAULTWARDEN_SSO_CLIENT_ID: ENC[AES256_GCM,data:BaRYnvaj5UlYmmZ/It5j83h5XEsjoWEegpfbB2H7EFXHPUDb,iv:znVDTKbNZ9sW0JLZ7zrqbpVM0WY/pdpmLi21TtfNV+4=,tag:mf8uCe29c0/6uhWc5G6+Cg==,type:str]
    VAULTWARDEN_SSO_CLIENT_SECRET: ENC[AES256_GCM,data:4PkO/LlVur7/f6PNhJYG1Y5XI2g/M/MOe+Zu402AIqI=,iv:+BjRFFjL1BlrSFXsmfMiDMaxFvO9rrV1pF/hHgGgOJY=,tag:S2Xu/p5Yem4rHLRCoaezdw==,type:str]
    WG_ADDRESS: ENC[AES256_GCM,data:0O6dOlAhotbP+SrKlr/E0ObnjnNzkKJootnFmpT9ZXCslJojCdDa+wo=,iv:IfAqICYRJr9cFvfHAHO9YoysfwhCGboDBWX1BGRRry4=,tag:HxqXF8YqUFYBQ1RN6xzU9g==,type:str]
    WG_ALLOWED_IPS4: ENC[AES256_GCM,data:kR9csgOPF3DNUfq93v7sRavLaxvf4PbcJPcA1Nh6Meix3sPhQdHb37XT9/s=,iv:tw6IQhbscOqz/XqPDC6f0B7RNr+AHbtQRZckQOIHPZQ=,tag:vOtEcTJ3fpenkTIc9V0wNw==,type:str]
    WG_ALLOWED_IPS6: ENC[AES256_GCM,data:dzUWia7Sv9J/hAY6Bapi1LLEcu01B/89/Zw9ecphkmmoL/7xqB3fP/N9ANYhw7A/u5qW4kNcrP/JkSDe48XekAV+ohWK3iGHCQ==,iv:zA2itQ7g58wzm9MoVdeyeMcHA4udz0emVSLF1fgAY+8=,tag:xXN1/R9Zgtyg/lBwGthvkw==,type:str]
    WG_PRIVATEKEY: ENC[AES256_GCM,data:1HrMPciiEYxALZ1ylKkEGCCXe/ND8p/Nh7pO9f15A11vFV4hoeq3x18zaYQ=,iv:6aYVMy1nU7qDfJ7KaD1iLfcjhlLrkhlJen7bP5iDhhU=,tag:eAyF+8bgVUGA4LjsRg2CoQ==,type:str]
    WG_PUBLICKEY: ENC[AES256_GCM,data:iYEglpHSeODwb8ECGXbJNm5bE4FA7iQdkRHCao80hfHy45ohrgF3DAE+2oI=,iv:xs32KkH0W4VIcFu3ngePEucgEa62WSKXzmwusELQ/DI=,tag:eEdyLbINSXpEavee8y3elg==,type:str]
    WG_ENDPOINT: ENC[AES256_GCM,data:1/OCJRvWr537mkymDy2k+EfchZOMAUigtFJdNA==,iv:g0kx896LNPapzQ5HBdI5o8L2tJXhqOIBDtPVfU3yDNc=,tag:4YauNztOoBziFPaNKmMDYQ==,type:str]
    WG_ENDPOINT_HOST: ENC[AES256_GCM,data:80js7CUu51sRf/aVgN7HQ1+5WPV+AA==,iv:qNOn3Up7GsiWqRgPuspP24nlYzF+zqtqrG9Wa4h93Tk=,tag:O1k2cow83wpVeR3d6/BlGQ==,type:str]
    WG_HEALTHCHECK: ENC[AES256_GCM,data:vifKUGARx2j+YbN/5TS1iU7Lwmha,iv:6sG7XSp1MGhg60gdM7sMWcoF8L+MS3YLYWDsFZUW0qc=,tag:yadRhHj0ibUkOt97rHGfiA==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:6pgbdoRzQKA2U8qlSwIBISBMzISLbxO8Ye1v0wrSvg==,iv:BfPkBqQ9wAYGGUJvrQKjtjkzQETQnSAO6JQhlyodkJ8=,tag:UrpQ/rvAAl4Icr6AQ56T/w==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:jevdoKyx34i+kqgSomjtFItMdgkxACBat8Aem8SGsYI=,iv:hqW4dxNob81WvKbJmb07ali3G6kxv5rQqpP9/8a4Ijc=,tag:zm18j766KD0f1mBt3TNbDA==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:Ahe9+pdx5R5Js1yfB6If2po/KEVQtdJ5WHABQ9UbeAc=,iv:Os0U89ddshPPoMkw0sONDTRysQxm1i9xXWlEYiBOl0o=,tag:S195bCi0gcSJLT8W5uC1/w==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:W7GW+RAnH7UV70lxry8keKCf4jnxnis5,iv:39lvI1QwtSvYIjNLKJClhpXWTRCb7h9Mr/IljXo88QU=,tag:X2nY8rrE4WnW6uLwNIWY6g==,type:str]
    RESTIC_BUCKET_APPS: ENC[AES256_GCM,data:Oj3Kzv+04k34nQtkHrU=,iv:iJDvpsGjJdjlq6gWVglAfukBppS0PweNyBMxgiKTLAw=,tag:bBvye5/iVNb9jYUHz+AnBA==,type:str]
    DNS_HTTP2136_VHOST: ENC[AES256_GCM,data:+2038tzFvuskgFq5FZ2H02iEFIH7fw==,iv:KWl6XBqovVrL1SbXFVLtEiciPUH5AwDXYvjGLXU1AJc=,tag:Ww/GJSuEzgcovz27+WuDdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Z0M1QWV3OC9QUnJIclVz
            NXJ1SEtoRkpiVHFUczFIWElLNmxqSW1wd2p3ClNUOHptTFRTK1AzblZvZGdtS0l0
            aVluLzAveUl0d2pOc0dwRkZNNnBNTkkKLS0tIEM5L3IvZjJhSXZyRThkRnE0R3lZ
            czViSk9Tc2p2UlJYWHUzQmJVSXR1dW8KqP6fwVMo1EpjF48J6evw8UcC0vfpxqOJ
            OkedeRqwzl3+4DJoDVycwj0XkZKoDQu6vfVudB7eXL7nljxws+DQEQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-17T23:02:31Z"
    mac: ENC[AES256_GCM,data:GG555FgMlnkzIbbV8Ib5590JI/jBrYSKp90adw0pmlj8LLtD0qcKNzJE32K6heB81xpBbPNREVA/7e7Jd6JgmZsv5DRb2qQ0hpEkVgpdh8I7HH9UToESR9WEDmcT5rUMjJLIX2AGY3RrU67LlT2BG39kEZrz3MjNOU3rJyel5wg=,iv:nwp7rv8suAKwqbvKu/+FwADh4B9VeRl2j11jPLZcP6o=,tag:F9VuhMz+TwdtSS7kfLVDBw==,type:str]
    version: 3.13.3
