apiVersion: v1
data:
    SERVER_PASS: ENC[AES256_GCM,data:25s7muMx0DQ5O3Ap,iv:eH94P4OMPrxMMrobDJkUdB0FpB+azalBbLdnbFcUIEg=,tag:B4kdy4eq/UANleR3wUhh1Q==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: valheim-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7ehhg7p0xsxnsdggen9plw5p20rxs89pdy3fmwafr84dh4qdylstwad7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxK2tKZmlVWWtubXE2LzIv
            RWpvZ2RnVDhRV0RIanN0NzZmemdMZi9CRW5jCkY3aFlkYU1mRnVpcXdQcVg0dERL
            YjV4dlZOaTlwclJQVGRwbXExN0ZLaDQKLS0tIE5oS0RRNDhLVTJNQUJPenl6S2FJ
            TThRZUE1NjRiWjdwL041bTJVQ1hmZWMKbNaI0Fe+RFz6mq+twlcofG4OZvQnHA2R
            fdfZsjRHB2T61FGwjoQBjZ8GoYV7AkGsRQA3Ud3jX+HFO07Mvfklyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-23T18:20:54Z"
    mac: ENC[AES256_GCM,data:kSCoUQ85c464clOD/MPeQEjKT5iFgpKXJQOYeBwfaFc6BwdU6CZ2aG4gMdXImMKb1Tb2WKAp/1ItavlOJ1Sez+e47DzdXdKd2BZ3kVIzadX9mGyZBM0ZUSeQPGrC6voDN7cmnCowKC+YdvrVmJAh14dUr1sJ5xHf7hDA/11WXwc=,iv:FjHwoa+WIyPrORxttiJ0a2oWYLyyaNd71UIJIYCobYQ=,tag:qgaHfwmbGBerODJxQj2Nsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
