---
apiVersion: v1
kind: Service
metadata:
  annotations:
    "io.cilium/lb-ipam-ips": "172.16.238.9,2a01:e0a:1c0:da86:2::9"
  name: valheim
spec:
  allocateLoadBalancerNodePorts: false
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: valheim-1
    port: 2456
    protocol: UDP
    targetPort: valheim-1
  - name: valheim-2
    port: 2457
    protocol: UDP
    targetPort: valheim-2
  selector:
    app: valheim
  type: LoadBalancer
