---
- name: Install boot packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - curl
      - docker.io
      - docker-compose
      - emacs-nox
      - git
    update_cache: yes

- name: Install yq
  ansible.builtin.get_url:
    url: https://github.com/mikefarah/yq/releases/download/v4.30.6/yq_linux_amd64
    dest: /usr/local/bin/yq
    mode: 0755

- name: Configure Emacs backups directory
  ansible.builtin.copy:
    content: "(setq backup-directory-alist '((\".\" . \"~/.emacs.d/backups\")))"
    dest: /usr/share/emacs/site-lisp/backup.el

- name: Create root Emacs backups directory
  ansible.builtin.file:
    path: /root/.emacs.d/backups
    state: directory

- meta: flush_handlers

- name: Boot directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/boot
    - /opt/boot/kea
    - /opt/boot/assets
    - /opt/boot/assets/nodes

- name: Download boot assets
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "/opt/boot/assets/{{ item.dest }}"
  loop:
    -
      url: http://boot.ipxe.org/snponly.efi
      dest: snponly.efi
    -
      url: http://boot.ipxe.org/arm64-efi/snponly.efi
      dest: snponly-arm64.efi
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.6.5/vmlinuz-amd64
      dest: vmlinuz
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.6.5/initramfs-amd64.xz
      dest: initramfs.xz
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.6.5/vmlinuz-arm64
      dest: vmlinuz-arm64
    -
      url: https://github.com/siderolabs/talos/releases/download/v1.6.5/initramfs-arm64.xz
      dest: initramfs-arm64.xz

- name: Boot docker-compose
  ansible.builtin.template:
    src: docker-compose.yaml.j2
    dest: /opt/boot/docker-compose.yaml

- name: Caddy boot proxy
  ansible.builtin.template:
    src: Caddyfile.boot.j2
    dest: /opt/boot/Caddyfile.boot

- name: Boot iPXE menu
  ansible.builtin.template:
    src: menu.ipxe.j2
    dest: /opt/boot/assets/menu.ipxe

- name: Talos iPXE
  ansible.builtin.template:
    src: talos.ipxe.j2
    dest: "/opt/boot/assets/nodes/{{ item.value.mac|replace(':', '-') }}.ipxe"
  loop: "{{ nodes|dict2items }}"

- name: Kea DHCPv6 configuration file
  ansible.builtin.template:
    src: dhcp6.json.j2
    dest: /opt/boot/kea/dhcp6.json

- name: Systemd unit
  ansible.builtin.template:
    src: unit.j2
    dest: /etc/systemd/system/boot.service

# Bitwarden
- name: Gateway directory
  ansible.builtin.file:
    path: /opt/bitwarden
    state: directory

- name: Certbot OVH credentials
  ansible.builtin.template:
    src: certbot-ovh-credentials.ini.j2
    dest: /opt/bitwarden/certbot-ovh-credentials.ini
    mode: 0400

- name: Bitwarden certificate renew service
  ansible.builtin.template:
    src: renew.service
    dest: /etc/systemd/system/renew.service

- name: Bitwarden certificate renew timer
  ansible.builtin.template:
    src: renew.timer
    dest: /etc/systemd/system/renew.timer

- name: Check if certificate exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ bitwarden_vhost }}/fullchain.pem
  register: result

- name: Generate bitwarden certificate
  ansible.builtin.docker_container:
    name: certbot
    image: certbot/dns-ovh
    state: started
    recreate: yes
    detach: no
    cleanup: yes
    volumes:
      - /opt/bitwarden:/opt/bitwarden
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    command: "certonly --dns-ovh --dns-ovh-credentials /opt/bitwarden/certbot-ovh-credentials.ini -d {{ bitwarden_vhost }} -m {{ mail }} --non-interactive --agree-to"
  when: not result.stat.exists

- name: Bitwarden backup service
  ansible.builtin.template:
    src: backup.service.j2
    dest: /etc/systemd/system/backup.service

- name: Bitwarden backup timer
  ansible.builtin.template:
    src: backup.timer
    dest: /etc/systemd/system/backup.timer

- name: Start Renew timer
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: renew.timer

- name: Start Backup timer
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: backup.timer

# Start Gateway
- name: Start boot services
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: boot
