---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: lldap-cert
spec:
  secretName: lldap-cert
  additionalOutputFormats:
    - type: CombinedPEM
  dnsNames:
    - lldap.home.tremoureux.fr
    - ldap.home.tremoureux.fr
  issuerRef:
    name: acme
    kind: Issuer
    group: cert-manager.io
