# kubectl create -n auth secret generic lldap-secrets --dry-run=client -o yaml \
#               --from-literal=lldap-jwt-secret=(pwgen -s 40 -1 -y -B) \
#               --from-literal=lldap-bind-dn=cn=admin,ou=people,dc=domain,dc=tld \
#               --from-literal=lldap-bind-password=(pwgen -s 40 -1 -y -B) \
#               --from-literal=lldap-base-dn=dc=domain,dc=tld > secrets.yaml
# sops --encrypt --encrypted-regex '^(data|stringData)$' secrets.yaml > secrets.sops.yaml
# rm secrets.yaml
---
apiVersion: v1
data:
    lldap-base-dn: ENC[AES256_GCM,data:mYxHAy9L73KJB5/oOXZN9ZxiuZr9GHEeYxlg+w==,iv:PQCSQ9YuZUrUhN0YcuXKQjNR66nSTcHVfKVd8O2+Yrw=,tag:kFLer0vXo3sADknVbY2kYQ==,type:str]
    lldap-bind-dn: ENC[AES256_GCM,data:x6ZzOdMHMKvF+j+Id6a1xeO/D+7gaIthegtJ1oeMtTd3fmdgxAVMg+tVFgrwbqgywwZLfQ==,iv:BrBZ4Ywlup/LbSi1sjoYeEA6p6tXK0POP6R9ax1k8Nk=,tag:PMfknIkGokYgCg3+EUjE2A==,type:str]
    lldap-bind-password: ENC[AES256_GCM,data:U+ejTM8RolkMX9v9WrgoM0OQ2Dm5IqmU1A7GrRAW9McuPi33RE6fntnIsSurTOsN+i6vJn2SuiY=,iv:zDS5LW7QlCXzbvWcU4MPZBDsF0J4/10YIvaMLGdcR/Y=,tag:iWcM+bfz0HazKUkrHLJZ/g==,type:str]
    lldap-jwt-secret: ENC[AES256_GCM,data:6mcx67KWY0f9a5iTkmFpVXcj9iNYtOuzblv37kzBQjXmq3G/EUKPKSNQA6g400U9bHWOfYtoGBY=,iv:Zqg5M8BVRQL+0fLRlcFm/xJ6dTJ2w17qGbb0kcanLNQ=,tag:gvttT8nYRvh2mbexLwF12A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: lldap-secrets
    namespace: auth
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pch6mmgqfw7ll7hhfk82kg7r8gc7njl6vv9sutvu7llrapjvpqnq84ne2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMS1prOW5kWStwb2pHSzlH
            U1k1TVB5M0hQK0Jqd2lzU3FUdGlEcjQ4RmxVClprcnE3aHBmeEZPNU1GQllJaisx
            ZXBLL08zLzFZTXhyaFlQUkRqOFl3bDAKLS0tIDhnbjRBc2dLNmRuZFhpaS9JZmIw
            bnM5QkZndXQ5MHJaakZ3RG1DWW82VEkKfy4iTbcM6JW9aiQ2sGtPrXLEYbhuMwIc
            EXOhKkEfKMr0sqsJTYWWOGz39GrTdYokrGFJi/ED0YSZ4uO1LHuZUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T18:53:44Z"
    mac: ENC[AES256_GCM,data:LvKclV5YBw1Bg9SrdbSyRuXHrp6AtLuGq54n59jyX+BoFEh+9fLAZ0vhnozKBbXOMzqgKjq5WygmWlKYeBVPubQ0YB2kVwI+Sufqq08Q+3kic5j2u6ZpzuyARPbJdzBMIPh065RLX/VMr0AD3LW7WeHKSdSBiQ5PU9AwRrt/E8E=,iv:dKtB6Jgutta/HMCHhrmOxli9bbJNOuHW/0fLlw7JhvM=,tag:D4xFYLz8mWh5mPLrg+EgiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
