cluster-init: ENC[AES256_GCM,data:EIFv6w==,iv:PHzGHOPRqmMmNj3zBzooiHIggyWBgharTkTLg1vZ21U=,tag:Jbz7ZLOTCOLHNdGPXEuUgw==,type:bool]
flannel-backend: ENC[AES256_GCM,data:vBRLEw==,iv:39x8OT76CqbsReXIjV0Kffxyy58B1W2lTqKIuNyUuww=,tag:TOZeZK3Sk390Fle+oZZvYg==,type:str]
disable-kube-proxy: ENC[AES256_GCM,data:43oOWw==,iv:ZLAH/o8y6lpKUG/zH0RzoXOZRZnpz4/iNa+C6k4dPqg=,tag:2TX4nOIMyA+woglPseerRw==,type:bool]
disable-network-policy: ENC[AES256_GCM,data:6pb9Fg==,iv:3XwkRuh6UUSOzKajOb6QWhFCI8pROLvpXnPzR2yv0Nk=,tag:0o+JKFTwBvZS9DdzUIceqQ==,type:bool]
disable:
    - ENC[AES256_GCM,data:KiTuEDDk9A==,iv:ExV45j6IasvCCdUsOd9cmJ1uxWhhRS7xRTMcaiijyqk=,tag:gncBYHibS/PhOAv4jA6kAA==,type:str]
    - ENC[AES256_GCM,data:gM4JUjoU7WMB,iv:MbBA/+4JdGmTR9TXgTeSjJRhT2cYdajk9w3wpB2Lz3w=,tag:b4ffRdS3hicvEmM2lm3VZw==,type:str]
    - ENC[AES256_GCM,data:HARUBWmsnfCLIT86gqQ=,iv:8cJEcFPmMcEJwpuUaFgNw8DjimuixgcS+dHStSOBOu0=,tag:H73dwA1Kr8w9Y339ARQRvw==,type:str]
tls-san:
    - ENC[AES256_GCM,data:IrKgdqkLVUNKfdHbedo+e6U2oDkqGA==,iv:rpH5fdGZ23SarfU9Ov3eHumX62LDtMCRIyS0nVmEmnw=,tag:LsFGhPoCxhi/tYWQ/Jfy8g==,type:str]
    - ENC[AES256_GCM,data:G+MRt8MM83FcAuL0mBuyTtkvbenvSoA=,iv:Z+f+uqG0BE/bag/2a2PAxzGlpi8T1O8II6/MRahTn/U=,tag:5mjfsckglP0/hBSibPbY9A==,type:str]
cluster-cidr:
    - ENC[AES256_GCM,data:+DcZgvAmX8gjVdv0KA==,iv:RKu/4QunHOxQXzP/VJPuwoqEe85110gBK3e3Lr5BT78=,tag:pJ4lAZAs3Y0AuUW369oh5w==,type:str]
    - ENC[AES256_GCM,data:GTisXS0vwg84I2n8Iun+IWMy0JdOke4=,iv:fXxNpN4hgBMSzKg3zjH62womoScNzrATe9CiMW7atUg=,tag:I7p8JUFZKAO5Dv9Y7XbhAg==,type:str]
service-cidr:
    - ENC[AES256_GCM,data:hI/iFTv0B70gkNwsYA==,iv:zSYLTcccTMdOrNRHsFS3Q7EbyQOH1aWkVWen0bASqFo=,tag:hpQF56zKK9jHGhgNMZgGeQ==,type:str]
    - ENC[AES256_GCM,data:vIQ0lC90ZR3qHQsimzJD5qrHQfMjIaON,iv:yASPxYSd3JUwlxJTXbhepgE/X/B8kZ994QpqxB6nOZQ=,tag:zfzMa6oPKuXpNqPkIh1qWA==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRHRnWE1ob2Ywa3FUbk84
            QXU4M2tTYURoeHdaSE5HdnFCeGlCbDlzd2h3CkV0bkQ5YWpObVh3MTkvRGRaeEJs
            cHN3MWdlTHl4cUExUHpVZHJIaTVwVnMKLS0tIGVlYjVGUzR5SmVRdFFvUXIvbFdW
            eFpRVk5aenBneTRBRGVuN3d5QVNWT28KyujOMzcRcUBL2980Im5e1rcroaXIqJte
            RO9tMmy7i2UeOzeh6zEnNCz196zuonZSKGuDP4G0pUEPDncVD4NkQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-26T12:25:13Z"
    mac: ENC[AES256_GCM,data:3Ahehx7OBPpq7kSoEXUfwQJ2/K2AlzF88zjQ29/nJFGtpdfq3d8rngnydMnQCtOzJeRS+CsdpdulfzjcV3MBY4xycnkj7Y2mpOUGMfQ3KTOQVMGjTYijMH3wFs37VILoFF/41HnCcwYctW/QW8eTT6elgMgKVn8AvsC14UMF6ag=,iv:EVshZk/xACkFT7JAg5E1EHuOmc0zsKEhCHYuFA/vQI8=,tag:4KuU+cbVYoJfPIqF1m9cBg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
