apiVersion: v1
kind: Secret
metadata:
  name: restic-config-pocketid
  namespace: apps
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:{{ .Values.backup.endpoint }}/{{ .Values.backup.bucket }}/pocketid
  RESTIC_PASSWORD: "{{ .Values.backup.restic }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.backup.ak }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.backup.sk }}"
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-config-vaultwarden
  namespace: apps
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:{{ .Values.backup.endpoint }}/{{ .Values.backup.bucket }}/vaultwarden
  RESTIC_PASSWORD: "{{ .Values.backup.restic }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.backup.ak }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.backup.sk }}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: pocketid
  namespace: apps
spec:
  sourcePVC: pocketid
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-pocketid
    copyMethod: Direct
    pruneIntervalDays: 14
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden
  namespace: apps
spec:
  sourcePVC: vaultwarden
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-vaultwarden
    copyMethod: Direct
    pruneIntervalDays: 14
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
