---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto
  annotations:
    "io.cilium/lb-ipam-ips": "172.16.238.2,2a01:e0a:1c0:da86:2::2"
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  selector:
    app: mosquitto
  ports:
  - name: mosquitto-mqtt
    protocol: TCP
    port: 1883
    targetPort: mosquitto-mqtt
