apiVersion: v1
kind: Secret
metadata:
  name: restic-config-papra-docs
  namespace: apps
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:{{ .Values.backup.endpoint }}/{{ .Values.backup.bucket }}/papra-docs
  RESTIC_PASSWORD: "{{ .Values.backup.restic }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.backup.ak }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.backup.sk }}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: papra-docs
  namespace: apps
spec:
  sourcePVC: papra-docs
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-papra-docs
    copyMethod: Direct
    pruneIntervalDays: 14
    retain:
      hourly: 5
