apiVersion: v1
kind: Secret
metadata:
  name: restic-config-unifi-os-pvc
  namespace: unifi
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:{{ .Values.backup.endpoint }}/{{ .Values.backup.bucket }}/unifi-os-pvc
  RESTIC_PASSWORD: "{{ .Values.backup.restic }}"
  AWS_ACCESS_KEY_ID: "{{ .Values.backup.ak }}"
  AWS_SECRET_ACCESS_KEY: "{{ .Values.backup.sk }}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: unifi-os-pvc
  namespace: unifi
spec:
  sourcePVC: unifi-os-pvc
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-unifi-os-pvc
    copyMethod: Direct
    pruneIntervalDays: 14
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
