apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-db-init-script
  namespace: unifi
data:
  init-mongodb.js: |
    var admin = db.getSiblingDB('admin');
    admin.auth(process.env.MONGODB_INITDB_ROOT_USERNAME, process.env.MONGODB_INITDB_ROOT_PASSWORD);
    admin.createUser({
      user: process.env.MONGODB_USER,
      pwd: process.env.MONGODB_PASSWORD,
      roles: [
        { role: 'dbOwner', db: 'unifi' },
        { role: 'dbOwner', db: 'unifi_stat' },
        { role: 'dbOwner', db: 'unifi_audit' }
      ],
    });
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-db-pvc
  namespace: unifi
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: unifi-db
  namespace: unifi
spec:
  selector:
    app: unifi-db
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unifi-db
  namespace: unifi
  labels:
    app: unifi-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unifi-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unifi-db
    spec:
      containers:
        - name: unifi-db
          image: docker.io/mongodb/mongodb-community-server:8.0.10-ubi8
          args:
            - --ipv6
          ports:
            - containerPort: 27017
          env:
            - name: MONGODB_INITDB_ROOT_USERNAME
              value: root
            - name: MONGODB_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unifi-secrets
                  key: mongodb-root-password
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: unifi-secrets
                  key: mongodb-user
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: unifi-secrets
                  key: mongodb-password
          volumeMounts:
            - name: data
              mountPath: /data/db
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init-mongodb.js
              subPath: init-mongodb.js
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: unifi-db-pvc
        - name: init-script
          configMap:
            name: unifi-db-init-script
