apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-os-pvc
  namespace: unifi
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
