apiVersion: v1
kind: Secret
metadata:
    name: unifi-secrets
    namespace: unifi
type: Opaque
stringData:
    mongodb-root-password: {{ .Values.mongodb.root_password }}
    mongodb-user: {{ .Values.mongodb.user }}
    mongodb-password: {{ .Values.mongodb.password }}
