apiVersion: v1
kind: Service
metadata:
  name: unifi-app
  namespace: unifi
  annotations:
    lbipam.cilium.io/ips: "{{ .Values.lb.ip }}"
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack # No IPv6 on Unifi APs…
  selector:
    app: unifi-os-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      name: webui
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: inform
    - protocol: UDP
      port: 3478
      targetPort: 3478
      name: stun
    - protocol: UDP
      port: 10003
      targetPort: 10003
      name: discovery
    - protocol: TCP
      port: 6789
      targetPort: 6789
      name: speedtest
