---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: network-cilium
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 3m0s
  retryInterval: 1m0s
  path: ./k8s/apps/network/cilium
  prune: true
  dependsOn:
    - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
