---
- name: Backups unit
  ansible.builtin.template:
    src: backups.service
    dest: /etc/systemd/system/money.backups.service

- name: Backups timer
  ansible.builtin.template:
    src: backups.timer
    dest: /etc/systemd/system/money.backups.timer

- name: Create money folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - /opt/money

- name: Generate Actual container
  containers.podman.podman_container:
    name: actual-server
    image: ghcr.io/actualbudget/actual-server
    state: quadlet
    env:
      ACTUAL_LOGIN_METHOD: header
      ACTUAL_TRUSTED_PROXIES: '10.89.0.0/24,fd84:3f4c:8fc8::/48'
    volume:
      - "/opt/money:/data"
    quadlet_options:
      - AutoUpdate=registry
      - "Pull=newer"
      - |
        [Install]
        WantedBy=default.target

- name: Start Actual
  ansible.builtin.systemd_service:
    name: actual-server.service
    state: started
    daemon_reload: yes

- name: Start money backup timer
  ansible.builtin.systemd:
    state: started
    enabled: true
    name: money.backups.timer
