---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: 1.14.0-snapshot.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 5
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    autoDirectNodeRoutes: true
    ipv4NativeRoutingCIDR: 172.16.240.0/20
    ipv6NativeRoutingCIDR: 2a01:e0a:1c0:da87::/64
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    enableIPv4Masquerade: false
    enableIPv6Masquerade: false
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDR: 172.16.240.0/20
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDR: 2a01:e0a:1c0:da87::/64
        clusterPoolIPv6MaskSize: 80
    tunnel: disabled
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
    hubble:
      enabled: true
      port: 9965
      preferIpv6: true
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
          - httpV2
          - port-distribution
        serviceMonitor:
          enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
    kubeProxyReplacement: strict
    bandwidthManager:
      enabled: true
    bgpControlPlane:
      enabled: true
    bpf:
      masquerade: true
    securityContext:
      privileged: true

    cgroup:
      hostRoot: /sys/fs/cgroup
      autoMount:
        enabled: false

    k8sServiceHost: kube.home.tremoureux.fr
    k8sServicePort: 6443
