groupName: acme-ovh
issuers:
    - name: le-prod
      create: true
      kind: ClusterIssuer
      namespace: cert-manager
      acmeServerUrl: https://acme-v02.api.letsencrypt.org/directory
      email: ENC[AES256_GCM,data:OMK/N8NnyZjvdG0uLzItThPMPA==,iv:fDDsIeaeAGPyO22AKqfgRu91mr5xsFeL/J49Jkq4L2M=,tag:XRG0U1arNK/74N1ccBGNXA==,type:str]
      ovhEndpointName: ENC[AES256_GCM,data:STCstDAs,iv:5pKQInMGDu0NtJMZInefNQ6lLN7x5OkGTon0UjxHZV8=,tag:DaXR96XnoyTAw6RDXWHLeA==,type:str]
      ovhAuthenticationMethod: ENC[AES256_GCM,data:D2irpuE3DZyt1eU=,iv:ZxoMo3GJfp2+5a+wzrYTjsa0acAXqrms6RkGaWC91rs=,tag:ZwO0axLdj1XSG59vW8ucmA==,type:str]
      ovhAuthentication:
        applicationKey: ENC[AES256_GCM,data:w0eNd5c9yLVYc2KXJOGPWg==,iv:fpAppjncmQ+Ri4NT8bHvEJQT/1LqW/qYdND5JbtSrqg=,tag:Lq0VAFTUCZeg8Qc4SWV7ew==,type:str]
        applicationSecret: ENC[AES256_GCM,data:LcoWXLRWmQ4j76F4l8lwCV4KibZN64dPuInnMiQnS10=,iv:EGcLZ/KZiPT4PDro3EYkThMeGWQLCIdW1AdHViKjlMY=,tag:C1wggv0aXTsix4c6woCt1Q==,type:str]
        applicationConsumerKey: ENC[AES256_GCM,data:sWwPXGL6cHYJUkFZ31uox5CwL8R5mCwsBefOroExCNc=,iv:jSMl2JQHBvcIWE/ybosfc5iF0CSW1GD0NzD+m7Ey524=,tag:Pdg15dg2et6idVpopsTwpQ==,type:str]
    - name: le-staging
      create: true
      kind: ClusterIssuer
      namespace: cert-manager
      acmeServerUrl: https://acme-staging-v02.api.letsencrypt.org/directory
      email: ENC[AES256_GCM,data:OMK/N8NnyZjvdG0uLzItThPMPA==,iv:fDDsIeaeAGPyO22AKqfgRu91mr5xsFeL/J49Jkq4L2M=,tag:XRG0U1arNK/74N1ccBGNXA==,type:str]
      ovhEndpointName: ENC[AES256_GCM,data:STCstDAs,iv:5pKQInMGDu0NtJMZInefNQ6lLN7x5OkGTon0UjxHZV8=,tag:DaXR96XnoyTAw6RDXWHLeA==,type:str]
      ovhAuthenticationMethod: ENC[AES256_GCM,data:D2irpuE3DZyt1eU=,iv:ZxoMo3GJfp2+5a+wzrYTjsa0acAXqrms6RkGaWC91rs=,tag:ZwO0axLdj1XSG59vW8ucmA==,type:str]
      ovhAuthentication:
        applicationKey: ENC[AES256_GCM,data:w0eNd5c9yLVYc2KXJOGPWg==,iv:fpAppjncmQ+Ri4NT8bHvEJQT/1LqW/qYdND5JbtSrqg=,tag:Lq0VAFTUCZeg8Qc4SWV7ew==,type:str]
        applicationSecret: ENC[AES256_GCM,data:LcoWXLRWmQ4j76F4l8lwCV4KibZN64dPuInnMiQnS10=,iv:EGcLZ/KZiPT4PDro3EYkThMeGWQLCIdW1AdHViKjlMY=,tag:C1wggv0aXTsix4c6woCt1Q==,type:str]
        applicationConsumerKey: ENC[AES256_GCM,data:sWwPXGL6cHYJUkFZ31uox5CwL8R5mCwsBefOroExCNc=,iv:jSMl2JQHBvcIWE/ybosfc5iF0CSW1GD0NzD+m7Ey524=,tag:Pdg15dg2et6idVpopsTwpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcjZibUN1WW9xVGkzdGNM
            ZHh4UFlwcE1IK3UzS2hOS2o1NklBSEVkczF3CnprQlVkYUxGL0k3Y0YwMmNZTVZL
            d1hvTUNqTEpJdzFyQ2lRcUFKQTMxWncKLS0tIEhpRDVTaVVXcEJFbFovOFNuOXEy
            VGE4ckdjTVRBWUlIRzZpTi9kbTAxSW8K/GasxsVbIWPOPGbSxj9aXpXQkorVl2SV
            3C71685l3cXyXbAKR8c4wc7NE52O0rl+kJnaqSDJ5VnnHsV1Hn72pg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(ovh.+|email)$
    lastmodified: "2026-03-28T12:41:16Z"
    mac: ENC[AES256_GCM,data:LzKAGz9KBkRjqOQFQ2SWRJYItEP0nrcTECtYfy56dHEj3M4434DUWEgBeY0NIVeYxKY9eHLK1vGz5mDW3InyABME6n4IBYqLuYZQSriV3p7QY1E+gBYzJWOAhvrDNCrem04SdJq7Sac0BxcNYmCfPfaxC4xIJWCgpQfXdsV72WE=,iv:hx8C3zBQCnJxHEBtJuIg2RaCyjMaSBQ0N2v4sw4RkKs=,tag:Btm5NwPmtHqP3QYA6E7xGA==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdAoEC93fklPtWkbOzaeZelGAWUVzCcIED0Q2Zb72HI9hkw
            7oye6DBXJAAm/KlbjGWDbqeuFBSJpItu8G2w2HqVYiNPkb/rGzUQJ1QRjsT9e3V0
            0l4Bc+79N1XlicD9S3Xomi1Svj2h/Em1KOnyYLSaPiOF5vihja+1uZ1yHR2SIk4S
            VebE53tBgbgTonYScQKubvnB+pcs1iHXf1U9tfIsfvrfBFEM2dWjCze69a/SVYT/
            =s7qc
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    version: 3.12.2
