apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: le-home-staging
spec:
    acme:
        email: ENC[AES256_GCM,data:Jm2WfOsdhev38eY/liQMNCZfKw==,iv:QARDYskf95fJ4T1oV7A97C7tnvCR2FALsiHAgWemFM4=,tag:YsYbbhSV4S8c5RzB4Xyfnw==,type:str]
        privateKeySecretRef:
            name: le-home-staging-account-key
        server: https://acme-staging-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:hzjo6kpj1ijDSJw/JdtK6Q==,iv:w4qZrLM0lJfaO+YSkpnzxxKSHdFk5S6f+ibWXmRFvNs=,tag:mqowqd13OJQsilVmVf7qdg==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: rndc.key
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZW1RTHB1VXM1UEhZL09i
            cnRJZXdNaVJCc2o1aWZ6YXhseDhOOGN1aXdZCm1jM3UxMzBwRVNLLzF2MlN5c2t0
            dTJJL3Z2Zk9vOFRtZ3RoblJaVW93QTQKLS0tIENyZXNnaEtWQ1NjK1Z3VXpjdEFC
            QzV2SGpDeVNWOHFUZzVOL2VWUjJIbGsKK6brUNKsD6QJ5NA5TVhNneGTkRkirjPB
            RaxFfKx4FUGUTp9+yHfJL3nhkpRO0oaGOEXex2Kue9K4gkz9R61n0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(rndc\.key|nameserver|email)$
    lastmodified: "2025-06-11T21:01:22Z"
    mac: ENC[AES256_GCM,data:J6ca22Q9qrimTuuAhP5t4wxQydRUyQ+dohz0jeG9rLWq4dCPgAqRHdHzlAZQFrx9xvOcZdcBipugzCmjJAyIRWk9KXXktKCS3EbjVffEy+SgIYqj4JWGBjPb6eE2zxNQTEqEQJfyNJlUDE3z/pCb9SGbKhqq7f8yj04DLP1t4xk=,iv:sRmoLcNskAtUC6Zu1x/onAGMzW7mwxI0VYgl2c5vhAI=,tag:kEyhFBHTnzIn9LcRjaMp4A==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdA7AkvCE7qpRAtF58aFp4hXMDmtCQU2HLjCShh0cEyjX4w
            MqJzhBWsIfSh5JFTGaLoCCGrrm3af1LPJfLcdYfGRCBTjWllhyA+orMvsUfbXuPt
            0lwBWv7Nal4mXIWmwEhVAHt3B1G0RYXs1caCWad5f9IcMxVJ45zbbGqHvvdqjei2
            kE8nHgK1149WLEMK68AEuBwwEsX+6xsQXLvyT2xiARZm38EAU3apFwKt1uZKhw==
            =slRt
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    version: 3.10.2
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: le-home-prod
spec:
    acme:
        email: ENC[AES256_GCM,data:Jm2WfOsdhev38eY/liQMNCZfKw==,iv:QARDYskf95fJ4T1oV7A97C7tnvCR2FALsiHAgWemFM4=,tag:YsYbbhSV4S8c5RzB4Xyfnw==,type:str]
        privateKeySecretRef:
            name: le-home-prod-account-key
        server: https://acme-v02.api.letsencrypt.org/directory
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:hzjo6kpj1ijDSJw/JdtK6Q==,iv:w4qZrLM0lJfaO+YSkpnzxxKSHdFk5S6f+ibWXmRFvNs=,tag:mqowqd13OJQsilVmVf7qdg==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: rndc.key
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZW1RTHB1VXM1UEhZL09i
            cnRJZXdNaVJCc2o1aWZ6YXhseDhOOGN1aXdZCm1jM3UxMzBwRVNLLzF2MlN5c2t0
            dTJJL3Z2Zk9vOFRtZ3RoblJaVW93QTQKLS0tIENyZXNnaEtWQ1NjK1Z3VXpjdEFC
            QzV2SGpDeVNWOHFUZzVOL2VWUjJIbGsKK6brUNKsD6QJ5NA5TVhNneGTkRkirjPB
            RaxFfKx4FUGUTp9+yHfJL3nhkpRO0oaGOEXex2Kue9K4gkz9R61n0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(rndc\.key|nameserver|email)$
    lastmodified: "2025-06-11T21:01:22Z"
    mac: ENC[AES256_GCM,data:J6ca22Q9qrimTuuAhP5t4wxQydRUyQ+dohz0jeG9rLWq4dCPgAqRHdHzlAZQFrx9xvOcZdcBipugzCmjJAyIRWk9KXXktKCS3EbjVffEy+SgIYqj4JWGBjPb6eE2zxNQTEqEQJfyNJlUDE3z/pCb9SGbKhqq7f8yj04DLP1t4xk=,iv:sRmoLcNskAtUC6Zu1x/onAGMzW7mwxI0VYgl2c5vhAI=,tag:kEyhFBHTnzIn9LcRjaMp4A==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdA7AkvCE7qpRAtF58aFp4hXMDmtCQU2HLjCShh0cEyjX4w
            MqJzhBWsIfSh5JFTGaLoCCGrrm3af1LPJfLcdYfGRCBTjWllhyA+orMvsUfbXuPt
            0lwBWv7Nal4mXIWmwEhVAHt3B1G0RYXs1caCWad5f9IcMxVJ45zbbGqHvvdqjei2
            kE8nHgK1149WLEMK68AEuBwwEsX+6xsQXLvyT2xiARZm38EAU3apFwKt1uZKhw==
            =slRt
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: rndc-key
    namespace: cert-manager
type: Opaque
stringData:
    rndc.key: ENC[AES256_GCM,data:nn3qhI86wCLEIqIYNKaw9A+miU0tBq+yZi32sTqrR3v4wpW6yrDLCN5T5Yk=,iv:ZUhmcUeTcH1JLk9MyJC9xoll6jEoaUNUv7nFP9meE1M=,tag:NUd0noN+mNLyrVn4ZQxGkA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZW1RTHB1VXM1UEhZL09i
            cnRJZXdNaVJCc2o1aWZ6YXhseDhOOGN1aXdZCm1jM3UxMzBwRVNLLzF2MlN5c2t0
            dTJJL3Z2Zk9vOFRtZ3RoblJaVW93QTQKLS0tIENyZXNnaEtWQ1NjK1Z3VXpjdEFC
            QzV2SGpDeVNWOHFUZzVOL2VWUjJIbGsKK6brUNKsD6QJ5NA5TVhNneGTkRkirjPB
            RaxFfKx4FUGUTp9+yHfJL3nhkpRO0oaGOEXex2Kue9K4gkz9R61n0w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(rndc\.key|nameserver|email)$
    lastmodified: "2025-06-11T21:01:22Z"
    mac: ENC[AES256_GCM,data:J6ca22Q9qrimTuuAhP5t4wxQydRUyQ+dohz0jeG9rLWq4dCPgAqRHdHzlAZQFrx9xvOcZdcBipugzCmjJAyIRWk9KXXktKCS3EbjVffEy+SgIYqj4JWGBjPb6eE2zxNQTEqEQJfyNJlUDE3z/pCb9SGbKhqq7f8yj04DLP1t4xk=,iv:sRmoLcNskAtUC6Zu1x/onAGMzW7mwxI0VYgl2c5vhAI=,tag:kEyhFBHTnzIn9LcRjaMp4A==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdA7AkvCE7qpRAtF58aFp4hXMDmtCQU2HLjCShh0cEyjX4w
            MqJzhBWsIfSh5JFTGaLoCCGrrm3af1LPJfLcdYfGRCBTjWllhyA+orMvsUfbXuPt
            0lwBWv7Nal4mXIWmwEhVAHt3B1G0RYXs1caCWad5f9IcMxVJ45zbbGqHvvdqjei2
            kE8nHgK1149WLEMK68AEuBwwEsX+6xsQXLvyT2xiARZm38EAU3apFwKt1uZKhw==
            =slRt
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    version: 3.10.2
