---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
spec:
  interval: 5m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.13.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    operatorNamespace: storage
    ingress:
      dashboard:
        ingressClassName: nginx
        host:
          name: rook.home.tremoureux.fr
          path: /
    monitoring:
      enabled: true
      createPrometheusRules: true
    toolbox:
      enabled: true
      resources:
        limits:
          cpu: null
          memory: null
        requests:
          cpu: null
          memory: null
    cephClusterSpec:
      network:
        ipFamily: "IPv6"
        connections:
          encryption:
            enabled: false
          compression:
            enabled: false
      resources:
        mgr:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        mon:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        osd:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        prepareosd:
          requests:
            cpu: null
            memory: null
        mgr-sidecar:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        crashcollector:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        logcollector:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        cleanup:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
        exporter:
          limits:
            cpu: null
            memory: null
          requests:
            cpu: null
            memory: null
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: mele
            devices:
              - name: /dev/nvme0n1
          - name: bl1
            devices:
              - name: /dev/sdb
          - name: bl2
            devices:
              - name: /dev/sdb
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 3
        storageClass:
          enabled: true
          name: ceph-block
          isDefault: true
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          parameters:
            imageFormat: "2"
            imageFeatures: layering
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: storage
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: storage
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: storage
            csi.storage.k8s.io/fstype: ext4
    cephFileSystems:
      - name: ceph-filesystem
        spec:
          metadataPool:
            replicated:
              size: 3
          dataPools:
            - failureDomain: host
              replicated:
                size: 3
              name: data0
          metadataServer:
            activeCount: 1
            activeStandby: true
            resources:
              limits:
                cpu: null
                memory: null
              requests:
                cpu: null
                memory: null
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          isDefault: false
          name: ceph-filesystem
          pool: data0
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: "Immediate"
          mountOptions: []
          parameters:
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: storage
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: storage
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
            csi.storage.k8s.io/node-stage-secret-namespace: storage
            csi.storage.k8s.io/fstype: ext4

    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              limits:
                cpu: null
                memory: null
              requests:
                cpu: null
                memory: null
            instances: 1
            priorityClassName: system-cluster-critical
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          volumeBindingMode: "Immediate"
          parameters:
            region: us-east-1
        ingress:
          enabled: true
          ingressClassName: nginx
          host:
            name: objectstore.home.tremoureux.fr
            path: /
