apiVersion: apps/v1
kind: Deployment
metadata:
  name: wg
  labels:
    app: wg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: wg
  template:
    metadata:
      labels:
        app: wg
    spec:
      initContainers:
        - name: wait-for-dns
          image: docker.io/alpine:latest
          command: ["sh", "-c", "until nslookup ${WG_ENDPOINT_HOST}; do echo waiting for DNS; sleep 2; done;"]
      containers:
        - name: wireguard
          image: docker.io/linuxserver/wireguard
          livenessProbe:
            exec:
              command: ["ping6", "-c", "1", "${WG_HEALTHCHECK}"]
            initialDelaySeconds: 3
            periodSeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 51820
              protocol: UDP
          volumeMounts:
            - name: wg-secrets
              mountPath: /config/wg0.conf
              subPath: wg0.conf
            - name: modules
              mountPath: /lib/modules
              readOnly: true
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - SYS_MODULE
            privileged: true
      volumes:
        - name: wg-secrets
          secret:
            secretName: wg
        - name: modules
          hostPath:
            path: /lib/modules
            type: Directory
