apiVersion: v1
kind: Secret
metadata:
  name: wg
type: Opaque
stringData:
  wg0.conf: |
    [Interface]
    Address = ${WG_ADDRESS}
    ListenPort = 51820
    PrivateKey = ${WG_PRIVATEKEY}

    [Peer]
    PublicKey = ${WG_PUBLICKEY}
    AllowedIPs = ${WG_ALLOWED_IPS6}, ${WG_ALLOWED_IPS4}
    Endpoint = ${WG_ENDPOINT}
    PersistentKeepalive = 25
