apiVersion: v1
kind: Service
metadata:
  labels:
    app: wg
  name: wg
spec:
  selector:
    app: wg
  ipFamilyPolicy: PreferDualStack
  ports:
    - name: wireguard
      protocol: UDP
      port: 51820
      targetPort: 51820
