dns:
    ns: ENC[AES256_GCM,data:tFBaHI7hsV55mCCJV/Ie/w==,iv:+L+FmJ7vwKJKXRZZVgTtGq7YIfBRM/6Ck2vv38/06VA=,tag:KkRtvGIXLJU2m1Ls3YbzUw==,type:str]
    zone: ENC[AES256_GCM,data:/7BosuNxvg5Qj9zgo5CVJltS,iv:OjgQmB0xdOngpg3vSPDUqwfp120ELLthiZu0K6w3tIY=,tag:oAi7MSSlPuTdIt1QPZw0xg==,type:str]
    http2136_vhost: ENC[AES256_GCM,data:+/KON4UZtJUo/UEzYuULJu2XevDIzw==,iv:oX9jLoyBXbY9LPoN9nap/vXsPe5miDnezCYhM99jTt8=,tag:AzZfrJXs1iN4SOSHkQFC6A==,type:str]
    http2136_token: ENC[AES256_GCM,data:3N3IvaW4Pe8NMmYOomMhcqN8t+MujzWch+pEzCqi9fxEGRJJ,iv:YtphmbDGvWAjBHFDKX6E3GSikcvvXB6nX+Jz/ZGYdaY=,tag:k67yoMnCI2mdbvwEusRT3A==,type:str]
    rndc_key: ENC[AES256_GCM,data:Prc/Fxv9eBdl18jCgYbgY4PF9HfXGeDgRBlg7CnomlzpYLt7y1gGF6kFuVw=,iv:qY/vuR2ntXTzWzYx+tEz4Ag9atRV2C/lOllR605lfZg=,tag:UP8UUoCbKrhvsy2G4gMuqQ==,type:str]
    ipv6_prefix: ENC[AES256_GCM,data:gafuBDwly4mms9nISg/1VylkYww=,iv:uDSNukRQ/0gyMuF4K1I1X52NQ0KXVYt0dm7U+c86xDU=,tag:V8bT4qUsVYDPt8yw5Mx6iw==,type:str]
    nodes:
        boot: ENC[AES256_GCM,data:bnU=,iv:tHesEsqK/UXezd7bDsXMHfaEdmxynRWcpf8tClABqDc=,tag:bg8HTIMG8pLYe2yossDXzg==,type:int]
        bl3: ENC[AES256_GCM,data:P10=,iv:B3uK5ET84DX5QB+996LXxmMZdqLEIJvHiVHPqndWpoM=,tag:a8pip1wPoO86HTsTnc+9qQ==,type:int]
    kube:
        - ENC[AES256_GCM,data:gmG1,iv:uq3iDAi+d9eSnNtr+Zt2i9ZDR49jDF+T6ToM1Zvw2BQ=,tag:ZXupJGSQL2VtJ1LENyEYKw==,type:str]
    custom_records: ENC[AES256_GCM,data:JNRBhaqLXUHsmC6oX+SdZY0R3W0HDNxZGG99+WIKu5fUsaFRjW9MW4sr8uunSEnRK18qwkmULbm+TRQRgX+LlkmVbPyhGTCZ5Jn+te239+NXghZtid3QKU4HDWSYcII2hAmBw26UJqeIreUefwNIm/hRtGVDJQ0jjpMQbgFi/HksoLscJT0PPrsI3v3576/Dk9sopOeLpr6Kda1vMkwsOmVYldBiidFG+r9qcfsG2X42Z5ANeGD7H4+sJkezS4ghdQ7nLFNhBXoqJMAGoFYZCpHSC34PFIuFrSgow+4qPiGCbiw2ELtHxcW7zqMLQ8GMPy7sXBiqHkL/0brCrFPg+DZXwOeBeWXn5rHmtFatxN52IUw6EsyVjYA4W2/3G4Mjr9QdzuhrVHixigaYHjvvZwhj/xI/9UKihosYaoR0St/liXMt+IpH2dS9KKhbLggEBwrDm7Q+9CueIAoCaZsO7Jqh6n1WtmDgZreRtcT9tuJEXIzpAWNMFW78+S/tVT8QqnJw5/Rg93PRXU6N54H0yVvSKWOpaJ5Fqlquzqlom88FfozvtqJPt8NxidHaequmzPcHRG76ygQbpdWkV9ipsgkMnWW9jDsN2YsnX/S1eQ4S+NvCbISix7wpbadXa1RMgntMVJ0/rFq3bQVEqeoKzeatcek1pVzGtPmx6g0lSwqpUvMCJV2V7/gfAtrKV5oovBc8MR4+N0X8SDnFQkIdPcZPZrrc1282K7dylpGUjhN1tGNWJhu+U97KZv+cvK1pAaR6gSJaS2/qrFEh7D+ZIcsehvpq+1I+CAHaFOosOlQT5jNa4UbNpAdUxIjp62M1yhBBAash5oydUTfpFJ0U6ct0by4fcu7fphL/XOp32zHb0MBzR0sgbDiKR1yZu+RmrZhB7W9JiEu0/e+so+hOmQSZHqRv2qFzF9cW3PSMZVU8NML79WVqF3td3qrIzsr80Sx0WwTpnDOFvyX5qcztBxfh9N60Yb/WI1WFczrAc72MQ1SJ/0X3VDpxLUPdY2Ex+GnUWh1ocQxD7GRFBfJ4dA6ETQ2w5UKkwn9//0OGD6ngO+GnA9NDBtxPNyDyYmeqmfgmKj7Cl85AcvBoE9Ea6LxmYqzcXLkfyiVKvIsdlNjTjUFVuYyLVyc2bt/ZFB4MIPnSNn4sHkibU3PE6Ul91WzAPyRU/bPpEoAPEnJj/M2s9NBcC5v4u/vlVpP6L1P1uq3PHS2EGwSxcayIn6wlO5nnit7mLrIpzKETnBPjYRgNRntxWM+lJoszsgZpVKmQI0JxM83L4TRpxT9A12GA+whVxlHZZNq0Ae8ff18ky/JSsbxBTDnewUh0ZlXRggLd35qNxaHy0JUI1EiEIw8A8CKkRjkkYztwDgZGwlTLN5clJLG8NJt0brb3MotiuohcT+rIs+7UnmLeFGJ+3qXjUSCnti/V/td9X+xvDQ9CvwO7kGlCpprKwibLMQ26uWdW7GFTNuzkPDxKiA+p8TC+ZIcTQeD+UMCUWXs=,iv:dWvnOu1VL36sr9rzdx4WMes1WgJcmZ+ycUbhd5nwj/w=,tag:wnnjEyuTS+MyncPnQd/XqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBweDBpc2xqZzVNOGd3V0Y2
            cHg3Y2J0R0pCcnM0c3BORi9hcTJ0N0FWOFdJCjRTS2l1TWRNY1lkRUxXaGs1d2Nz
            ZjltYlgzSnNXY2pyMG14N2F5TXVjM1UKLS0tIEtmcmhRemF3QWRjRnZRNzQrWkp4
            dlB4M29BcnB5R3VvQVg2MHhhSEp0enMK/td5N6P73gCjHqitTkcZ4GpT/uXLGEU9
            6W8pB9XhBsl74/X89NkrdvLAgVTkstM3BIlBpTbDyclUl/MMU8a9AQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-09-01T19:13:06Z"
    mac: ENC[AES256_GCM,data:z2eEKacedtGZieFzMxJovzPtMvSsApESGp1+C5QnNTmd/oQnqTvEsiqa7d0PqBYt8A2cciouyXCI7exVCekSURZEzK2b1WY2qUqRdeZ602WQf1/+pO58URwggcVpwX23xheHQq0NuddcBYfQn9YslCFyuxcPU9Ad1Sj+JZAYggs=,iv:vTNoREMF68tH80cnveiXLboNwa8sPlQREUt8cr9UQes=,tag:qB3y5IbFmxXT2hkTfu78iA==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdA55Yq37+gHr2RDjnd/K1z6sduICr0ivFOmDinDRgh2FEw
            4nGnrbNpO/EQ4/6VQI1+dPYGjRRSgnPm6IJzelH8EslrW5L/IGKxmbN8ZaUzANz/
            0l4BKQkTUTQPUfguOdad8FcoYJcAOGVBee9Ivd0UJCZRK5BZJBtBjILMd5kqBczL
            YdXJGVZ4Tm6u7opUlT2/XW1lWXU6LKmziiH0vabBimKWyAuE6sNdhTcjHOJdJKxk
            =vRcy
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    unencrypted_suffix: _unencrypted
    version: 3.13.3
