---
- name: Restart Kea
  ansible.builtin.systemd_service:
    name: kea-dhcp6-server
    state: restarted
    enabled: true
    daemon_reload: yes

- name: Restart Caddy
  ansible.builtin.systemd_service:
    name: caddy
    state: restarted
    enabled: true
    daemon_reload: yes

