---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-operator
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 3m0s
  retryInterval: 1m0s
  path: ./k8s/apps/storage/operator
  prune: true
  dependsOn:
    - name: monitoring-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ceph-cluster
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 3m0s
  retryInterval: 1m0s
  path: ./k8s/apps/storage/cluster
  prune: false
  wait: false
  dependsOn:
    - name: ceph-operator
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
