ipam:
    operator:
        clusterPoolIPv4PodCIDRList: ENC[AES256_GCM,data:YAZ9IruXj8bJrja/,iv:UnZRZVqWBNaygdtPxSygX1QLo5RjBum61P4/l9CnNjQ=,tag:4cxlfKyiaZspKcOaypwH7Q==,type:str]
        clusterPoolIPv4MaskSize: ENC[AES256_GCM,data:oTU=,iv:0+CybilioPZPiDsLGRYRTEpOvN88L5jJnRYt9qlobHA=,tag:8i983k5Dv91ddk5D4sPUcg==,type:int]
        clusterPoolIPv6PodCIDRList: ENC[AES256_GCM,data:padQpha1zj/OpsitMcwUShkbHQ==,iv:U7QE98LewnwmBR8ICkwfpfv6H3ZmnaLXrVo0i1yIOVg=,tag:nu+17dQV5GVEQS89JWCW2g==,type:str]
        clusterPoolIPv6MaskSize: ENC[AES256_GCM,data:JrE=,iv:U5mKGOOUrJaC6Iij4JQfERmu8V1NG+hn31F172nlpX0=,tag:HNRl3c6RdASXSEUL0s1KwQ==,type:int]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlMktYOXNCZmozMEpIVCtJ
            SXdUV1RLSEkrZGpueVZHa00rcGUwUk0rdW5VCkxUQTVudlpERzJXOGdWWlA3c25w
            Y044L3pETGtFb0ZTZy9icGhBQTBwdjAKLS0tIHE3RW9PVkRyTFk4Tjc5TUNacTdZ
            WTdWYzQzQWNDU1FBek0yZnJTS0Rpb0EKXreG5Mr3DTZQ8R0mlMCNSKIymG3XTxyM
            1AwIyJJOk8iOZTHHnS57YMMUXRELzGVGdyN9E7YrTXdD5BhXt75WRg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-08-22T22:43:50Z"
    mac: ENC[AES256_GCM,data:MpQiuHXTMyX/NTFt16cGOpYInl7rI9nZFob+7lysV/G2JVqPwwmpS7lYDLxD93bfRatrZsFxU1Vc1jFGEGiyM8tlExgwBPFln0q2K7c4SrbC87fZTTMqK5NSRSDIqobt8jCoy2tKbn+ZiK2jqJXPEFPY31tQVqnf69OQsJNB+Ns=,iv:gruvh4GHmpcNOL/m6Ikuust/OxGfCStgbmFReeZybhk=,tag:0E4GHyJiy5PmBDM4fHGQxQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
