apiVersion: ENC[AES256_GCM,data:IU9HjN9Q+zgJSXzQ,iv:PY80mvn1G19p4HXsUnNxnU43GOUVpgRbRww79W+jmQs=,tag:9wdfTPoXv6l6rvUTQZs0hQ==,type:str]
kind: ENC[AES256_GCM,data:rFcbNIZci2uZqSRaEtgI202zZxi4znGB,iv:Nxqi/AwW0T3La6N5hIgg82afc177LCTZdFlNPl7SKmE=,tag:Wwu0yQzGW+VihfdjF3KqdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:PBEhsDHtxIMH,iv:FeF06gjDt9XGohMfxFvohZTjIahDogxTV6HJl55pzYQ=,tag:aXN6U5sc1S813OcOIt291Q==,type:str]
spec:
    serviceSelector:
        matchLabels:
            gateway.networking.k8s.io/gateway-name: ENC[AES256_GCM,data:rX/zmG7eIzIfhQ==,iv:a3w17oZX62LA+bAIzLs+m3ZsrBdeLF9JaAR6IcIwfbc=,tag:Rb5v4BuikxFt8otb31rpcA==,type:str]
    blocks:
        - cidr: ENC[AES256_GCM,data:XKoaoShUMJ7b5Hz5FjhY0tktzg==,iv:KU8ArLh0P7/YfezHCaqXrV/2GD+btVbdMxCkBZv0IP4=,tag:+ofgdEnglnEzKSMwm52Trw==,type:str]
        - cidr: ENC[AES256_GCM,data:0cgXPhJ63PTgTQ3ItI/L,iv:qDIy8KzSs+m0Ol4Hw3f2t3fNezocrU5SmwVp3aXZNCw=,tag:UUsYitWm4Qb25LYpnfRjqQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVXhQaDFPR0NBdjh6My9u
            VjNJZlVsK0VLeU5lZ1JVS0JWanVWL1U1UGhzCit5L1pvQ3M4UllZWHY4ZVMxRksz
            bmk5Z2Y2RGUzeFZ2UjJOaGQ4cmZZb3cKLS0tIFhPV3FJZ1F6UXVwZzBZSEJ0V1hK
            ZG1NdUxmaC84V3ErUjhaY0hMV2hLemsKedVJIODl4uB6QkiTh3YZ3QTEs/LZI5cb
            cEo1SFcP5gmI8MQ2viJjDHzISPAwthAJs6BlkjGaX5hmvj4B7IJIqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-08-22T22:36:10Z"
    mac: ENC[AES256_GCM,data:GmmpS3RCRotANc5sF4C4K0C2v6F1KyIrXoYWj5FrwnjqJOM6eoLkF2NlPOPXuWTEQJhErp+WvUbY7atK4WpP2Rc2rvbcwbE2qRVyhsNUTKRnB1/nHEIGupRO8LaKNEKA1O/YmPOdVDrrHzGycomlGAAYlEAjv2Ly0JdxQ9rhZyc=,iv:oX85JtPI2rG60i/tjjdBaJSL1IBk8NdCJE2bYA+UrFM=,tag:+sLGRj6OEHRG8cFVaQJdoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
