# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - local-path-provisioner.yaml
  - cilium.yaml
  - gatewayclass.yaml
  - ippool.sops.yaml
  - cert-manager.yaml
  - reloader.yaml
  - external-snapshotter-crds.yaml
  - volsync.yaml
  - kubelet-serving-cert-approver.yaml
  - metrics-server.yaml
secretGenerator:
  - name: cilium-values
    namespace: kube-system
    files:
      - values.yaml=cilium-values.sops.yaml
  - name: cert-manager-webhook-ovh-values
    namespace: cert-manager
    files:
      - values.yaml=cert-manager-webhook-ovh-values.sops.yaml
generatorOptions:
  disableNameSuffixHash: true
