snapshotsEnabled: ENC[AES256_GCM,data:33JYC3Y=,iv:PcZ4YUlc9f8ZEAatYxR/AYIVtDMxgqaGgQxdNObcLOY=,tag:iRac0HX4eweXB8H5RhrnCg==,type:bool]
deployNodeAgent: ENC[AES256_GCM,data:YfNLrA==,iv:ZZqkNTxpSJKMfqHUiVJsWEIeR8BxC4oJopiPuBdMJLg=,tag:Tslo5AkvatjL20FACLHCqA==,type:bool]
credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:QnJU/twryebCKPJWokA2K24Z36zgTtFADVRnnfeVL2cXPxpDIBISDJUHxRSJPvUlIMK9hhhTYSXPHfGn7Mgo7UNyIOBO9puGMWryonwpStX9K3HsX5dSR3Y1zRWu5Vm/RYw+4s9gGsEsQXVn4/lvbUS6Q8k=,iv:lvsJsN9Ed2zf7bGPwh9PyLHJj9aJrweyPKeGGv+CPnU=,tag:bgo9E0Llp6KnlKHR6087IQ==,type:str]
configuration:
    backupStorageLocation:
        - name: ENC[AES256_GCM,data:blYZApwhag==,iv:+YPQ9RB0rAs6Biifds+bsL0FYNFEB6iNmMjf7b/Mqj8=,tag:0pSHgPMUoC4UVSBcgjVM/w==,type:str]
          bucket: ENC[AES256_GCM,data:6JhUIcDQ,iv:gFyJFvVr3k5GHoMoeb8TbzZORgLP6aSYID10RS20x7I=,tag:Z+I52PPdK8ZUKqnBUmfD7w==,type:str]
          prefix: ENC[AES256_GCM,data:Jn8=,iv:hMNOSBgBUVtYQimPEtHyJv5YMTrQtiJ+UMjpTgoNyMU=,tag:hl0lKGxZFrhpbbGVY1i4Cw==,type:str]
          provider: ENC[AES256_GCM,data:+fgK,iv:PlzqirWjXZkSUjiJKmOY8/8vzZbRqW1KIfO8W/ABCeU=,tag:ZdQMjZTCXfGDe1ciIvxGjA==,type:str]
          config:
            region: ENC[AES256_GCM,data:pZOe,iv:PLfX3GTo8wmXxFFMP1j0W4Y/Di/f81flHaL0ut2EzhA=,tag:7DIMU/NqwU6m5b2JFOjD0A==,type:str]
            s3Url: ENC[AES256_GCM,data:YZ3t43/i8r3gK7W1zcdCNC+E70MlGOHHw/KVoUkHYw==,iv:18svGw6VgZUpHxNi62tSh6wQOfsdde8YLrJuM2tUEiI=,tag:yRUucjeKMdoiRdKqyxYE8g==,type:str]
            s3ForcePathStyle: ENC[AES256_GCM,data:lkV2fQ==,iv:xPGcyR+xmAp7CVJwWYmWwuy3nQMCMa2RLceO1Cv5Ekk=,tag:LZBRf8dtBN6I9mEwSHCNfA==,type:bool]
            checksumAlgorithm: ""
initContainers:
    - name: ENC[AES256_GCM,data:z/++Gq0HQQgNC3P7yUp6TFSxI0C8,iv:/FQ6yZh1VYzgQo7dV4eznuraN2BqT4yFAe6E70zxqC4=,tag:+3+Y+mRUvpboGnYkk0IAxg==,type:str]
      image: ENC[AES256_GCM,data:tD3Xowa2DAnGBDfJWMKcxq8pgrJN1a1Yx+yyajlAKs8/lZ5y,iv:mInm7J+Cvg34xdMKkBzRQBNYNBENQq9FoYjcv0PCJbc=,tag:zFdPR0o0f9dBof5984WFzA==,type:str]
      imagePullPolicy: ENC[AES256_GCM,data:+0EE0qQI8ljM76Nr,iv:zelUekBcqxFLjtbnlR5/SEvf2LeAvllGIlJDoZNsNgQ=,tag:8Roa2XZCorzcVvYDtSdxEw==,type:str]
      volumeMounts:
        - mountPath: ENC[AES256_GCM,data:lIiNGVd3/A==,iv:Qmi4iEErsh74OnnySeen8Goc7Huw2p+2/y+LZYZgGog=,tag:VvuJd7rr7zistB0G0dYLzA==,type:str]
          name: ENC[AES256_GCM,data:sirNLHo52Q==,iv:hHk5TQnm4WDiaoP362qb+vwu4zeIcY+nWHSrtSbe6hI=,tag:AIdWqlKAFAnrGt8BsLGNOw==,type:str]
extraObjects:
    - apiVersion: ENC[AES256_GCM,data:51M=,iv:kmsKqPNF4CAF6uGGHI5+0cV+8razRKMVUn9X/BMvoNI=,tag:scLap6TKxFDskxi20WFsyg==,type:str]
      kind: ENC[AES256_GCM,data:6RawKH+m,iv:jp7wtsYktxfoaHb2vEuXKHAFm4N3uNE7cnSufWwbpKw=,tag:nn/fuIKcW9d/h5/Jl0rHwg==,type:str]
      metadata:
        name: ENC[AES256_GCM,data:1lYG/EyKZmt/wvfrxO2//xzBXscTg9E=,iv:4Q+romIH//Ig36HdUHAniXnrLQN1Y1fx7rz/R0uWYz8=,tag:dazxXsuzb3hfP/8rX/H1hQ==,type:str]
      type: ENC[AES256_GCM,data:hOOEGR04,iv:0ZKx/9zmBjPw1Gp70HCVLfv2SkKwzTWy6ssoW1bL3QI=,tag:ZT07TnEjq1tigejFX++QnQ==,type:str]
      stringData:
        repository-password: ENC[AES256_GCM,data:F5xq3pj7PG0aKDdQ2K0JnJfU40JTqmze,iv:TEbEKP5f3peSZ/MvDCudVNaqzNTxKOH0HhbxqTDJMoo=,tag:R0kuLRKjTu5F9GDTuEcUUQ==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYi9pbWE1NjFXaWJjcEFT
            TURlb0U4T2EwcGFXeE9zTnR4bjh6endzN2xjCm9HSFMwYWZ3TVBjK3phamZNSi85
            Ymc4amdxL01hZlE4Z09wd3pta0p2OVkKLS0tIHRxQkIvWEtBdG1yb1lBdGQzUWN5
            eFYwYVV1REg5emwrSzVPWTZXZDB1NTgKP2x4OXA5p2DMtb6zF1FQcZoWz5cXOTlz
            9K7XWpz+xHDubd325utFAl8F7U1FN1wwE/P9bXoNkhqHLFCTkXi4AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-02T23:30:13Z"
    mac: ENC[AES256_GCM,data:1Mzr7S8N2Ro2ZB7gXjnBLpp9TTUxTDvrOMEbFs/VWouLGvFwEerBXQ6hqi3S6N/PXEx5SSQLvlncyypMOi2aBtQ34uOsBnSm5KPAXJlOMDZEtsN2VQwIYzw2zHDFsLvP+/rqzs0kEXtWvjv4vHoJCahzHLwydhB3rbwPtcEiLoM=,iv:/W+Poiguyi6+XpgvwSlG3Qo37nRXeAajNAT6B/NviqY=,tag:vRq2PxIj3mY+jKD8GMACCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
