wildcard_domain: example.tld
gw:
  ip: ::1
lb:
  ip: ::2
uos:
  system_ip: 192.0.2.1
backup:
  ak: AKIAIOSFODNN7EXAMPLE
  sk: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  restic: your-restic-password
  endpoint: s3.example.com
  bucket: backup-unifi
