apiVersion: v1
kind: ConfigMap
metadata:
  name: authelia
  labels:
    app.kubernetes.io/name: authelia
data:
  configuration.yaml: |
    ---
    theme: auto
    default_redirection_url: https://auth.home.tremoureux.fr
    default_2fa_method: 'totp'
    server:
      host: '::'
      port: 9091
      asset_path: ''
      headers:
        csp_template: ''
      buffers:
        read: 4096
        write: 4096
      timeouts:
        read: 6s
        write: 6s
        idle: 30s
      enable_pprof: false
      enable_expvars: false
    log:
      level: info
      format: text
      file_path: ''
      keep_stdout: true
    totp:
      disable: false
      issuer: authelia.com
      algorithm: sha1
      digits: 6
      period: 30
      skew: 1
      secret_size: 32
    webauthn:
      disable: false
      display_name: Authelia
      attestation_conveyance_preference: indirect
      user_verification: preferred
      timeout: 60s
    ntp:
      address: time.cloudflare.com:123
      version: 4
      max_desync: 3s
      disable_startup_check: false
      disable_failure: false
    authentication_backend:
      password_reset:
        disable: false
        custom_url: ''
      ldap:
        implementation: custom
        url: ldap://lldap-service.auth.svc.cluster.local:3890
        timeout: 5s
        start_tls: false
        tls:
          server_name: ''
          skip_verify: false
          minimum_version: TLS1.3
          maximum_version: TLS1.3
        username_attribute: uid
        additional_users_dn: ou=people
        users_filter: (&(|({username_attribute}={input})({mail_attribute}={input}))(objectClass=person))
        additional_groups_dn: ou=groups
        groups_filter: (member={dn})
        group_name_attribute: cn
        mail_attribute: mail
        display_name_attribute: displayName
        permit_referrals: false
        permit_unauthenticated_bind: false
        permit_feature_detection_failure: false
    password_policy:
      standard:
        enabled: false
        min_length: 8
        max_length: 0
        require_uppercase: true
        require_lowercase: true
        require_number: true
        require_special: true
      zxcvbn:
        enabled: false
        min_score: 0
    session:
      name: 'authelia_session'
      domain: 'home.tremoureux.fr'
      same_site: 'lax'
      expiration: 1h
      inactivity: 5m
      remember_me_duration: 1M
      redis:
        host: authelia-redis-master.auth.svc.cluster.local
        port: 6379
        database_index: 0
        maximum_active_connections: 8
        minimum_idle_connections: 0
    regulation:
      ban_time: 5m
      find_time: 2m
      max_retries: 3
    storage:
      postgres:
        host: authelia-db-postgresql.auth.svc.cluster.local
        port: 5432
        database: authelia
        schema: public
        username: authelia
        timeout: 5s
    identity_providers:
      oidc:
        access_token_lifespan: 1h
        authorize_code_lifespan: 1m
        id_token_lifespan: 1h
        refresh_token_lifespan: 90m
        enforce_pkce: public_clients_only
        enable_pkce_plain_challenge: false
        enable_client_debug_messages: false
        minimum_parameter_entropy: 8
        cors:
          allowed_origins_from_client_redirect_uris: true
    access_control:
      default_policy: deny
      rules:
        - policy: two_factor
          domain:
            - '*.home.tremoureux.fr'
