---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/storage/rook-ceph
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-tremoureux-fr
    namespace: flux-system
