# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: apps
resources:
  - namespace.yaml
  - gateway.yaml
  - gateway-private.yaml
  - http-redirect.yaml
  - lldap.yaml
  - pocketid.yaml
  - vaultwarden.yaml
