# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: registry
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: registry
resources:
  - namespace.yaml
  - certificate.yaml
  - gateway.yaml
  - http-redirect.yaml
  - registry.yaml
