apiVersion: v1
kind: Secret
metadata:
    name: wg
type: Opaque
stringData:
    wg0.conf: |
        [Interface]
        Address = {{ .Values.wg.address }}
        ListenPort = 51820
        PrivateKey = {{ .Values.wg.privatekey }}

        [Peer]
        PublicKey = {{ .Values.wg.publickey }}
        AllowedIPs = {{ .Values.wg.allowed_ips6 }}, {{ .Values.wg.allowed_ips4 }}
        Endpoint = {{ .Values.wg.endpoint }}
        PersistentKeepalive = 25
