wildcard_domain: example.tld
gw:
  ip: ::2
backup:
  ak: AKIAIOSFODNN7EXAMPLE
  sk: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  restic: your-restic-password
  endpoint: s3.example.com
  bucket: backup-media
papra:
  oauth:
    id: providerid
    name: "Provider Name"
    clientId: toto
    clientSecret: toto
    url: https://your-provider.tld/.well-known/openid-configuration
