---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ ansible_host }}"
    use: systemd

- name: Purge cloud-init Netplan configuration
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
  notify: Netplan apply

- name: Netplan configuration
  ansible.builtin.template:
    src: netplan.yaml
    dest: /etc/netplan/10-base.yaml
    mode: 0600
  notify: Netplan apply
