apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: http2136
spec:
    secretName: http2136-cert
    dnsNames:
        - {{ .Values.dns.http2136_vhost }}
    issuerRef:
        name: letsencrypt
        kind: Issuer
        group: cert-manager.io
