apiVersion: v1
kind: Service
metadata:
    name: dns
    labels:
        app: dns
    annotations:
      "lbipam.cilium.io/sharing-key": "external-ips"
spec:
    type: LoadBalancer
    selector:
        app: dns
    ipFamilyPolicy: PreferDualStack
    ports:
        - name: dns-tcp
          protocol: TCP
          port: 53
          targetPort: 53
        - name: dns-udp
          protocol: UDP
          port: 53
          targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
    name: http2136
    labels:
        app: dns
spec:
    selector:
        app: dns
    ports:
        - name: http2136
          protocol: TCP
          port: 2136
          targetPort: http
