apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme
spec:
    acme:
        email: ENC[AES256_GCM,data:gMnZltTioiwTxvUNbFsY98xCHA==,iv:5we6VqrOGqL011XUUCFrhfKU5U04K8cRasWVrfMkBm4=,tag:Rf1nowXynunRdhWIOz3DIg==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: acme-key
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:iai11Bti5ZMdjZZe+esIMg==,iv:yrN1tFIjmcmfMpBvs16U3d+Dda9O7X9Z9oVIHIHlUzg=,tag:gnINj5DsNaRh3ZXP4iJ6Vw==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: rndc-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7ehhg7p0xsxnsdggen9plw5p20rxs89pdy3fmwafr84dh4qdylstwad7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcFJ6ekk5aWFCRFFXcE44
            OFZSSERiUU41RGlDckxwZ0JCamZNbjIyclI0Ckh5c0tjb1dNc1dicmxJb1BnWVZZ
            cWRod3BGbGFMMWdmeVNYdUFiQ1IxTEUKLS0tIGltb2xwY3dxbWVFQTkzbkZMREtC
            WkpwV0xPZkg5Y2twaEdTRHgwdjJsOUkKIP+t+RUZdOki+p3DZqe2plc8+ok7Gx/H
            XEdra218m4q+aAjA1YiNPnmJfd/Iw3bcr9OZNkMaeIxatOuo2MyDng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-27T17:00:55Z"
    mac: ENC[AES256_GCM,data:3mycXl8LFJLsfpq3p2y93AGMRHJuFusHBswiWRgIf5BxO/CkM9ijyb69SUDo1fuw08gkD9oSpwJ003nYs4bWcFaL0qPKIX173oVYEL5Y4y7Aeqi8pbRlwvn7FicvlHD2fkQJPcsCyr20roJSrwDyUAQk7Az+rwBtUc2ubyPBd5E=,iv:u2m0jUNY+S715s468Eo1KPsusjeaebsNYWdwCmi50ww=,tag:3NdGgpmUnd9mvsnMY/Y9Dw==,type:str]
    pgp: []
    encrypted_regex: ^(nameserver|email)$
    version: 3.8.1
