apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme
spec:
    acme:
        email: ENC[AES256_GCM,data:Nc5mXF84wKoo9Bv+IhvmXwSOzg==,iv:yET31ew0fmUEQA9x0jarStSl0472RNBdtp6UHsvsMng=,tag:+X8o5m+EN5doLs3SnmoiWA==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: acme-key
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:CijDjhEZSZZDqRPOKiO9WQ==,iv:ld8RvQNFrNOH20Wc19zjgwQoM9h5D/4iMaxj7n/EjA8=,tag:3pNDWcwe1uGfgLp+W7J/aw==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: rndc-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1pch6mmgqfw7ll7hhfk82kg7r8gc7njl6vv9sutvu7llrapjvpqnq84ne2e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1elFIQkhsR21vcVlhY3l5
            WWhyckd2UUYyVUFxM21VNDdtNStNZ0dHcTJFClFjNXF5NTBMN1k3TGVPM2VMK1M2
            OGdvNk53MU12enlrZFVLY2NkVHd6TUEKLS0tIGorZE5hQUxlMlg0RFkyYWRaTTN3
            MHZBeXc5b094QUVidldoay9wK2x3cDgKLpy6fmWUSpuDXm8r7HZtEjxboIH6aqJr
            AwEP9QfbvmQvbfhZfvNYANUQrPHiTZrIrHydGBF8uPGl96ctIV66rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-01T22:25:34Z"
    mac: ENC[AES256_GCM,data:V1H0BS66rY2GFcZ4H4dcb73jeSiRAL1Q+JKr9ZZi9Y8Rbu39XMb9rxtLT3XqdjZJRzXLBHT4jmzFAFgxAKS8J5TxQASrU8Jw1/ixv7t0+tonl9er4dflq0Z+ZzHJg3xGVjFKIS0qBJ6FBYD12aZizRVy12RF61fI6U3IJYI6I/o=,iv:yUoIsrdKE94NCrc69PFocdBi4kUuerKR8mDrHtOQZI0=,tag:mPegxruzjJWEJ6hmuO3yEw==,type:str]
    pgp: []
    encrypted_regex: ^(nameserver|email)$
    version: 3.8.1
