apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: acme
spec:
    acme:
        email: ENC[AES256_GCM,data:uD6eYIPBrPyhlq9koc0INiMz/g==,iv:m7miwdxBA/q/6pdIRIrbaAfOvoQ5RQd/3yfvr6ooXHw=,tag:jDTmlnNraQTxcrkyc0ub3g==,type:str]
        server: https://acme-v02.api.letsencrypt.org/directory
        privateKeySecretRef:
            name: acme-key
        solvers:
            - dns01:
                rfc2136:
                    nameserver: ENC[AES256_GCM,data:/1OXQrMr+pgnO+telT0OQA==,iv:P4AXhioSwt/B1VxfRseMBNnHYQoGEAxSOZ7ymiHHp3c=,tag:doiSJQD/fo5k7yS5GHydCw==,type:str]
                    tsigKeyName: rndc-key
                    tsigAlgorithm: HMACSHA256
                    tsigSecretSecretRef:
                        name: rndc-key
                        key: rndc-key
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7ehhg7p0xsxnsdggen9plw5p20rxs89pdy3fmwafr84dh4qdylstwad7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBc200WTZCT0Z3ejREeEV0
            Rk5hdFJ6bEU5MEVwQkFuTDl0OVUvVW1SNEZrCkdvZUtyMHRNWHBYcGx1YUN2YkRG
            bDd3NGJuaVowREoyenZNOFJ1Q3hvMjAKLS0tIG1SM1NSTVRHV3d5anVzUHNHSEgx
            QXJiU016WEtKNWFRSGY0TmVlSFVaNXMKST1QHc8cyd7BHzHp9cEkJylhfN8wWfji
            qXVK/E0kXKWfD7PXw+Nc1y9ImbRNtVeh65tkfO7dFsCR4K3TEfwQBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T22:21:38Z"
    mac: ENC[AES256_GCM,data:FzNNh7iRueMcB0ATngi3bqsh7CmYttU/GlwxHsbOVRt6kWDzBvC0RevH+UtujcEK4Tj3YzbB0a81AP9TROHymEGmOekS7m3lOEnZDN9X8DS3ynu7EAMiAtyp//y+jr6468YrjFu6rMJfvGICrGB7rldxZusKE2YV8zfECoTZv5E=,iv:lBICc9faWZiXeZszopYwqZhY2GHNtR7FGq5+m/E27CU=,tag:uJYjPzs776XjGwt4NdfY1Q==,type:str]
    pgp: []
    encrypted_regex: ^(nameserver|email)$
    version: 3.8.1
