apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-data
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
