# https://taskfile.dev

version: '3'

dotenv: ['.env']

tasks:
  default:
    - gomplate -f cp.patch.template -o _out/cp.patch
    - gomplate -f all.patch.template -o _out/all.patch
    - talosctl gen secrets --force -o _out/secrets.yaml
    - talosctl gen config --force --with-secrets _out/secrets.yaml $cluster https://$endpoint:6443 --config-patch @_out/all.patch --config-patch-control-plane=@_out/cp.patch --output-dir _out/
    - talosctl --talosconfig _out/talosconfig config endpoint $endpoint
    - talosctl --talosconfig _out/talosconfig config node $endpoint
  mele:
    - gomplate -f mele.patch.template -o _out/mele.patch
    - talosctl machineconfig patch _out/controlplane.yaml --patch @_out/mele.patch --output _out/mele.yaml
    - talosctl apply-config --insecure --nodes $mele_recovery_ip --file _out/mele.yaml
  bootstrap:
    - talosctl --talosconfig _out/talosconfig bootstrap
  post:
    - talosctl --talosconfig _out/talosconfig kubeconfig
    - gomplate -f cilium-bootstrap.yaml.template -o _out/cilium-bootstrap.yaml
    - gomplate -f bgp.yaml.template -o _out/bgp.yaml
    - helm upgrade --install cilium cilium/cilium  --namespace cilium --create-namespace -f _out/cilium-bootstrap.yaml --version=1.14.0-snapshot.1
    - kubectl create -f _out/bgp.yaml

  bl1:
    - gomplate -f bl1.patch.template -o _out/bl1.patch
    - talosctl machineconfig patch _out/controlplane.yaml --patch @_out/bl1.patch --output _out/bl1.yaml
    - talosctl apply-config --insecure --nodes $bl1_recovery_ip --file _out/bl1.yaml

  bl2:
    - gomplate -f bl2.patch.template -o _out/bl2.patch
    - talosctl machineconfig patch _out/controlplane.yaml --patch @_out/bl2.patch --output _out/bl2.yaml
    - talosctl apply-config --insecure --nodes $bl2_recovery_ip --file _out/bl2.yaml

  encrypt:
    cmds:
      - sops --encrypt .env > .env.sops
