apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - image: ghcr.io/jellyfin/jellyfin:10.11.11
          imagePullPolicy: Always
          name: jellyfin
          securityContext:
            privileged: true # for DRI
          volumeMounts:
            - name: jellyfin-config
              mountPath: /config
            - name: jellyfin-cache
              mountPath: /config/cache
            - name: jellyfin-media
              mountPath: /media
            - name: jellyfin-dri
              mountPath: /dev/dri
      volumes:
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: jellyfin-cache
          persistentVolumeClaim:
            claimName: jellyfin-cache
        - name: jellyfin-media
          hostPath:
            path: /var/mnt/media
            type: Directory
        - name: jellyfin-dri
          hostPath:
            path: /dev/dri
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: jellyfin
  name: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 8096
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: jellyfin
spec:
  parentRefs:
    - name: gw-private
      namespace: gateway
      sectionName: https
  hostnames:
    - jellyfin.${SECRET_DOMAIN}
  rules:
    - backendRefs:
        - name: jellyfin
          port: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: restic-config-jellyfin-config
type: Opaque
stringData:
  RESTIC_REPOSITORY: s3:${S3_ENDPOINT}/${RESTIC_BUCKET_MEDIA}/jellyfin-config
  RESTIC_PASSWORD: "${RESTIC_PASSWORD}"
  AWS_ACCESS_KEY_ID: "${S3_ACCESS_KEY}"
  AWS_SECRET_ACCESS_KEY: "${S3_SECRET_KEY}"
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: jellyfin-config
spec:
  sourcePVC: jellyfin-config
  trigger:
    schedule: "0 * * * *"
  restic:
    repository: restic-config-jellyfin-config
    copyMethod: Direct
    pruneIntervalDays: 14
    retain:
      hourly: 6
      daily: 5
      weekly: 4
      monthly: 2
      yearly: 1
