---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/monitoring/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-tremoureux-fr
    namespace: flux-system
