apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:LeZpIPchtG7hvHMnsAYJPGZG,iv:14AaCn/kFKZI6WHU9clGoZ8kneFeXVne7AhtZRB/TWI=,tag:U+AvXuMxQ8jEjmbur61TeQ==,type:str]
    S3_ENDPOINT: ENC[AES256_GCM,data:SbtTNSUTVJpa0Zn5r5Rjoe51r7MB6bIxBwgUAARHXw==,iv:0ewmYobd3J2vxBNCtUxRRGl4Tnm5cBu8+dasNnCkhn0=,tag:Xup2MxhmanEhRda+czHCzg==,type:str]
    S3_ACCESS_KEY: ENC[AES256_GCM,data:K0HRAZgdWeEON1irOlDm0t+bHJdcJWjQNOimWVj2XcA=,iv:eFr9GG/uXHLUG8aWvvFn2vHtscLQehmGBaXSd3PyZX0=,tag:u0iwQCwlslmPG1dOriRcug==,type:str]
    S3_SECRET_KEY: ENC[AES256_GCM,data:+m15D3Dwm2lbzlVNmHbKwgow6YZOvLQkVmOVH7HJ+Lc=,iv:a8/mAJDeqvKd8HBHgNXlWZjrAJmnuExvc8lus8wM75Y=,tag:KAIbYaQjjHSIT8j5wCJGhw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:5qe/p7ba8rSbKiNfKVXb037Nfx60hWjr,iv:1FbWK3CvgBUUimW5x43lJfzG7cHhm50YmLd9GHyWVRU=,tag:5CKSxTUwGxa8JUrloyymgQ==,type:str]
    RESTIC_BUCKET_MEDIA: ENC[AES256_GCM,data:o6SpaZcj2ctAdl0eLs733+Y=,iv:2X+SZuzLlM09zdcRFelAcTrAQcNjVNNBLgJliWvY8uQ=,tag:rCCf8CODk04n5LTz5Fj6eQ==,type:str]
    RESTIC_BUCKET_APPS: ENC[AES256_GCM,data:a5pxJ11InOehJQThPWpHlA==,iv:tUVe0UA6NLQophlk4IafNNqZ4TtUiRwgEmEfix3ITUU=,tag:WR51XbGiQBxS25E0ZH5H9A==,type:str]
    RESTIC_BUCKET_UNIFI: ENC[AES256_GCM,data:4fhlOK/nwVs9SRlmCvCUVj4=,iv:uWexvPOUPCoNxcGc0m1RG94GXgevttsLojmrA+e+4ZM=,tag:DVJsQ+Z+RkVP5o/pOTWUmg==,type:str]
    GW_IPV6: ENC[AES256_GCM,data:smt32Hys3/t7+RbLbZhMWx3fqF1b,iv:Bp/ToPkA5IH8QO7zP7pbrLifAGhfvWqGU0ZCCxMCyv0=,tag:ZEIwct5DIYy9i6gbuQSCyQ==,type:str]
    GW_IPV4: ENC[AES256_GCM,data:PX0dHXjSyeoEeA==,iv:8dpt4umZaCILEIM5JArhMUbqaMUnJ8CG/VIfI8K6j2E=,tag:nL9koRfeiDIiRHr/rX4S0w==,type:str]
    SEEDBOX_HOST: ENC[AES256_GCM,data:ZCg4KET/Rf8pA/YXFbZeMGUidA==,iv:cfvK9dBRnjXLXJHfOhJy0m3fce/bnQLSzscCVX2OXhY=,tag:NfpKi9Oowb458mn9JymSqw==,type:str]
    SEEDBOX_USER: ENC[AES256_GCM,data:lZBthzVZPQ==,iv:e97S+gCG+79587Vo+WqjG+VczRnokh7RFW108MP9nAU=,tag:367h8xqllWfjK+3bdKObTQ==,type:str]
    SEEDBOX_SSH_KEY_B64: ENC[AES256_GCM,data:I0bkrZ5j2POGL2r3QuNYLdsRt79BZ/SBW+vj+uHdxPrfbVf0d9jjs2QgfLj/+2siWw2LZcW3S1kQB//2uyZ1mp/m0OPsL6zICM0/vyLqSabfU7eRIlia0hgbpqibeIo1j4fAeDGJzLUKrWgwaG9XjflUK0nTyQV1ZhzRtGL6kw+4KtikkKRhEYal9vtvg5ucPEGyvgrgSFIKf6P2puUA+D4dr645V7N6x14ylPe9DnoxQi4h3zz6/NnepF9r6kRdDh1Uyx7tGwPXKLi+jz/AAySS/HUPjZfEQXsC0oTkg2+EP3dVF2bjCUWFZAxs9HJILmAsxAnNwlxLvO1gSAxyupSG2JGR29u4JGifDaEUA86MHcthP24YI7tyMEGdn2njQB/OQzU9qrHu5owfAm1Mjv868BGv1pGKm41K/qpJNN233ONfPT0SWGMxsq09iXHLwj5nV3uZ+4bBTm2A0/Lr+0wxkb3nS2chZChdql8q/IqAwegQc9S3MOfYE6rIiwHpTkplVIi6M3lQ2gUQeMmwTH4cmo8y8VZITnrHYW1n7s8v0MVmMSNei7zmFWsWm/hU3Lft0/L3roM6eIwZ0aE4rj5lAIUx2n52cB01LqpM8v34IC5yX/scloQJHM2IKWFXs5l5XIiB5DSpMoKnn+LgRMGDdNvuTr7yZq/ApA75IgHVMR0eo/qFTps01Sq8S2f3GBLwTVgCE/izCQNOtb5OP1t8Pe8=,iv:CjiuMLeBhmyrvkPh2vmbAO00/O4esb23fCbD+VIXxew=,tag:JWn8KKXnYsvpw4pufQq6+A==,type:str]
    PAPRA_AUTH_SECRET: ENC[AES256_GCM,data:NCXDWiZdueu//I1jy7ESP2cH3jWS14BzUhiz+ZbT7CV9wVbsVPufFOV5dsN7CHWqIDFTs/HSFVwSZY0cIaBpNhBFc9X4VzV+a/rAJugXu9Hf0jWNNjSWhTN0CpbZsN2y,iv:fMCOhopMrMHQIsQIFnuA/UbzYYaFzqivo4rZO/UUijk=,tag:3stKtaUmBMKcHhW14XEG0w==,type:str]
    PAPRA_OAUTH_ID: ENC[AES256_GCM,data:eBYh6JYGOGM=,iv:RRsZ804MU/7yz5pTL4kwEEw4NaYGSwJsEB/MnL2WxJw=,tag:7/selU0tpk3nxC7lplOxtA==,type:str]
    PAPRA_OAUTH_NAME: ENC[AES256_GCM,data:sklSONL5q4Qe4iefoOw8BA==,iv:qF9V344C1rgO+p7Nz+qUd8/oMVrNkLE0CVFQq0XxMmw=,tag:iVN1KZMgjHwqMZmwVYnhPw==,type:str]
    PAPRA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:lQ0Y15dqowkpFD+BmGPX3YMHM0DpJcjqIWeOLeuxuBacINM8,iv:/cYut5Fc+9st8KZL8DgWDdkgdqihWU/5UGwfm/ahOn0=,tag:RumCYjvanNiftPov22pEFA==,type:str]
    PAPRA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:xF1aYLMsWQ4ZbPiYyDuS9gyrhfhz/fqblyh0P9y3/Ow=,iv:oiOynsELK4rkwLCHpeu/J9tzH1sR1b0ZBe81sOn2c6w=,tag:KtDqSYBt60tLMHx3EYOdTA==,type:str]
    PAPRA_OAUTH_URL: ENC[AES256_GCM,data:DoAdCmXULarB2G+7hnWzVT52/2E9kxqtjuLwfC49YQe++vtJbcZ/O2m/aceMs/mXgA6Zxs07fyklSWY=,iv:XML744RQD0fht2+ch1WN0bVcMS6n1H7qjWTz4s8clb8=,tag:sE4wRrguTCTxQNN9YBdaCQ==,type:str]
    SYNCTHING_API_KEY: ENC[AES256_GCM,data:GRgvpuYMdD/ldzKQ5uRx+7crCtsAw156Rud4M5vGRsZla9IRRD9xnt/sGEqMWnySmnXeIuak3tbmp+Un3iVqZw==,iv:7rAyIZcoLGXcX9qF5jQ5Z+U0iqFy6fvsvDPVifATOZ4=,tag:+wurYC5pfj5tj8mQPRVq6g==,type:str]
    LLDAP_VHOST: ENC[AES256_GCM,data:y7W0znkC2BscxwEQig+YPj49Ow==,iv:4t6L/g0BpfZOwMcucLEOKDtIPh0a5bF/jBbkh+3nHBE=,tag:FYDw1fDER/28DT5T2hLS0Q==,type:str]
    GW_PUBLIC_IPV6: ENC[AES256_GCM,data:x7Hpvfs/waGjlyjXjYLEdL2mZlJc,iv:6n8fidiMdObYIQruOfoYQ8kN7vF9hs2k540eVhqjT44=,tag:Gk6AB9XNrF4RmrLKzCRMwQ==,type:str]
    GW_PUBLIC_IPV4: ENC[AES256_GCM,data:clhefdaVn9lVbA==,iv:bLUCo5fdYSg9HQncpz332xpY03KKZwEkp5GJ6l88NHQ=,tag:FOK8j5ysGfJMiCU5b7vdOg==,type:str]
    HTTP2136_VHOST: ENC[AES256_GCM,data:etbef8JtJYnEHLYH1RvzngxRi3zxZg==,iv:0uAxJkwmpLf/ovDHLA2zT+a2J1CLlGWpk91nFtvqOs4=,tag:RCRIg5PB1MXZSqwWpPaq3A==,type:str]
    HTTP2136_TOKEN: ENC[AES256_GCM,data:fBV4M8pGclSTlcWJpfSOgaJE/KwYvdT4wAgg23bmsJQqEr5w,iv:DcaYKtfv/9BOhnCnVGPeAER12cy4Q2Y69DAxl9O6Spo=,tag:crnaYP+JOdgsfM3v7Hem0Q==,type:str]
    WG_IPV6: ENC[AES256_GCM,data:tVPNFJP8b/OwjMl7tM8XycRodbK4,iv:A/K4vhicWAz7kxeAB5jDKPumorhpQ8PUJyRNh3gMV88=,tag:5+LxTe5SDrdxM/NJJBby3Q==,type:str]
    WG_IPV4: ENC[AES256_GCM,data:TfbdnGIQRoJzRa8TtIS3,iv:98cHJZThMWaEU0pK0Qgij2OWVVbzAXwLlJGLRvY+k5E=,tag:Sb72VaSjH5Uenz2Al8y43w==,type:str]
    NTFY_SACHA_PASSWORD: ENC[AES256_GCM,data:ULnZHQ46d3DNuIHh5IGM14ZJydVSg4VZ6zwlhuj0XbY=,iv:0qoSIAGvQmMpGd4lGH+jUD2f8uybYtNM0AOY8lxTwzM=,tag:GDB/rFabvIAlalpiQywHrw==,type:str]
    NTFY_SACHA_PASSWORD_HASH: ENC[AES256_GCM,data:GPAYMjTVECYwTABBt75pc0Is3/w79CWDHcSpxaY6C3WdRQr+HpNpedcrbFClNa71JgI/+VQzdscDwnff,iv:EvuFUNVpL12tR/PEEf0pcCNY7nFUVdTy3csQdNXkJzQ=,tag:RsIhXgdagrKYeZo60Lu5ag==,type:str]
    NTFY_KUMA_PASSWORD_HASH: ENC[AES256_GCM,data:cUgo8R5bYWcbFNzBBzGpgwl4SsJvu3YM+tUvf75ZVLhp84B+vORiOp1ZGaL/0bdHWvsQzBMR/MJCInQ2,iv:e1g/8SpYwBXphIx0crFYULGSmmh6Z087k7JXLk+US7I=,tag:DnhkpB5zMzih/SUFxAmk+g==,type:str]
    NTFY_KUMA_TOKEN: ENC[AES256_GCM,data:MJAY3TR9VvXPoYak9QuFguDSBulHs8eloAPxtMNIjkU=,iv:yPZuoQLAXSW/WNuNrAGj/8WfiGeysq7Q6fuScasIUrg=,tag:mQvwWPcetfPTFcoJK1af8Q==,type:str]
    NTFY_TOPIC: ENC[AES256_GCM,data:A7tm+V+w81Cs2J0lXhxTxSAFwf+UkTfbKwenWMPgkxuwais=,iv:cPlYpoU1H2nHYO0fBQuNLItGJP1rQ3N/+yCQ4ehINoQ=,tag:MUh/HqwsTIp17WNnYaxJGg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU2FqUERQR0x2VW9BVEdB
            RUxmQ1drSVZMVVBDWHQwVEd0N0hxWklqQUFnCjE4Q0lncG0yZWVadncrYkxMNnVj
            NjY2VmQxcmVXZXRHbXVmdEpYV2gzckkKLS0tIEs5dDhzK0RMdjhiNlZ1MWdJRVQy
            Mm5xQWdVMEQ4YjV0YTVLZE9UdWVJRkEKHX2/wzTpG82lMaj8raF1Vm8Tarc+MoRk
            j9rntN9ogzfz2YEhchNu6PsGHCky6US+XeJ0mbnsvivJrqwaCRYRJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-01T19:08:02Z"
    mac: ENC[AES256_GCM,data:lkmoBdpLFGhoFjJNVqvhF04IY6v2/edGGgDhBWw8mhUfzrGTQdFRmqR0alZelxkulSefg8DqbmdoM4Q3nng6hNrJ7MUuxnun82lnReMm71ytKI5ki8hm3D1gzVBc1WiNdMeX3NzXgyht9aiLLHwi1wGgaVr5kGqTQXMPPDO5PPw=,iv:J0Qv+Jf1x0X6AyiTC1PPGoX/l66FMcxNGaFs1VNyLvI=,tag:hdMD5bo8Iyv4oUJwR6v0zw==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdAAXfn2CbMLzXPhPeJkzBLJezJHcDWkxvBDwA0aL3inFgw
            Szf+T+lyA0DyjS/SLirwrD4Pd5i5usmkUh5JootxIPN3eBJpxFTWH6QThqRNnVB2
            0l4BWxozuw69iUzRuqNIpbYt8IWn2chVi8gWZx1YS7NiYL+DBsPOED3FlMTGI+7y
            UdBHTYkpSmTrYCe7HJUq89WJmGLFgHtHPJqi877LKMyW9eUQe6RAzbfVz8E9TCHu
            =ZuBM
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    version: 3.13.3
