---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: vaultwarden-backup
spec:
  sourcePVC: vaultwarden
  trigger:
    schedule: "20 * * * *"
  restic:
    pruneIntervalDays: 1
    repository: restic-config
    retain:
      hourly: 4
      daily: 5
      weekly: 1
      monthly: 1
      yearly: 1
    copyMethod: Clone
    volumeSnapshotClassName: csi-rbdplugin-snapclass

