---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 1m
  chart:
    spec:
      chart: vaultwarden
      version: 0.22.6
      sourceRef:
        kind: HelmRepository
        name: guerzon-vaultwarden
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 1
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    domain: "https://pass.s.tremoureux.fr"
    image:
      repository: timshel/vaultwarden
      tag: 1.30.5-4
    websocket:
      address: '::'
    rocket:
      address: '::'
