---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vaultwarden
  annotations:
    cert-manager.io/cluster-issuer: "acme-http-nginx"
spec:
  ingressClassName: nginx
  tls:
    -
      secretName: vaultwarden-cert
      hosts:
        - pass.s.tremoureux.fr
  rules:
  -
    host: pass.s.tremoureux.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vaultwarden
            port:
              number: 80
