---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: passwords
resources:
  - storage.yaml
  - service.yaml
  - ingress.yaml
  - oidc.sops.yaml
  - deployment.yaml
