---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: auth-cert
spec:
  secretName: auth-cert
  dnsNames:
    - auth.home.tremoureux.fr
  issuerRef:
    name: acme
    kind: ClusterIssuer
    group: cert-manager.io
