---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authelia-redis
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
    remediation:
      remediateLastFailure: true
      retries: 5
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    architecture: standalone
    auth:
      existingSecret: authelia-secrets
      existingSecretPasswordKey: authelia-redis-password
    master:
      persistence:
        enabled: true
        existingClaim: authelia-redis
    replica:
      persistence:
        existingClaim: authelia-redis-replica
    volumePermissions:
      enabled: true
