apiVersion: apps/v1
kind: Deployment
metadata:
  name: recyclarr
  labels:
    app: recyclarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recyclarr
  template:
    metadata:
      labels:
        app: recyclarr
    spec:
      containers:
        - name: recyclarr
          image: ghcr.io/recyclarr/recyclarr:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: Etc/UTC
          ports:
            - containerPort: 8191
          volumeMounts:
            - name: recyclarr-config
              mountPath: /config
      volumes:
        - name: recyclarr-config
          persistentVolumeClaim:
            claimName: recyclarr-config
