apiVersion: ENC[AES256_GCM,data:jsk=,iv:dAZaWHDWcRMIIBcfMJInFEE0QRbcfZ9vnV7m7tO3vx8=,tag:SS8sNrWNItxvg+71ZsqEnw==,type:str]
kind: ENC[AES256_GCM,data:2IRSY2iN,iv:95sARQcG730ugbyiZ1PDxhElXZr6mQ5/UMEwTK7lkVU=,tag:ZgbC4qT32rJKWWVDZiR2Bg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:34jTvSUveL88NfRP9A==,iv:usdykmtAoHpD/ChryUNeyKvO+Da3cnhXahv79JuLf9M=,tag:ZU9Hk7IRHSgRBfUxTUbFxQ==,type:str]
    namespace: ENC[AES256_GCM,data:wZgkcrQ=,iv:3KK//linut9r1pOKOKW558YS+GVUUOVNdI+gvWuPjwM=,tag:1OKeAQtNo7kJ4Nvu5MusLA==,type:str]
type: ENC[AES256_GCM,data:+o6SiVBl,iv:8CMFG+Ir7A4tTA/YgfY1PM2Mu0y1F9yeIVzl/mVk1RA=,tag:9roJc+H1X8dXEP4I/mJ9Cw==,type:str]
stringData:
    mongodb-root-password: ENC[AES256_GCM,data:7kvBMnI/+KqzxP2q63uuKbItceKCHlsY,iv:Gc4T0QxEupUsTj0qu8Yx8KsNaNP688kCn1J3+Xtz6G4=,tag:ALxPPoa1OxQmmEc+azxiKA==,type:str]
    mongodb-user: ENC[AES256_GCM,data:FrnzpNo=,iv:2IxrRsi602szIcZlS68/UURiN+5httI8rY3NedUidn4=,tag:6wDhSlakc3+W6vlFs5VyTg==,type:str]
    mongodb-password: ENC[AES256_GCM,data:hznbWDg5ofQGNWRyD92vAyNDBTajT9BD,iv:LNHpOCS3t7RFdzlNyKUJJAP/sV33f53xSoko0m8+zu8=,tag:xcCNeVm7UBDieHOOO+pICQ==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEN01KaHc1NGNrSU9zYTc3
            aHlZVXlVK2JnSzMvOWRnc3kyMHBQeDNnZ2l3CkdtaWVEWEY2ZXQwS1BjbCtMS05x
            cXZpSERObTlEZXZ1cGJLVGE1VDlrd1EKLS0tIHFERE92ZFczWDRSdWQ3SENoWHdx
            ZDRXMXVOM1kwaEs3N3BXYjdlNkJGazgKTWBV+oW6FbFICtaK2ojDyRKXFtL0QF2y
            ADj7ApYFuucyp/3aWk9faaP4szIs+mWQHIA1/pFDPclb2TRe4Mft/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-24T17:58:09Z"
    mac: ENC[AES256_GCM,data:h72gRQEIRKOiTN7Xd/HYsDOAlUEyGWwv7bZm8ile/UqaSfFXA+ti03xopSvhH9dmPJdiGwwz38+XpLYXImg4jD4660rAHE1LyFpAIu1rtmzVqJz5t4k2R2rSCVRw4ehJRjLDUtfiCh+LYMDh9tasq8ZOeJrXhz1UrbnsLto1DG8=,iv:wHQ/fFzTMlSHXg8tI2qj4x6EwwhUgZ7LsnFbD+rJipA=,tag:t3mdHjAevfE0487yVGvhtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
