apiVersion: v1
kind: Namespace
metadata:
  name: unifi
  annotations:
    volsync.backube/privileged-movers: "true"
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi
  namespace: unifi
spec:
  interval: 5m0s
  chart:
    spec:
      chart: ./charts/home-unifi
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: unifi-values
