wildcard_domain: ENC[AES256_GCM,data:l/bYcarpo9UfYJWz5M0wAZUe,iv:RFdbzFaqptwPll1WE2eRt1ABQNPUl4uOeFe7pcWzYLk=,tag:yUjJNgcu0DBHyi0b8Fkprw==,type:str]
gw:
    ip: ENC[AES256_GCM,data:+bfgabALO6srlOabDzZCXPpYM+TV,iv:JVNMaDxocprCejp1lN5fJuJ/8LhpHVw1IR2LSJ+tOgc=,tag:OfYqyLPl7nl4PXrgSSXm+w==,type:str]
lb:
    ip: ENC[AES256_GCM,data:rz437wlGJb8peaG+Czn8Cy1t9lrQbIKYM6S1ovYtNhE=,iv:iMGkurqGAZD58rnu9Y6Kz6DkbswpaUR4VnpF056gF2k=,tag:OrH+ReF0kFs0NWehysheCQ==,type:str]
backup:
    ak: ENC[AES256_GCM,data:sxzECYyEgAjyY+nN3+0xTJv+KwmwNvVd2zGX/DAq1dY=,iv:rrOjWv6vSChvw10LasIlc8qwLI8J/FIM9IFKnD/VZWU=,tag:1ABM0Rl7Xu5O/MUgQNjTPQ==,type:str]
    sk: ENC[AES256_GCM,data:jZwS/VFep+oshmQNlw3ifFlEDd3u5LVHkHL6yNlGOPA=,iv:99ZCQe9QfpE/6PuWp7QO4jpUK3P961OtI+UQ3nCRgqk=,tag:jP31F9JHDDNDriyFgWRjoA==,type:str]
    restic: ENC[AES256_GCM,data:T+svXqrRXdpxGykXlSHbQ9r9YShYc4U5,iv:o1VYizO7jpQyMv9m3Z6WLecr9hxwCGEADZ7JiAh8zXo=,tag:Q+e0f0Dwwut4fMFjRZNKlQ==,type:str]
    endpoint: ENC[AES256_GCM,data:mqcbJfyoDSNLg0orPhoFkf/g8Eb/VSCxVrG27a7PtQ==,iv:DoOS6KnjINlUH13bHqamxttOusRTcz6tcQxaUE6CHyY=,tag:NcDnuhq+3TLKUdOFckd/og==,type:str]
    bucket: ENC[AES256_GCM,data:ngCzY1ZMMhVKSCdN0nlRTT0=,iv:HIXjNroYSgqunNMV7bsIUpCvnJzh77Nzu1YWTNm05Kc=,tag:fWUXNBs5dZ1Pjn6Av1aNHg==,type:str]
uos:
    system_ip: ENC[AES256_GCM,data:qWYi2/UwipIIUg==,iv:Z5Rmw3BbX9Wu+3hI8nsZqPEsN6JlAslj/sVLB7vKpak=,tag:NfflaM0FwtB4/G32a3Rj5A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIRGJKOWM1RXNlb0hyZVZa
            WlRreFFpOGdsT25nbThQcHFGMDdwVGZ2WEg0CklOSWlVU01oKzYxMU5TR0JSbVBF
            cTRNOGtYNk9GWVZtNjZGY1pPVGpnMHcKLS0tIGNZNkJ0UElTdlpxK3BKc3ZsYjlG
            M0RzKysxNnZRL0ZzOFFROEFPWFRCL2sK20L86WF3fg73wCDcP1w/hp5iA8+bS4WJ
            mg6831f2VVo7JpWUQ8/fW/kL6sdI/E68hZVAIyakCwu80nyUlL60dQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-07-19T21:57:08Z"
    mac: ENC[AES256_GCM,data:7jURm8ZPemng/H4uK/OzWyafPDQH+Mof3gCY3xrSLew5MqetqfJHCwLZHdFPVKrIVmahgoforjwICLcI/dnzTzWwJZczd+U9JL5sCl9FsxZeccjR+RJHWTWMuC1Jib3Hx1DIEUGocpN5GTZxDbc1UbSo3P/pj5oo8ujPwUn4Dp4=,iv:Nmx9xzOVK+TIwIQ6n2lt3/FADFFsff+6gPPTUBPHzNE=,tag:zAO5NGlXx/fOEs0Ur7rEAA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
