---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-web
  annotations:
    cert-manager.io/cluster-issuer: "acme"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  -
    host: grafana.home.tremoureux.fr
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 80
