apiVersion: v1
data:
    api_url: ENC[AES256_GCM,data:Jjbn650KtUUtLt+YbhQBoo1qdy5UldH0TBIT5678Q8S2yPeF0SoZnab+xyLSBaN2cCYpEgqbFfjtEWbpBx6jX3VebIE=,iv:zPLqcFH2hzjoHuVGeUktV0GUZMecK+VnnXu+1TYQETI=,tag:oXtD0lWvRBG7tkwZcfSnqw==,type:str]
    auth_url: ENC[AES256_GCM,data:pklno7ZS6ybwOVMohqXzcLxX6cOUodaFBm4Mhvcj4wIMbTwYJPXbH4kaj1XEFEG2IhAxp3/RhU6gBP6+3yKgLWq8GjR8B1Tx,iv:SYbZeR5kYKX8hfxQVXqawCsngAofwbPpufaXryfLob8=,tag:oRuYEVE5myziwWpUuzbJNg==,type:str]
    grafana_id: ENC[AES256_GCM,data:xJI/DOLfUmmvlB9q,iv:wOGjYCSB9thptwyGoaqfumB+EMvWg2RRwTuc3yriYpE=,tag:VmAOxKPQT7sU9kEk5Ww3Fw==,type:str]
    grafana_secret: ENC[AES256_GCM,data:hqWZuQIRZKORxQzQ,iv:pxuKu6uaV8q2v3Hg6rnXOGVb08NXYrxgdZSKskBhVb4=,tag:i2IgIcf9aGVUC8SWTxrgHA==,type:str]
    token_url: ENC[AES256_GCM,data:cqgCZP11U/oYUXGJ9PxQXNn2vpzU0ssgnB1UYFE9TjVuzCV1wI17JnMFHWmCdv6QE3cSiEvjUNQReZ0nIdEABQ==,iv:BiXj5GKkhaJEWcMFUbRToeTszz1CaYJL78BIJbPxDAs=,tag:P/0+eg7PAyHKvXtIYc09gg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-secrets
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1g7ehhg7p0xsxnsdggen9plw5p20rxs89pdy3fmwafr84dh4qdylstwad7z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYVQ2eXBmejEzOHhOajhh
            TkluQ0tzVHllUE9yOWpmOHRkVFVJUG50aTIwCnlyZ3Z2QkgrRkUyaVRRd3lMRXBo
            QXBuRHZGYS91MElpUmdwTzhUd1JoaVEKLS0tIHEvWGNmWWFwSy80akt6RDFsQWNX
            K096T2o0dTRCRHVPSEFVTG1SMmpZYzQKDbqoaiM3E9hbkROZifE3PyUcMBU8Zpsh
            00hJx1tEvk0wMpK4WAqG1IOA8p3gCj6v7VBICNO6XOvCGh11tqK4Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-17T22:21:39Z"
    mac: ENC[AES256_GCM,data:6AAmuGWmwnLLlJr58bDSAsJ1/SvXpskSq71DZ/bhu+ZQHoDLvIysOWsmBFBVk51EADknplOyZD1q6A5vh5s/BMZyy6tA1J1WUdQHSHZqyMWskC2l6aGn9sZTVQ1TbmKfpTlg4XrTtVidAbAQAlWus5i3vEMAnaC3xRLbXzVSJ5M=,iv:mhGDRZ/bcM9KrYwjh7FVyXczh9pec6gcfhWHa5Po6Jc=,tag:lnRd5QLv8wLs/E5VqG3H9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
