apiVersion: v1
kind: Secret
metadata:
  name: dns
type: Opaque
stringData:
  http2136-token: "{{ .Values.dns.http2136_token }}"
  rndc.key: |
    key "rndc-key" {
            algorithm hmac-sha256;
            secret "{{ .Values.dns.rndc_key }}";
    };
