apiVersion: v1alpha1
kind: TimeSyncConfig
ntp:
  servers:
    - ${NTP6}
---
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  rotate-server-certificates: "true"
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
$patch: delete
---
apiVersion: v1alpha1
kind: DiscoveryIdentityConfig
$patch: delete
