machine:
  certSANs:
    - ${GW_FQDN}
    - ${WG_HOST6}
---
# Recreate KubeNodeConfig without the control-plane taint.
apiVersion: v1alpha1
kind: KubeNodeConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  node-role.kubernetes.io/control-plane: ""
nodeIP:
  validSubnets:
    - ${GW_ADDR6}/128
    - ${GW_ADDR4}/32
---
apiVersion: v1alpha1
kind: KubeFlannelCNIConfig
$patch: delete
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
podSubnets:
  - ${POD_CIDR6}
  - ${POD_CIDR4}
serviceSubnets:
  - ${SVC_CIDR6}
  - ${SVC_CIDR4}
---
apiVersion: v1alpha1
kind: KubeAPIServerConfig
certExtraSANs:
  - ${GW_FQDN}
