cluster:
  etcd:
    # Never on the public IP.
    listenSubnets:
      - ${WG_SUBNET6}
    advertisedSubnets:
      - ${WG_SUBNET6}
---
apiVersion: v1alpha1
kind: KubeProxyConfig
enabled: false
---
apiVersion: v1alpha1
kind: KubeControllerManagerConfig
extraArgs:
  allocate-node-cidrs: "false"
