apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/hcloud-installer/${SCHEMATIC_ID}:${TALOS_VERSION}
provisioning:
  diskSelector:
    match: disk.dev_path == "${GW_INSTALL_DISK}" || "${GW_INSTALL_DISK}" in disk.symlinks
  wipe: false
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: gw
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: ${GW_ADDR6}
hostnames:
  - ${GW_FQDN}
