apiVersion: v1alpha1
kind: UnattendedInstallConfig
installer:
  image: factory.talos.dev/hcloud-installer/${SCHEMATIC_ID}:${TALOS_VERSION}
provisioning:
  diskSelector:
    match: disk.dev_path == "${GW_INSTALL_DISK}" || "${GW_INSTALL_DISK}" in disk.symlinks
  wipe: false
---
apiVersion: v1alpha1
kind: StaticHostConfig
name: ${GW_ADDR6}
hostnames:
  - ${GW_FQDN}
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: gw
---
apiVersion: v1alpha1
kind: LinkAliasConfig
name: ethSel0
selector:
  match: link.type == 1
---
apiVersion: v1alpha1
kind: DHCPv4Config
name: ethSel0
---
apiVersion: v1alpha1
kind: LinkConfig
name: ethSel0
addresses:
  - address: ${GW_ADDR6}/64
routes:
  - gateway: fe80::1
---
apiVersion: v1alpha1
kind: WireguardConfig
name: wg0
privateKey: ${WG_PRIVATEKEY}
listenPort: ${WG_LISTEN_PORT}
peers:
  - publicKey: ${WG_PEER_PUBLICKEY}
    allowedIPs: ${WG_ALLOWED}
mtu: ${WG_MTU}
addresses:
  - address: ${WG_ADDR6}
  - address: ${WG_ADDR4}
routes: ${WG_ROUTES}
---
apiVersion: v1alpha1
kind: NetworkDefaultActionConfig
ingress: block
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: apid
portSelector: { ports: [50000], protocol: tcp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: trustd
portSelector: { ports: [50001], protocol: tcp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kube-apiserver
portSelector: { ports: [6443], protocol: tcp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: kubelet
portSelector: { ports: [10250], protocol: tcp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: ldaps
portSelector: { ports: [636], protocol: tcp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: ldaps-cluster
portSelector: { ports: [636], protocol: tcp }
ingress:
  - subnet: ${POD_CIDR6}
  - subnet: ${POD_CIDR4}
  - subnet: ${HOME_POD_CIDR6}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: etcd
portSelector: { ports: [2379, 2380], protocol: tcp }
ingress:
  - subnet: ${WG_SUBNET6}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: wireguard
portSelector:
  ports:
    - ${WG_LISTEN_PORT}
  protocol: udp
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: cilium-vxlan
portSelector: { ports: [8472], protocol: udp }
ingress: ${FW_TRUSTED}
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: http-public
portSelector: { ports: [80, 443], protocol: tcp }
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: dns-udp
portSelector: { ports: [53], protocol: udp }
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
---
apiVersion: v1alpha1
kind: NetworkRuleConfig
name: dns-tcp
portSelector: { ports: [53], protocol: tcp }
ingress:
  - subnet: 0.0.0.0/0
  - subnet: ::/0
