# Nameservers and NTP come from DHCP.
apiVersion: v1alpha1
kind: KubeletConfig
extraArgs:
  # Needs kubelet-serving-cert-approver, deployed in clusters/gw/infra.
  rotate-server-certificates: "true"
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
$patch: delete
---
apiVersion: v1alpha1
kind: DiscoveryIdentityConfig
$patch: delete
