---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-crds
  namespace: flux-system
spec:
  interval: 5m0s
  timeout: 3m0s
  retryInterval: 1m0s
  path: ./k8s/apps/monitoring/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-kube-prometheus-stack
#  namespace: flux-system
#spec:
#  interval: 5m0s
#  timeout: 3m0s
#  retryInterval: 1m0s
#  path: ./k8s/apps/monitoring/kube-prometheus-stack
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  dependsOn:
#    - name: monitoring-crds
#
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: monitoring-grafana
#  namespace: flux-system
#spec:
#  interval: 5m0s
#  timeout: 3m0s
#  retryInterval: 1m0s
#  path: ./k8s/apps/monitoring/grafana
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#    namespace: flux-system
#  dependsOn:
#    - name: monitoring-crds
#  decryption:
#    provider: sops
#    secretRef:
#      name: sops-age
