cluster-init: ENC[AES256_GCM,data:5AX5TA==,iv:Wq0+Jj67FJZ+9chRImyQcRVGG0eesyIQso0Gm2iDGp4=,tag:R8Z27eYudwhTNTeSAKFFtQ==,type:bool]
flannel-backend: ENC[AES256_GCM,data:h2wMjw==,iv:ssITwJIpB7vZmiPZi67AjzGjT4on3NZlXETSNvkNmQk=,tag:bW9dyz+H5FsxdddEbQV7zA==,type:str]
disable-kube-proxy: ENC[AES256_GCM,data:+JmV4Q==,iv:kN4zZsfQTF8ov2iByj+H88NjIO3Qg+h7tjPiq2E4LmU=,tag:h6O2J/hYipIpxujlj5PXzA==,type:bool]
disable-network-policy: ENC[AES256_GCM,data:D5ACfA==,iv:cnis607F7UMq95xn0OWm117WDifdXpmsu6+gcdko2E4=,tag:09wOB/HZLvrw+/zg46dcTg==,type:bool]
disable:
    - ENC[AES256_GCM,data:cdKN2VMpkw==,iv:58cdVUELwovadu3zcVZXuZz9B02F8QrStgy92IUtoqk=,tag:MjllUtqvcmb92+1YKfqwNA==,type:str]
    - ENC[AES256_GCM,data:mfCbe0Ig/w5J,iv:CugvCjpHH2C+bBvl9s08C04C0uCpyapC36AidIgNX0Y=,tag:+aK3diHbTBSyrsxv3eqlHw==,type:str]
    - ENC[AES256_GCM,data:5TUeZ5W0SRUuKVgA6bg=,iv:aB4AjHnDSltvIK+OkLj7554XagGD+y9PY/NFxVMocxE=,tag:zQHvQChB4jMs+lYLpaVioQ==,type:str]
tls-san:
    - ENC[AES256_GCM,data:k4ysO2syzNJlcYD/1755SQ==,iv:rPu0Xoq6yUUkHdeA1itYHd6zfmzNG6q+Cy1OZjosXF0=,tag:eIuT/IeHs0U4AJFWx51Ehg==,type:str]
cluster-cidr:
    - ENC[AES256_GCM,data:jtgCidiofFOXjUb7,iv:scZA5OKDyMCfwh4HVJtIN3yWpw8nq8FMHioZSiDaoBM=,tag:i4z56CWr0aA++yzaPG8ECg==,type:str]
    - ENC[AES256_GCM,data:tgtv5H8JCQvDBpfNYfk5z73ETQ==,iv:8bt9l5WbfhQXFO/Xq3NBAwmm+pdXjUKf8ogxJS3/HPo=,tag:YfsF7t+n4izCxpk4vTdDiw==,type:str]
service-cidr:
    - ENC[AES256_GCM,data:RY29fUfwkLA5guj2,iv:/Y4xAfcz6DVhrctOtP1ovpir91o6Sogb0tH5bPVb86E=,tag:jWCIRXqYIV/YmEEvtSlV4Q==,type:str]
    - ENC[AES256_GCM,data:vKm5SWtEKoW38aVs1S/P+uTNJKzsUUTmAw==,iv:ORVN4+jdVouM9u2ok/aRPrx3O1BKZgs+ss9NyQ15qFQ=,tag:oxD4Agk/K8cA7q9h+6VN6w==,type:str]
sops:
    lastmodified: "2025-05-19T16:58:28Z"
    mac: ENC[AES256_GCM,data:j4B6EN0wvW9K24/m3Vn862p17jSda+ReAjJk0IP11av2VaMBhgsrUvk3aTd8rQkMA1kLqgpIsUj9aLvKxYR3AkH88jzBoNZRlfJpI/2aGe4NUonKOQM8we3XS2MW9bBNdH8NrN6oj49gGUHb8jdsu7cQSUE7VGg1dx/kUL7Tp8E=,iv:Fl3HrdZolpK0Oii4j/hFYDRWVnZSrH/okCPLC3c6JFw=,tag:EmliP+fAH0p2UlXjlsUrww==,type:str]
    pgp:
        - created_at: "2025-05-19T16:58:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdAr8QTFCa0I9hoF2XEgi56VXC7Xr5pnCfN/jvNDlcpmnsw
            zhBA7+/PzvZ4eVQ3h1KoVsprJ54dwp+CxwgdZE2XsPvn/9Uh+0G/KTHSFJgNbbeE
            1GYBCQIQDmTyP45nNhuvn25e+SFJ4GRIcst0O257q7z6SrFmJPRqzofd2Gl2nlYr
            PdBKHD675BH4z/GbStttclmOfHyfnKdKAtkqIbBhYYHdGaiSehmwC7i//PXo621y
            iCnYICfgLd8=
            =aGEM
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    unencrypted_suffix: _unencrypted
    version: 3.10.2
