# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/part-of: apps
resources:
  - namespace.yaml
  - certificate.yaml
  - gateway.yaml
  - http-redirect.yaml
  - papra.yaml
  - syncthing.yaml
  - syncthing-discovery.yaml
