apiVersion: gateway.networking.k8s.io/v1
kind: ListenerSet
metadata:
  name: syncthing
spec:
  parentRef:
    name: gw-private
    namespace: gateway
  listeners:
    - name: bep
      protocol: TCP
      port: 22000
    - name: quic
      protocol: UDP
      port: 22000
    - name: discovery
      protocol: TCP
      port: 8443
