# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - home-media.yaml
secretGenerator:
  - name: media-values
    namespace: media
    files:
      - values.yaml=values.sops.yaml
generatorOptions:
  disableNameSuffixHash: true
