wildcard_domain: ENC[AES256_GCM,data:Mjjz5XvqJcWIX4fo+keEeaJi,iv:DZFg7sUu2faQNRzuM5f6WzQersjgHAWHymBzeq0yK9M=,tag:s8/1/cKdHO+oFa9MuEbw7g==,type:str]
gw:
    ip: ENC[AES256_GCM,data:2ZyskGU+n4/nqAxqE9gF2d7hu6Zp,iv:A3yFK2loxcPxElqLIH/KkQpGKp8CG5KoIoCNjFRkTVM=,tag:wjNcV1FA5IZS/IXlJBcexg==,type:str]
sync:
    seedbox_host: ENC[AES256_GCM,data:9T1orkxu7a/BaGM7A+aYKDMeug==,iv:BlZ7WjJ0icLO1j8ABBsK0sK2u62/Nq3p8QJh5PlryFc=,tag:75gPvsL9fFlmCa04LUhgVw==,type:str]
    seedbox_user: ENC[AES256_GCM,data:jSyCjufYfQ==,iv:mAixVhn35S4MYQ10GM/I9fWnJ6x2wv2w3CbAj6JEQr4=,tag:sN4UK/a71ycQ4sQSeXFWCw==,type:str]
    ssh_pubkey: ENC[AES256_GCM,data:UkrCOu/aTyyuTbaDxI936hXw7FhKLLW5Oi1uS82VTcKTqlsuIFzo6LjjlBejEqhoW4VPMqMks/2VKUXBnSmdLsK0Wd/iAgBjZpjD7MBd5gHSodNKSt+zoJus,iv:2qxVvx0fG3ySqC7ksx2o8zyKUbXNp4lcX5O7Co81l+I=,tag:OvEdM5n24E7ymSgmMqMjLA==,type:str]
    ssh_key: ENC[AES256_GCM,data:U4kFFaS7D2iyFOD/KKPophQBugSuT0vRRRjPklElkweUW0D8fL022d309OlVcMr1vCXCNWXOJzJfL8hogP8jAPsYpUsWbPxOAj5Wj7eRAWi32M6c9Dg2OQUs6HRbXPDlrHZamn1z+K/nnm0VQ+JGXkImen6aWCEVnGOTHO+6LRQtpmc5NSYVqoP+PLnklqN9Vuhz7IPS6lCL99ndpsOEyIcWn1pvtbAPsTT3/ntAfC9fp1ofcnl/FbTIBKbPWRPO/9oD5A2TU9E4iQcNipLm5GPf/Lv3xs9M3AyOC9FlBK+bzfUxXQa84xfJ42gDJBSo9jwVZ5taFqZTo1R6f4FG3SsAUKy8s5aVStSgOP8k+MG7fZJRjPmSOvD++L+tKk2U8BOQxXKClJbYH0zDRrY+Knoz6xf7P8lHPQkpohu8GBcLpvzQf7j5Pi/fOWcId1kNiBekq/EuHm1DJqTf8gQM2QRDGb2u3PI36hggeJsrtelBk7HNYTyzVisKOPTbRHFQiaEGeMuwbjUb4cDs0+ktjiGtihcf7XBbd3LG,iv:6IrPxoZkK1nKkL+7oGBKp/ddnmOjHk28mUWNlolqrsc=,tag:lwX+y4BAmxiqeSyqlJ9wew==,type:str]
backup:
    ak: ENC[AES256_GCM,data:9lMLP5GLsRw49IVKSyjbsbe331C7bNJ9ErCMruFo+Pg=,iv:pktkutmA0IQcFBeAMk/fr94mEiLvKCYTpv5MRqwYggo=,tag:FKuj1uywd74CzYcHygp8jA==,type:str]
    sk: ENC[AES256_GCM,data:GGfIJHoJ2hE9rzf31tuPI3BjvE0XVkTOAv+Fvk4Zt3Q=,iv:lcH5qphHMSJOCKyJZGVoCM7BEYK1/Fu+s2E/mNw/z44=,tag:kCpCRQLDrdyDiWUhcsihtA==,type:str]
    restic: ENC[AES256_GCM,data:Lrs11o0luCdw8cJ4WYpIH10gqDNmfH43,iv:AsXP0CzfFAVIUqDVYkcwwvMUZAq+Rz2aBV5pWPP4v1I=,tag:BEI3YuDoa3HZL8Dzlnuf5w==,type:str]
    endpoint: ENC[AES256_GCM,data:Gmn2EkBAZ+Up1YzTA3DgtcjQhMI75gdkTwEx2treTg==,iv:sZTo8GtXKQBLFqVIK/e6S2vAxCXC1VPbU1ndPPyCWiA=,tag:/nnewywuKpVWUWDnU95WJg==,type:str]
    bucket: ENC[AES256_GCM,data:FGrp5V4SyiX+c3/ESK4rOjg=,iv:984k3fkCKzEaxb5CYZGiB3+xpjgCMH/XZ/ZXfYRljdE=,tag:UjstZyPNG9VAtBRIZd+N2g==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NGNmNVFEL1ZweFY5aUg4
            TXRwQklTaCs5TFdkS2pkVENQV1FuY3A0MzNnCjZGZE44QjZzUFJTNU1ZK3dONE9s
            RUY2c0VJTEJGOGpwazRMSHJqTE9oQlEKLS0tIEt6aWRpSGQyL3A4Y3FCcis3alN0
            VzhQUDhGbTlDMHAvWXA0VFZkVCs2eWcKgpn/cePFeO+jJ8JpX+DmoZZhmQXC55GF
            l4r9WQ+lnjx/0KTsOwQ6IW+7OudE7r52tKeFISjTaCV2DQMAtro9OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-18T14:32:18Z"
    mac: ENC[AES256_GCM,data:BEZ+LVtvSfuFufL3hJFJRYNLDLlYAGbAxngOCC8CfCBUXyBhIOu1JG9voneq2Cg1lcceNKiaH2wd/+Rwje4ZtUuajLmHOTkGG4kb7Tj4E9K42GKfpJ68BEBx77A34kbyZilZSN7egGFesu16/jUp3nxIRgO2ZTMyd+jshW09GCY=,iv:Olmmdc/djdcB5pPE87E9QRazznoYY3oKCIZX+67KerI=,tag:MdOyCkx5ffXf3MAweLN95A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
