apiVersion: cilium.io/v2
kind: CiliumBGPClusterConfig
metadata:
    name: cilium-bgp
spec:
    nodeSelector:
        matchLabels:
            kubernetes.io/os: linux
    bgpInstances:
        - name: to-router
          localASN: ENC[AES256_GCM,data:8JU8EKA=,iv:H5Au+mqHadhCN2CO2wiUSY+2nCB9VwOc3Wi5fMm20jo=,tag:9qj8wT/yX6gA2ZOx4j53Vg==,type:int]
          peers:
            - name: router6
              peerASN: ENC[AES256_GCM,data:eZnoDug=,iv:VYPZK7cBxlcYGOYfz2gKVVRnyS8UF+3iGbmYb83Qqbw=,tag:IdpnBFYMbz+V0Lua1+KXqw==,type:int]
              peerAddress: ENC[AES256_GCM,data:jtNUarfAzuH/TiQN1PDWNP5eFRVn,iv:qKPTsN87qD/hFpO/CZGi3XvVq++w72xeJmw/DP2FKEg=,tag:ZH85TNVah/dl8KMkXeTqVA==,type:str]
              peerConfigRef:
                name: cilium-peer
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2QxM0hrWWs3NFlFRFRy
            bFhUMXdlN1hwOVlsZ2VKZTNKdTJoTS9JRGo4CnlwWWJWb2h5a3FKOGJMWEFwd09P
            bDVnVG0rN0pOQUxUL2VUdFp0dms0ZFkKLS0tIEFXTC9TRy92dUtlUGlBOUZkcjBm
            aGExOEdJU25IWk5nZkZ6MVNmc0ZLeUEKmkUzWrC02Nzt8OhMmxsn63YGgXhw0PJh
            X/h+Qdewkvej7S3i6yFcaHYjkh23GI7oqgoz4luAPcnA177wLDtLzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:55:51Z"
    mac: ENC[AES256_GCM,data:b7wZ9lqXDlw+O3OxzBzIpS2bihdLUlc50lz3upzLcCylDYYl3DEdyEgr42bii5WbkCwQZsLritcW1CBWDoNC87OCxr1d//NcwFlxLJ3q+HWNoiIHg1ZIqXIEEAr+SaQTHvHP3vPSJFhXyw382LeqtYR/VjwzQC5j1GS+mJ/kRG8=,iv:bHWn5RC8ljDJAGusIGV0H80qtoJX4m772aqq0LZ1b4U=,tag:iBcUgObTeqYzGRd2vW3FZw==,type:str]
    encrypted_regex: ^(peerAddress|peerASN|localASN|password)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: bgp-auth-secret
    namespace: kube-system
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:gD2vRiyoLnFVWjbHCFeI0/cJuFLmVaTgNQvjHmAi9KNt/W8pV5cZNVQk+VQgm+QYkl4ZBfr5ruveyEm1xHNfGg==,iv:9LM49d2bxiexy4HjVkKrw8IbQH17MUSPfmheM3h0sm4=,tag:QV2/X4LNLZRtAjz15qhU9A==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2QxM0hrWWs3NFlFRFRy
            bFhUMXdlN1hwOVlsZ2VKZTNKdTJoTS9JRGo4CnlwWWJWb2h5a3FKOGJMWEFwd09P
            bDVnVG0rN0pOQUxUL2VUdFp0dms0ZFkKLS0tIEFXTC9TRy92dUtlUGlBOUZkcjBm
            aGExOEdJU25IWk5nZkZ6MVNmc0ZLeUEKmkUzWrC02Nzt8OhMmxsn63YGgXhw0PJh
            X/h+Qdewkvej7S3i6yFcaHYjkh23GI7oqgoz4luAPcnA177wLDtLzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:55:51Z"
    mac: ENC[AES256_GCM,data:b7wZ9lqXDlw+O3OxzBzIpS2bihdLUlc50lz3upzLcCylDYYl3DEdyEgr42bii5WbkCwQZsLritcW1CBWDoNC87OCxr1d//NcwFlxLJ3q+HWNoiIHg1ZIqXIEEAr+SaQTHvHP3vPSJFhXyw382LeqtYR/VjwzQC5j1GS+mJ/kRG8=,iv:bHWn5RC8ljDJAGusIGV0H80qtoJX4m772aqq0LZ1b4U=,tag:iBcUgObTeqYzGRd2vW3FZw==,type:str]
    encrypted_regex: ^(peerAddress|peerASN|localASN|password)$
    version: 3.10.2
---
apiVersion: cilium.io/v2
kind: CiliumBGPPeerConfig
metadata:
    name: cilium-peer
spec:
    authSecretRef: bgp-auth-secret
    families:
        - afi: ipv6
          safi: unicast
          advertisements:
            matchLabels:
                advertise: bgp
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2QxM0hrWWs3NFlFRFRy
            bFhUMXdlN1hwOVlsZ2VKZTNKdTJoTS9JRGo4CnlwWWJWb2h5a3FKOGJMWEFwd09P
            bDVnVG0rN0pOQUxUL2VUdFp0dms0ZFkKLS0tIEFXTC9TRy92dUtlUGlBOUZkcjBm
            aGExOEdJU25IWk5nZkZ6MVNmc0ZLeUEKmkUzWrC02Nzt8OhMmxsn63YGgXhw0PJh
            X/h+Qdewkvej7S3i6yFcaHYjkh23GI7oqgoz4luAPcnA177wLDtLzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:55:51Z"
    mac: ENC[AES256_GCM,data:b7wZ9lqXDlw+O3OxzBzIpS2bihdLUlc50lz3upzLcCylDYYl3DEdyEgr42bii5WbkCwQZsLritcW1CBWDoNC87OCxr1d//NcwFlxLJ3q+HWNoiIHg1ZIqXIEEAr+SaQTHvHP3vPSJFhXyw382LeqtYR/VjwzQC5j1GS+mJ/kRG8=,iv:bHWn5RC8ljDJAGusIGV0H80qtoJX4m772aqq0LZ1b4U=,tag:iBcUgObTeqYzGRd2vW3FZw==,type:str]
    encrypted_regex: ^(peerAddress|peerASN|localASN|password)$
    version: 3.10.2
---
apiVersion: cilium.io/v2
kind: CiliumBGPAdvertisement
metadata:
    name: bgp-advertisements
    labels:
        advertise: bgp
spec:
    advertisements:
        - advertisementType: PodCIDR
        - advertisementType: Service
          service:
            addresses:
                - LoadBalancerIP
          selector:
            matchExpressions:
                - key: somekey
                  operator: NotIn
                  values:
                    - never-used-value
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHM2QxM0hrWWs3NFlFRFRy
            bFhUMXdlN1hwOVlsZ2VKZTNKdTJoTS9JRGo4CnlwWWJWb2h5a3FKOGJMWEFwd09P
            bDVnVG0rN0pOQUxUL2VUdFp0dms0ZFkKLS0tIEFXTC9TRy92dUtlUGlBOUZkcjBm
            aGExOEdJU25IWk5nZkZ6MVNmc0ZLeUEKmkUzWrC02Nzt8OhMmxsn63YGgXhw0PJh
            X/h+Qdewkvej7S3i6yFcaHYjkh23GI7oqgoz4luAPcnA177wLDtLzQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:55:51Z"
    mac: ENC[AES256_GCM,data:b7wZ9lqXDlw+O3OxzBzIpS2bihdLUlc50lz3upzLcCylDYYl3DEdyEgr42bii5WbkCwQZsLritcW1CBWDoNC87OCxr1d//NcwFlxLJ3q+HWNoiIHg1ZIqXIEEAr+SaQTHvHP3vPSJFhXyw382LeqtYR/VjwzQC5j1GS+mJ/kRG8=,iv:bHWn5RC8ljDJAGusIGV0H80qtoJX4m772aqq0LZ1b4U=,tag:iBcUgObTeqYzGRd2vW3FZw==,type:str]
    encrypted_regex: ^(peerAddress|peerASN|localASN|password)$
    version: 3.10.2
