ipam:
    operator:
        clusterPoolIPv4PodCIDRList: ENC[AES256_GCM,data:/rh8GJQXEWMeY8jadA==,iv:jOASZn1S6iuM7w5U5vbx2mLVJBcoOf1JqrmOQcOEktk=,tag:6vMQ5YOcVLwPJOt8Gmdgzw==,type:str]
        clusterPoolIPv4MaskSize: ENC[AES256_GCM,data:CQs=,iv:3AXr1sRX6A40KWYTDG+/4AJ4ca8sLvtVcEKJq/R4Nkg=,tag:O+wxUlj0v3+giSV82Hlh9g==,type:int]
        clusterPoolIPv6PodCIDRList: ENC[AES256_GCM,data:1hQK2+ufvT6mveYpnRTbgY+Wyo4VjP0=,iv:tdjRvvOI/vwC4KyQEiX7yC+nlTfPkg6k+UPSOYNRI4g=,tag:zsu0PnFF0e4ZfbSFCda30A==,type:str]
        clusterPoolIPv6MaskSize: ENC[AES256_GCM,data:Jpk=,iv:qfwzfnt3mgu0NnkYGXanADtIN1MHgAsJg37yg42h5PY=,tag:PJ8rhnAjH3Bm65Yt4fBugw==,type:int]
ipv4NativeRoutingCIDR: ENC[AES256_GCM,data:FYbdz7RYge/qRYIX2Q==,iv:z86J3n4RfV38NB6ryqeUDsUngJH53YlwazmmsSSjakU=,tag:11bMU4v8mo6U2JRHABusdQ==,type:str]
ipv6NativeRoutingCIDR: ENC[AES256_GCM,data:/jQHdSDvt9MDxyoA2SEtAJsNKqSk5NI=,iv:1AyrmMgcEmuiGyoSoa32Z3AGBgQZcsv5faJkPp6tSKk=,tag:IUCQp8LG3MTUDAprMb477g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3RTJVY0s5a1VYMlJETlE2
            NnJaWmROLzZlZTFGZWdlTVo4S00xRCtSNFVzCnllOUNqeFZYdTBHN3FxeUxFT3Z5
            QWJySDV6ZkdHR3FyYThaeVhDUzRUK2cKLS0tIDBLMDZWVlBENE9BVkxQTnBPdlBH
            QXFzY08yK0JRK2hEVEE5MzdDUjlDRlkK26ciQbd7chEv9xvmgb4XmqL7VzQlGxnL
            okDW+WraZ1vZKX8goSXZybd+ED7TMN1a2Metb4pCRoM2M8nd5S7/Lw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-08-22T22:43:50Z"
    mac: ENC[AES256_GCM,data:0UvmwW6Ux6T4l8TVmGyTWCAH2eGhRLINek279RunaqDD/roq88S8Qw/xFBQTDQW0zkwnpLVAxpPSIq0ul65ngBcPcHezmt7fg0WzGtw7TonqIw7DxS1ZNXxB5ICia8tSLGs3F+P2K4UytCuKivJ3P2eTKspcCe7ode+rArUpXho=,iv:9GvVxbscNHFISdipPrL2g4oyl/kRTYulE0JOg6y8DGI=,tag:IE5pgW0twAK2UKUJSTSmNw==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdAY6pNwthInaz3Mvd9JiFEONyB5DmXFP716FTgq3S5nEww
            wsnrdSSmw3C5IwhOCSz2Koc0mF9JzSY8s3oyvhuKNTnT0+NgU6pK5UMNfYBUdVGh
            0l4BkBOJEDBhs3w9JC8i+anLlVpnYlX5ISVGGWxDk8RXMykGrGvg03iNSo9I4k2x
            yYO0mwEg+o7BxwOnlWgjBWEuBwxVKYII4+wrfCoNuxigb+e41kafI2aGL6364VK6
            =GgQJ
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    unencrypted_suffix: _unencrypted
    version: 3.13.3
