apiVersion: ENC[AES256_GCM,data:YBoFTfFI2KCtOd7f,iv:/ep6qKpk7xVzywmtYjcKKRbFpeasAbxZ0WHhy4VQM5M=,tag:JqJZWZkal6RYaSBLDi481g==,type:str]
kind: ENC[AES256_GCM,data:wB+DmJ9GIIluHjI8OFzAO+bmd4np+G49,iv:LGvhqKVyG8qWBEI0h4O6RR8R4guI3tC94aRkWbAUhN8=,tag:b0vGKPv2ZMjVUDgW6QWDLg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:FJLW9rX19m+aMg==,iv:/PyrSennSrDbYTpScVeDOhk1ck+T0dwVaXhKaARG9mE=,tag:4oLUB/72qXcqoJBUkZqxIw==,type:str]
spec:
    blocks:
        - cidr: ENC[AES256_GCM,data:d/SaPBESwyaXbsPSOk0PmqJmaVuNPY8=,iv:8jzkCevOan33hDJEtiBZP9PWJSj1bgZJTXOWgZ5fEi8=,tag:CCOKi7QRERyuLFzDEd9mkw==,type:str]
        - cidr: ENC[AES256_GCM,data:suNSyMCw54Kgeg/gsQ==,iv:5CWSfQJrAR+nCnDJuteA7TaU+IW2be08EnTEQCWelwY=,tag:KzcJh9oX8j6ZtJ4zPHaI7A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZkdVQXlWSXZtaXJvNWJp
            bmtFSXVSbHp0OWw3QkJLMVJCc1BCU0sxbFd3Cmw5MCtGRWtWdEFldmtSWEJ0dVg2
            UElJU1pnL3o0ekRvNVE4SzV5SnZReHMKLS0tIEpTSDNoVUx0aFhjd2lKVWpydFFh
            MFR5d1V0Y1FRNlhMMnYxRmtVMks5ak0KkCQFZ/UYxJaK8vDeHJN9+74UrpExjHjD
            K3M8namLWCAwGDEQaxXSW/rghEFVIzd7KXLeOgKoAIrcARPYPeAM+Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
    lastmodified: "2026-08-22T22:36:10Z"
    mac: ENC[AES256_GCM,data:oj7Fyeg4OYFfEtGNoreaQ2S0jWkYl9r7li4wDc5PRsQuMPhkX7H8fXJXjR1pqniiDM/ZjNfjEekP8mJsG9QFfOaLzL6xmjpmTkdlzfGHlUGDrh++UPewdsmxEOhO0HNQuzABlgDSybQRON6DQMsVkOQcUUiGWDCMuGuuzC6LcBA=,iv:jf9QHLSa1zxpaHxsF+5ShM9oSouhEUIo39kzOEtsF2Y=,tag:wvSFWRJLI/3eQ7WfwKe30Q==,type:str]
    pgp:
        - created_at: "2026-08-26T16:59:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4D8x4N7lmZIqkSAQdAD6KR9hNHKgJgjqu4n6Rf0aYeCOLbqAq7kKYLqet66mYw
            amu5eg50C6KSW45tXb3KP6/UE+I4H0pKijjILIJpn+i7ha8iSe5GtdTOIRkqJVS5
            0lwB3eocjAummNwmESCSOSRLZmgZE0v2PAfb4pZwKSxWMqWMY/+EJQfOOcBquidL
            NIOjwfswhu6xPryvMqyu7notzXO72k2Y9WJyPj3eqNMnLdWA7Z7KjG5sBPkAww==
            =bIhE
            -----END PGP MESSAGE-----
          fp: 50C5DE2634B79DEA87206C8B27165D579CEB4919
    unencrypted_suffix: _unencrypted
    version: 3.13.3
