# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 5m0s
  chart:
    spec:
      chart: metrics-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
