snapshotsEnabled: ENC[AES256_GCM,data:33JYC3Y=,iv:PcZ4YUlc9f8ZEAatYxR/AYIVtDMxgqaGgQxdNObcLOY=,tag:iRac0HX4eweXB8H5RhrnCg==,type:bool]
deployNodeAgent: ENC[AES256_GCM,data:YfNLrA==,iv:ZZqkNTxpSJKMfqHUiVJsWEIeR8BxC4oJopiPuBdMJLg=,tag:Tslo5AkvatjL20FACLHCqA==,type:bool]
credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:QnJU/twryebCKPJWokA2K24Z36zgTtFADVRnnfeVL2cXPxpDIBISDJUHxRSJPvUlIMK9hhhTYSXPHfGn7Mgo7UNyIOBO9puGMWryonwpStX9K3HsX5dSR3Y1zRWu5Vm/RYw+4s9gGsEsQXVn4/lvbUS6Q8k=,iv:lvsJsN9Ed2zf7bGPwh9PyLHJj9aJrweyPKeGGv+CPnU=,tag:bgo9E0Llp6KnlKHR6087IQ==,type:str]
configuration:
    backupStorageLocation:
        - name: ENC[AES256_GCM,data:blYZApwhag==,iv:+YPQ9RB0rAs6Biifds+bsL0FYNFEB6iNmMjf7b/Mqj8=,tag:0pSHgPMUoC4UVSBcgjVM/w==,type:str]
          bucket: ENC[AES256_GCM,data:6JhUIcDQ,iv:gFyJFvVr3k5GHoMoeb8TbzZORgLP6aSYID10RS20x7I=,tag:Z+I52PPdK8ZUKqnBUmfD7w==,type:str]
          prefix: ENC[AES256_GCM,data:Jm7ZMw==,iv:by4eHGIFhXICm1KxTp8K70WClxH4vSadfMePTNHeT44=,tag:soVWH+pXJbaLmW52CjW9Bw==,type:str]
          provider: ENC[AES256_GCM,data:+fgK,iv:PlzqirWjXZkSUjiJKmOY8/8vzZbRqW1KIfO8W/ABCeU=,tag:ZdQMjZTCXfGDe1ciIvxGjA==,type:str]
          config:
            region: ENC[AES256_GCM,data:pZOe,iv:PLfX3GTo8wmXxFFMP1j0W4Y/Di/f81flHaL0ut2EzhA=,tag:7DIMU/NqwU6m5b2JFOjD0A==,type:str]
            s3Url: ENC[AES256_GCM,data:YZ3t43/i8r3gK7W1zcdCNC+E70MlGOHHw/KVoUkHYw==,iv:18svGw6VgZUpHxNi62tSh6wQOfsdde8YLrJuM2tUEiI=,tag:yRUucjeKMdoiRdKqyxYE8g==,type:str]
            s3ForcePathStyle: ENC[AES256_GCM,data:lkV2fQ==,iv:xPGcyR+xmAp7CVJwWYmWwuy3nQMCMa2RLceO1Cv5Ekk=,tag:LZBRf8dtBN6I9mEwSHCNfA==,type:bool]
            checksumAlgorithm: ""
initContainers:
    - name: ENC[AES256_GCM,data:z/++Gq0HQQgNC3P7yUp6TFSxI0C8,iv:/FQ6yZh1VYzgQo7dV4eznuraN2BqT4yFAe6E70zxqC4=,tag:+3+Y+mRUvpboGnYkk0IAxg==,type:str]
      image: ENC[AES256_GCM,data:6b/uctWTw905/7UitdSC0fwx8uEyM0mr2JmAh2hE+KHtM8Qg,iv:wX/QklvqiTcI+zxbBKOKkQxsuhpYoUVTnY9esh74NGE=,tag:XoMyiCCXxsEOGxD75oWAPA==,type:str]
      imagePullPolicy: ENC[AES256_GCM,data:+0EE0qQI8ljM76Nr,iv:zelUekBcqxFLjtbnlR5/SEvf2LeAvllGIlJDoZNsNgQ=,tag:8Roa2XZCorzcVvYDtSdxEw==,type:str]
      volumeMounts:
        - mountPath: ENC[AES256_GCM,data:lIiNGVd3/A==,iv:Qmi4iEErsh74OnnySeen8Goc7Huw2p+2/y+LZYZgGog=,tag:VvuJd7rr7zistB0G0dYLzA==,type:str]
          name: ENC[AES256_GCM,data:sirNLHo52Q==,iv:hHk5TQnm4WDiaoP362qb+vwu4zeIcY+nWHSrtSbe6hI=,tag:AIdWqlKAFAnrGt8BsLGNOw==,type:str]
extraObjects:
    - apiVersion: ENC[AES256_GCM,data:mWo=,iv:xZiqg8krx202nVVOsmN+cZ2fCtzE531ueHvejioXfYw=,tag:F/Sj2eb+MAJZUC4l4n4o/Q==,type:str]
      kind: ENC[AES256_GCM,data:8eCAe18N,iv:p939vz1Bskw88XYTz1VId4FzaV1kC6QVypPwov/5XfY=,tag:iQ0+Fo5YZO3eA6A1qn/rVw==,type:str]
      metadata:
        name: ENC[AES256_GCM,data:OHzLBAS2bsMFWRWsTume88IZ9xJGnZM=,iv:/yEXy6OU4CBi81yOTwmTOQDKTcIM/yuKeJrn+W5Tvic=,tag:hlx8Fo359SkTf7mJnjxGfQ==,type:str]
      type: ENC[AES256_GCM,data:nqAE9O2R,iv:ydcmWAFx3ett6g8KbTImV+aZ/cdy8HYLTmEM7VAqPPI=,tag:dUea03HTkgwxYzfgGDPVjw==,type:str]
      stringData:
        repository-password: ENC[AES256_GCM,data:E8jpb8dDoe80MGGi4VWnfMSSntrS0KvM,iv:WKjP2Z/fD/cZGe2NoFpc5QptWbxy4wZ2gcu4Jif0CaY=,tag:kEO5otwzjfR9w4kfLjt6BA==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYi9pbWE1NjFXaWJjcEFT
            TURlb0U4T2EwcGFXeE9zTnR4bjh6endzN2xjCm9HSFMwYWZ3TVBjK3phamZNSi85
            Ymc4amdxL01hZlE4Z09wd3pta0p2OVkKLS0tIHRxQkIvWEtBdG1yb1lBdGQzUWN5
            eFYwYVV1REg5emwrSzVPWTZXZDB1NTgKP2x4OXA5p2DMtb6zF1FQcZoWz5cXOTlz
            9K7XWpz+xHDubd325utFAl8F7U1FN1wwE/P9bXoNkhqHLFCTkXi4AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-14T11:49:31Z"
    mac: ENC[AES256_GCM,data:EXE2FpyCA5crqc8vgNyxffRwOwYde3vPBky2EAkrJ1ripeLGZkikGZZkD1Vfu/aAiU3vjE6wU+q7WZPvm4yGXsUI2TjSci1hJ5SmgroLcE2a0bQf6tDfUwBndlo1GOHPwQMPWgkKtyS1zMtRfS9VuXMyqzCfb+Vy7b9vC1vKIEs=,iv:YmpWNhtZKCKruPJr1T+VT9m5JI+Cll5AUL1NVBSl8Lk=,tag:0fXHSlMr+P7YB8K/Phrt6g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
