snapshotsEnabled: ENC[AES256_GCM,data:33JYC3Y=,iv:PcZ4YUlc9f8ZEAatYxR/AYIVtDMxgqaGgQxdNObcLOY=,tag:iRac0HX4eweXB8H5RhrnCg==,type:bool]
deployNodeAgent: ENC[AES256_GCM,data:YfNLrA==,iv:ZZqkNTxpSJKMfqHUiVJsWEIeR8BxC4oJopiPuBdMJLg=,tag:Tslo5AkvatjL20FACLHCqA==,type:bool]
credentials:
    secretContents:
        cloud: ENC[AES256_GCM,data:QnJU/twryebCKPJWokA2K24Z36zgTtFADVRnnfeVL2cXPxpDIBISDJUHxRSJPvUlIMK9hhhTYSXPHfGn7Mgo7UNyIOBO9puGMWryonwpStX9K3HsX5dSR3Y1zRWu5Vm/RYw+4s9gGsEsQXVn4/lvbUS6Q8k=,iv:lvsJsN9Ed2zf7bGPwh9PyLHJj9aJrweyPKeGGv+CPnU=,tag:bgo9E0Llp6KnlKHR6087IQ==,type:str]
configuration:
    backupStorageLocation:
        - name: ENC[AES256_GCM,data:blYZApwhag==,iv:+YPQ9RB0rAs6Biifds+bsL0FYNFEB6iNmMjf7b/Mqj8=,tag:0pSHgPMUoC4UVSBcgjVM/w==,type:str]
          bucket: ENC[AES256_GCM,data:6JhUIcDQ,iv:gFyJFvVr3k5GHoMoeb8TbzZORgLP6aSYID10RS20x7I=,tag:Z+I52PPdK8ZUKqnBUmfD7w==,type:str]
          prefix: ENC[AES256_GCM,data:Jm7ZMw==,iv:by4eHGIFhXICm1KxTp8K70WClxH4vSadfMePTNHeT44=,tag:soVWH+pXJbaLmW52CjW9Bw==,type:str]
          provider: ENC[AES256_GCM,data:+fgK,iv:PlzqirWjXZkSUjiJKmOY8/8vzZbRqW1KIfO8W/ABCeU=,tag:ZdQMjZTCXfGDe1ciIvxGjA==,type:str]
          config:
            region: ENC[AES256_GCM,data:pZOe,iv:PLfX3GTo8wmXxFFMP1j0W4Y/Di/f81flHaL0ut2EzhA=,tag:7DIMU/NqwU6m5b2JFOjD0A==,type:str]
            s3Url: ENC[AES256_GCM,data:YZ3t43/i8r3gK7W1zcdCNC+E70MlGOHHw/KVoUkHYw==,iv:18svGw6VgZUpHxNi62tSh6wQOfsdde8YLrJuM2tUEiI=,tag:yRUucjeKMdoiRdKqyxYE8g==,type:str]
            s3ForcePathStyle: ENC[AES256_GCM,data:lkV2fQ==,iv:xPGcyR+xmAp7CVJwWYmWwuy3nQMCMa2RLceO1Cv5Ekk=,tag:LZBRf8dtBN6I9mEwSHCNfA==,type:bool]
            checksumAlgorithm: ""
initContainers:
    - name: ENC[AES256_GCM,data:z/++Gq0HQQgNC3P7yUp6TFSxI0C8,iv:/FQ6yZh1VYzgQo7dV4eznuraN2BqT4yFAe6E70zxqC4=,tag:+3+Y+mRUvpboGnYkk0IAxg==,type:str]
      image: ENC[AES256_GCM,data:6b/uctWTw905/7UitdSC0fwx8uEyM0mr2JmAh2hE+KHtM8Qg,iv:wX/QklvqiTcI+zxbBKOKkQxsuhpYoUVTnY9esh74NGE=,tag:XoMyiCCXxsEOGxD75oWAPA==,type:str]
      imagePullPolicy: ENC[AES256_GCM,data:+0EE0qQI8ljM76Nr,iv:zelUekBcqxFLjtbnlR5/SEvf2LeAvllGIlJDoZNsNgQ=,tag:8Roa2XZCorzcVvYDtSdxEw==,type:str]
      volumeMounts:
        - mountPath: ENC[AES256_GCM,data:lIiNGVd3/A==,iv:Qmi4iEErsh74OnnySeen8Goc7Huw2p+2/y+LZYZgGog=,tag:VvuJd7rr7zistB0G0dYLzA==,type:str]
          name: ENC[AES256_GCM,data:sirNLHo52Q==,iv:hHk5TQnm4WDiaoP362qb+vwu4zeIcY+nWHSrtSbe6hI=,tag:AIdWqlKAFAnrGt8BsLGNOw==,type:str]
sops:
    age:
        - recipient: age164zdqnr4yzgxjyxp8mlxkn9z5nanl9u4p7s95x95spkjl2x85gqqfl8r00
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEYi9pbWE1NjFXaWJjcEFT
            TURlb0U4T2EwcGFXeE9zTnR4bjh6endzN2xjCm9HSFMwYWZ3TVBjK3phamZNSi85
            Ymc4amdxL01hZlE4Z09wd3pta0p2OVkKLS0tIHRxQkIvWEtBdG1yb1lBdGQzUWN5
            eFYwYVV1REg5emwrSzVPWTZXZDB1NTgKP2x4OXA5p2DMtb6zF1FQcZoWz5cXOTlz
            9K7XWpz+xHDubd325utFAl8F7U1FN1wwE/P9bXoNkhqHLFCTkXi4AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-23T21:17:51Z"
    mac: ENC[AES256_GCM,data:i5MFcNewuhu8l6bBs4APsQBueDIhnngCs0uBMUfmlMS+wPuj2bSf8u3PRa+KHkGq44+vU9ZyPybaZpsmIFx0bbSMaQEjJ87VjEVvnjL08PvLIJmJBEVnSfFRwhELlb2DsGzVUKq/2ZzZLvX3YLGwBBIA4lAukWJqwmk1G98m2xA=,iv:pPJA+rGHBAeAUwFx3sdIkfFBq2H4tE13fT1Lq8ZSlDc=,tag:OQ8ASERa2WLeQBVCuoWNsQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
