# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: backube
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://backube.github.io/helm-charts
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: volsync
  namespace: kube-system
spec:
  interval: 5m0s
  chart:
    spec:
      chart: volsync
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: backube
        namespace: flux-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
